module

public import Mathlib
public import stacks_project.Chap08.Definition_8_4_1
public import stacks_project.Chap07.Lemma_7_12_4


@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe u₁ u₂ v₁ v₂ vDesc

namespace CategoryTheory

open GrothendieckTopology.Cover

section

variable {C : Type u₁} {X : Type u₂} [Category.{v₁} C] [Category.{v₂} X]
variable (J : GrothendieckTopology C) (p : X ⥤ C) [p.IsFibered]

/- Domain-style sampling for Lemma 8.4.2:
- primary domain: stacks over a site, expressed through the canonical fiber pseudofunctor and
  descent-data equivalences for covering families.
- inspected owner-level declarations:
  `IsStackOnSite`,
  `Pseudofunctor.IsStackFor`,
  `Pseudofunctor.isStackFor'`,
  `Pseudofunctor.isStackFor_ofArrows_iff`,
  `Pseudofunctor.IsStack.of_isStackFor`.
- best owner abstraction: the source-facing owner is `IsStackOnSite J p`; the chosen-pullback
  system underlying `canonicalFiberPseudofunctor p` is not new public data here.
- primitive data: a fibred projection `p` together with the stack condition on
  `canonicalFiberPseudofunctor p`.
- derived API: the fixed-cover stack condition for `((S : Sieve U).arrows)` and the equivalent
  cover-indexed descent-data functor.

Source/core/bridge triage:
- `source-facing`: `IsStackOnSite J p` and Lemma 8.4.2.
- `core/canonical`: `Pseudofunctor.IsStack (canonicalFiberPseudofunctor p) J`.
- `bridge/view`: the cover-to-presieve identification `S.ofArrows_eq`, used to pass between a
  `J.Cover U` and the canonical `IsStackFor` owner for the underlying covering sieve. -/

/-- Helper for Lemma 8.4.2: the owner-level stack condition on the covering sieve attached to `S`
is equivalent to the descent-data functor for the family of cover arrows being an equivalence. -/
theorem canonicalFiberPseudofunctor_isStackFor_cover_iff {U : C} (S : J.Cover U) :
    (canonicalFiberPseudofunctor p).IsStackFor ((S : Sieve U).arrows) ↔
      ((canonicalFiberPseudofunctor p).toDescentData (fun I : S.Arrow ↦ I.f)).IsEquivalence := by
  let F := canonicalFiberPseudofunctor p
  let f : ∀ I : S.Arrow, I.Y ⟶ U := fun I ↦ I.f
  -- First replace the covering sieve by the presieve generated by the cover arrows.
  have hsieve :
      F.IsStackFor ((S : Sieve U).arrows) ↔
        F.IsStackFor (Presieve.ofArrows Arrow.Y f) := by
    exact F.isStackFor_iff_of_sieve_eq <| by
      simpa [f, Sieve.ofArrows] using S.ofArrows_eq.symm
  -- Then invoke the canonical `ofArrows` descent criterion for the same family.
  have hofArrows :
      F.IsStackFor (Presieve.ofArrows Arrow.Y f) ↔ (F.toDescentData f).IsEquivalence := by
    exact F.isStackFor_ofArrows_iff f
  simpa [F, f] using hsieve.trans hofArrows

/-- Lemma 8.4.2: a fibred category over `(C, J)` is a stack exactly when, for every cover
`S : J.Cover U`, the canonical functor from the fiber over `U` to the corresponding category of
descent data is an equivalence. -/
theorem isStackOnSite_iff_coverwise_canonicalDescentFunctor_isEquivalence :
    IsStackOnSite J p ↔
      ∀ (U : C) (S : J.Cover U),
        ((canonicalFiberPseudofunctor p).toDescentData (fun I : S.Arrow ↦ I.f)).IsEquivalence := by
  let F := canonicalFiberPseudofunctor p
  constructor
  · intro hp U S
    -- The site-level stack owner gives `IsStackFor` for every covering sieve.
    let _ : IsStackOnSite J p := hp
    exact (canonicalFiberPseudofunctor_isStackFor_cover_iff J p S).1 <| by
      simpa [F] using F.isStackFor' (S : Sieve U) S.condition
  · intro h
    -- Rebuild the canonical stack owner by checking `IsStackFor` on an arbitrary covering sieve.
    letI : Pseudofunctor.IsStack F J := by
      refine Pseudofunctor.IsStack.of_isStackFor ?_
      intro U R hR
      let S : J.Cover U := ⟨R, hR⟩
      simpa [F] using (canonicalFiberPseudofunctor_isStackFor_cover_iff J p S).2 (h U S)
    exact isStackOnSite_of_isStack J p

end

end CategoryTheory
