module

public import stacks_project.Chap07.Lemma_7_26_4.TerminalCovers

@[expose] public section

open CategoryTheory

universe u v w

namespace CategoryTheory
namespace GrothendieckTopology

section

variable {C : Type u} [Category.{v} C]
variable {J : GrothendieckTopology C} {U : C}

/-- Helper for Lemma 7.26.4: the terminal specialization of the component comparison is a genuine
equivalence, so applying it after its inverse recovers the original terminal section. -/
theorem localized_cover_descent_glue_component_terminal_equiv_apply_symm
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (t : (D.obj I).1.obj (Opposite.op (Over.mk (𝟙 I.Y)))) :
    localized_cover_descent_glue_component_terminal_equiv
        (J := J) (U := U) 𝒰 D I
        ((localized_cover_descent_glue_component_terminal_equiv
          (J := J) (U := U) 𝒰 D I).symm t) =
      t := by
  -- The terminal comparison is an equivalence, so its inverse is a true inverse on sections.
  exact Equiv.apply_symm_apply
    (localized_cover_descent_glue_component_terminal_equiv
      (J := J) (U := U) 𝒰 D I)
    t

/-- Helper for Lemma 7.26.4: restricting the future glued presheaf along `I.f` and then
evaluating at `T : Over I.Y` amounts to looking at the pullback cover over the composite
`T.hom ≫ I.f`. This is the canonical cover-index identification needed in the objectwise
restriction comparison for the source-style glued presheaf. -/
theorem localized_cover_descent_pullback_comp_eq_pullback_pullback
    (𝒰 : J.Cover U)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :
    𝒰.pullback (T.hom ≫ I.f) = ((𝒰.pullback I.f).pullback T.hom) := by
  -- Both pullback covers are generated by the same composite map to `U`.
  ext Z g
  simp [GrothendieckTopology.Cover.coe_pullback, Category.assoc]

/-- Helper for Lemma 7.26.4: restricting the future glued presheaf along `I.f` and then
evaluating at `T : Over I.Y` amounts to looking at the pullback cover over the composite
`T.hom ≫ I.f`. This is the canonical cover-index identification needed in the objectwise
restriction comparison for the source-style glued presheaf. -/
theorem localized_cover_descent_overMap_obj_hom
    (𝒰 : J.Cover U)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :
    ((Over.map I.f).obj T).hom = T.hom ≫ I.f := by
  -- `Over.map` sends `T : Over I.Y` to the same object with structure map postcomposed by `I.f`.
  rfl

/-- Helper for Lemma 7.26.4: restricting the future glued presheaf along `I.f` and then
evaluating at `T : Over I.Y` amounts to looking at the pullback cover over the composite
`T.hom ≫ I.f`. This is the canonical cover-index identification needed in the objectwise
restriction comparison for the source-style glued presheaf. -/
theorem localized_cover_descent_pullback_overMap_obj_eq_pullback_pullback
    (𝒰 : J.Cover U)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :
    𝒰.pullback ((Over.map I.f).obj T).hom = ((𝒰.pullback I.f).pullback T.hom) := by
  -- Both pullback covers are defined by the same composite structure map `T.hom ≫ I.f`.
  change 𝒰.pullback (T.hom ≫ I.f) = ((𝒰.pullback I.f).pullback T.hom)
  exact localized_cover_descent_pullback_comp_eq_pullback_pullback (J := J) (U := U) 𝒰 I T

/-- Helper for Lemma 7.26.4: after restricting the original descent datum to a cover member `I`
and then pulling back further along `T : Over I.Y`, one obtains the ordinary descent datum of the
pulled-back component sheaf `((J.overMapPullback (Type w) T.hom).obj (D.obj I))` on the doubly
pulled-back cover. This is the arbitrary-`T` bridge used before packaging the final glued
presheaf restriction isomorphism. -/
noncomputable def localized_cover_descent_pullbackDatum_toDescentData_over
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :
    (Pseudofunctor.DescentData.pullFunctor (J.pseudofunctorOver (Type w))
      (f := fun K : (𝒰.pullback I.f).Arrow ↦ K.f)
      (p := T.hom)
      (f' := fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)
      (α := fun K ↦ K.base)
      (p' := fun _ ↦ 𝟙 _)
      (w := localized_cover_descent_pullbackDatum_w (J := J) (U := I.Y)
        (𝒰.pullback I.f) T)).obj
      (localized_cover_descent_pullbackDatum (J := J) (U := U) 𝒰 D (Over.mk I.f)) ≅
      (((J.pseudofunctorOver (Type w)).toDescentData
        (fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)).obj
        ((J.overMapPullback (Type w) T.hom).obj (D.obj I))) := by
  let w₂ :
      ∀ K : ((𝒰.pullback I.f).pullback T.hom).Arrow, (𝟙 K.Y) ≫ K.base.f = K.f ≫ T.hom :=
    localized_cover_descent_pullbackDatum_w (J := J) (U := I.Y) (𝒰.pullback I.f) T
  -- Route correction: first pull back the already-solved `I`-level comparison along `T.hom`.
  -- The remaining direct-vs-iterated pullback identification is kept separate from this
  -- structural bridge.
  refine ((Pseudofunctor.DescentData.pullFunctor (J.pseudofunctorOver (Type w))
      (f := fun K : (𝒰.pullback I.f).Arrow ↦ K.f)
      (p := T.hom)
      (f' := fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)
      (α := fun K ↦ K.base)
      (p' := fun _ ↦ 𝟙 _)
      (w := w₂)).mapIso
      (localized_cover_descent_pullbackDatum_toDescentData_obj
        (J := J) (U := U) 𝒰 D I)) ≪≫ ?_
  exact
    (Pseudofunctor.DescentData.toDescentDataCompPullFunctorIso
      (J.pseudofunctorOver (Type w))
      (f := fun K : (𝒰.pullback I.f).Arrow ↦ K.f)
      (p := T.hom)
      (f' := fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)
      (α := fun K ↦ K.base)
      (p' := fun _ ↦ 𝟙 _)
      (w := w₂)).app (D.obj I)

/-- Helper for Lemma 7.26.4: after transporting along the canonical identification of pullback
covers, the direct pullback datum over `((Over.map I.f).obj T)` is literally the same object as
the iterated pullback datum obtained by first restricting to `I` and then pulling back along
`T.hom`. This isolates the only dependent cast needed before the final objectwise restriction
comparison. -/
theorem localized_cover_descent_pullbackDatum_over_direct_type
    (𝒰 : J.Cover U)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :
    (J.pseudofunctorOver (Type w)).DescentData
        (fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f) =
      (J.pseudofunctorOver (Type w)).DescentData
        (fun K : (𝒰.pullback ((Over.map I.f).obj T).hom).Arrow ↦ K.f) := by
  -- Rewriting the pullback cover along `((Over.map I.f).obj T).hom = T.hom ≫ I.f` aligns the two
  -- indexing families, so the ambient descent-data types coincide.
  rw [localized_cover_descent_pullback_overMap_obj_eq_pullback_pullback
    (J := J) (U := U) 𝒰 I T]
  rfl

/-- Helper for Lemma 7.26.4: after expressing the direct pullback along
`((Over.map I.f).obj T).hom = T.hom ≫ I.f` on the iterated pullback cover itself, the resulting
direct composite pullback datum is canonically isomorphic to the iterated pullback datum. This is
the cast-free source comparison behind the later direct-vs-iterated restriction bridge. -/
noncomputable def localized_cover_descent_pullbackDatum_over_direct_source_iso
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :
    (Pseudofunctor.DescentData.pullFunctor (J.pseudofunctorOver (Type w))
      (f := fun K : (𝒰.pullback I.f).Arrow ↦ K.f)
      (p := T.hom)
      (f' := fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)
      (α := fun K ↦ K.base)
      (p' := fun _ ↦ 𝟙 _)
      (w := localized_cover_descent_pullbackDatum_w (J := J) (U := I.Y)
        (𝒰.pullback I.f) T)).obj
      (localized_cover_descent_pullbackDatum
        (J := J) (U := U) 𝒰 D (Over.mk I.f)) ≅
      (Pseudofunctor.DescentData.pullFunctor (J.pseudofunctorOver (Type w))
        (f := fun JI : 𝒰.Arrow ↦ JI.f)
        (p := ((Over.map I.f).obj T).hom)
        (f' := fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)
        (α := fun K ↦ K.base.base)
        (p' := fun _ ↦ 𝟙 _)
        (w := fun K ↦ by
          -- Normalize the direct composite witness to the underlying cover equation on `K`.
          change (𝟙 K.Y) ≫ K.base.base.f = K.f ≫ ((Over.map I.f).obj T).hom
          rw [show K.base.base.f = K.base.f ≫ I.f by
            simpa [GrothendieckTopology.Cover.Arrow.base] using
              localized_cover_descent_pullbackDatum_w
                (J := J) (U := U) 𝒰 (Over.mk I.f) K.base]
          rw [show K.base.f = K.f ≫ T.hom by
            simpa using
              localized_cover_descent_pullbackDatum_w
                (J := J) (U := I.Y) (𝒰.pullback I.f) T K]
          simp [Category.assoc])).obj D := by
  -- Compare the two-stage pullback (`I.f` then `T.hom`) with the one-stage pullback along the
  -- composite `((Over.map I.f).obj T).hom = T.hom ≫ I.f`; `pullFunctorCompIso` gives exactly the
  -- comparison between that one-step pullback and the two-step pullback.
  let e :=
    (Pseudofunctor.DescentData.pullFunctorCompIso
      (F := J.pseudofunctorOver (Type w))
      (f := fun JI : 𝒰.Arrow ↦ JI.f)
      (p := I.f)
      (f' := fun K : (𝒰.pullback I.f).Arrow ↦ K.f)
      (α := fun K ↦ K.base)
      (p' := fun _ ↦ 𝟙 _)
      (w := localized_cover_descent_pullbackDatum_w (J := J) (U := U) 𝒰 (Over.mk I.f))
      (q := T.hom)
      (f'' := fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)
      (β := fun K ↦ K.base)
      (q' := fun _ ↦ 𝟙 _)
      (w' := localized_cover_descent_pullbackDatum_w (J := J) (U := I.Y)
        (𝒰.pullback I.f) T)
      (r := ((Over.map I.f).obj T).hom)
      (r' := fun _ ↦ 𝟙 _)
      (hr := by rfl)
      (hr' := by intro K; simp))
  exact e.app D

/-- Helper for Lemma 7.26.4: an arrow in the iterated pullback cover over `I` and then `T`
already satisfies the direct composite compatibility for the single pullback along
`((Over.map I.f).obj T).hom = T.hom ≫ I.f`. This isolates the source-side cover equation needed
before packaging the direct-vs-iterated pullback comparison. -/
theorem localized_cover_descent_pullback_over_direct_w
    (𝒰 : J.Cover U)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (K : ((𝒰.pullback I.f).pullback T.hom).Arrow) :
    (𝟙 K.Y) ≫ K.base.base.f = K.f ≫ ((Over.map I.f).obj T).hom := by
  -- First rewrite the outer pullback condition over `I`, then substitute the inner pullback
  -- condition over `T`; the result is exactly the direct composite equation.
  rw [show K.base.base.f = K.base.f ≫ I.f by
    simpa [GrothendieckTopology.Cover.Arrow.base] using
      localized_cover_descent_pullbackDatum_w (J := J) (U := U) 𝒰 (Over.mk I.f) K.base]
  rw [show K.base.f = K.f ≫ T.hom by
    simpa using
      localized_cover_descent_pullbackDatum_w (J := J) (U := I.Y) (𝒰.pullback I.f) T K]
  simp [Category.assoc]

/-- Helper for Lemma 7.26.4: after first restricting the original descent datum to `I` and then
pulling back further along `T : Over I.Y`, the resulting source-side descent datum over the
iterated pullback cover is the concrete object whose terminal sections will later be reassembled
into the glued presheaf. -/
abbrev localized_cover_descent_pullbackDatum_over_source
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :=
  (Pseudofunctor.DescentData.pullFunctor (J.pseudofunctorOver (Type w))
    (f := fun K : (𝒰.pullback I.f).Arrow ↦ K.f)
    (p := T.hom)
    (f' := fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)
    (α := fun K ↦ K.base)
    (p' := fun _ ↦ 𝟙 _)
    (w := localized_cover_descent_pullbackDatum_w (J := J) (U := I.Y)
      (𝒰.pullback I.f) T)).obj
    (localized_cover_descent_pullbackDatum (J := J) (U := U) 𝒰 D (Over.mk I.f))

/-- Helper for Lemma 7.26.4: evaluating the ordinary descent datum of the pulled-back component
sheaf at the terminal object of `Over K.Y` reduces to evaluating that pulled-back component sheaf
at the overlap object `Over.mk K.f`. This is the arbitrary-`T` target-side section normal form.
-/
theorem localized_cover_descent_toDescentData_over_section_eq
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (K : ((𝒰.pullback I.f).pullback T.hom).Arrow) :
    (((((J.pseudofunctorOver (Type w)).toDescentData
        (fun L : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ L.f)).obj
        ((J.overMapPullback (Type w) T.hom).obj (D.obj I))).obj K).1.obj
      (Opposite.op (Over.mk (𝟙 K.Y)))) =
      ((((J.overMapPullback (Type w) T.hom).obj (D.obj I)).1).obj
        (Opposite.op (Over.mk K.f))) := by
  -- The `K`-component of `toDescentData` is exactly the pullback of the component sheaf along
  -- `K.f`, so the terminal object of `Over K.Y` evaluates to the overlap object `Over.mk K.f`.
  simpa [Pseudofunctor.toDescentData] using
    (localized_cover_descent_overMap_terminal_section_eq
      (J := J) (f := K.f)
      (M := (J.overMapPullback (Type w) T.hom).obj (D.obj I)))

/-- Helper for Lemma 7.26.4: on each iterated pullback-cover member `K`, the arbitrary-`T`
comparison isomorphism from the source-side iterated pullback datum to the ordinary descent datum
of the pulled-back component sheaf has a concrete sheaf-level `K`-component. -/
noncomputable def localized_cover_descent_pullbackDatum_over_component_iso
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (K : ((𝒰.pullback I.f).pullback T.hom).Arrow) :
    (localized_cover_descent_pullbackDatum_over_source
      (J := J) (U := U) 𝒰 D I T).obj K ≅
      (((((J.pseudofunctorOver (Type w)).toDescentData
          (fun L : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ L.f)).obj
          ((J.overMapPullback (Type w) T.hom).obj (D.obj I))).obj K)) where
  hom :=
    (localized_cover_descent_pullbackDatum_toDescentData_over
      (J := J) (U := U) 𝒰 D I T).hom.hom K
  inv :=
    (localized_cover_descent_pullbackDatum_toDescentData_over
      (J := J) (U := U) 𝒰 D I T).inv.hom K
  hom_inv_id := by
    have hK :
        (localized_cover_descent_pullbackDatum_toDescentData_over
          (J := J) (U := U) 𝒰 D I T).hom.hom K ≫
          (localized_cover_descent_pullbackDatum_toDescentData_over
            (J := J) (U := U) 𝒰 D I T).inv.hom K =
            𝟙 ((localized_cover_descent_pullbackDatum_over_source
              (J := J) (U := U) 𝒰 D I T).obj K) := by
      exact congrArg
        (fun f ↦ f.hom K)
        ((localized_cover_descent_pullbackDatum_toDescentData_over
          (J := J) (U := U) 𝒰 D I T).hom_inv_id)
    exact hK
  inv_hom_id := by
    have hK :
        (localized_cover_descent_pullbackDatum_toDescentData_over
          (J := J) (U := U) 𝒰 D I T).inv.hom K ≫
          (localized_cover_descent_pullbackDatum_toDescentData_over
            (J := J) (U := U) 𝒰 D I T).hom.hom K =
            𝟙 (((((J.pseudofunctorOver (Type w)).toDescentData
              (fun L : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ L.f)).obj
              ((J.overMapPullback (Type w) T.hom).obj (D.obj I))).obj K)) := by
      exact congrArg
        (fun f ↦ f.hom K)
        ((localized_cover_descent_pullbackDatum_toDescentData_over
          (J := J) (U := U) 𝒰 D I T).inv_hom_id)
    exact hK

/-- Helper for Lemma 7.26.4: evaluating the arbitrary-`T` source-side comparison at the terminal
object of `Over K.Y` identifies sections of the iterated pullback datum with sections of the
pulled-back component sheaf over the overlap object `Over.mk K.f`. -/
noncomputable def localized_cover_descent_pullbackDatum_over_section_equiv_component
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (K : ((𝒰.pullback I.f).pullback T.hom).Arrow) :
    (((localized_cover_descent_pullbackDatum_over_source
      (J := J) (U := U) 𝒰 D I T).obj K).1.obj
        (Opposite.op (Over.mk (𝟙 K.Y)))) ≃
      ((((J.overMapPullback (Type w) T.hom).obj (D.obj I)).1).obj
        (Opposite.op (Over.mk K.f))) where
  toFun x :=
    cast
      (localized_cover_descent_toDescentData_over_section_eq
        (J := J) (U := U) 𝒰 D I T K)
      ((localized_cover_descent_pullbackDatum_over_component_iso
        (J := J) (U := U) 𝒰 D I T K).hom.hom.app
          (Opposite.op (Over.mk (𝟙 K.Y))) x)
  invFun y :=
    ((localized_cover_descent_pullbackDatum_over_component_iso
      (J := J) (U := U) 𝒰 D I T K).inv.hom.app
        (Opposite.op (Over.mk (𝟙 K.Y)))
        (cast
          (localized_cover_descent_toDescentData_over_section_eq
            (J := J) (U := U) 𝒰 D I T K).symm y))
  left_inv x := by
    -- Undo the target-side section cast and then apply the inverse relation of the `K`-component
    -- comparison isomorphism.
    let e :=
      ((sheafToPresheaf (J.over K.Y) (Type w)).mapIso
        (localized_cover_descent_pullbackDatum_over_component_iso
          (J := J) (U := U) 𝒰 D I T K)).app
        (Opposite.op (Over.mk (𝟙 K.Y)))
    simpa [e] using CategoryTheory.hom_inv_id_apply e x
  right_inv y := by
    -- The same inverse relation shows that a section of the pulled-back component sheaf is
    -- recovered unchanged from the source-side iterated pullback datum.
    let h :=
      localized_cover_descent_toDescentData_over_section_eq
        (J := J) (U := U) 𝒰 D I T K
    let e :=
      ((sheafToPresheaf (J.over K.Y) (Type w)).mapIso
        (localized_cover_descent_pullbackDatum_over_component_iso
          (J := J) (U := U) 𝒰 D I T K)).app
        (Opposite.op (Over.mk (𝟙 K.Y)))
    simpa [e, h] using congrArg (cast h)
      (CategoryTheory.inv_hom_id_apply e (cast h.symm y))

/-- Helper for Lemma 7.26.4: after normalizing the direct pullback along
`((Over.map I.f).obj T).hom` to the iterated pullback cover, this is the direct source-side
descent datum whose terminal sections encode the textbook compatible families over
`((Over.map I.f).obj T)`. -/
abbrev localized_cover_descent_pullbackDatum_over_direct_source
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :=
  (Pseudofunctor.DescentData.pullFunctor (J.pseudofunctorOver (Type w))
    (f := fun JI : 𝒰.Arrow ↦ JI.f)
    (p := ((Over.map I.f).obj T).hom)
    (f' := fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦ K.f)
    (α := fun K ↦ K.base.base)
    (p' := fun _ ↦ 𝟙 _)
    (w := localized_cover_descent_pullback_over_direct_w (J := J) (U := U) 𝒰 I T)).obj D

/-- Helper for Lemma 7.26.4: on each iterated pullback-cover member `K`, the direct source-side
datum over `((Over.map I.f).obj T)` is canonically identified with the iterated source-side datum.
This isolates the source-faithful direct-to-iterated comparison before compatible families are
packaged as a single subtype. -/
noncomputable def localized_cover_descent_pullbackDatum_over_direct_component_iso
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (K : ((𝒰.pullback I.f).pullback T.hom).Arrow) :
    (localized_cover_descent_pullbackDatum_over_direct_source
      (J := J) (U := U) 𝒰 D I T).obj K ≅
      (localized_cover_descent_pullbackDatum_over_source
        (J := J) (U := U) 𝒰 D I T).obj K where
  hom :=
    (localized_cover_descent_pullbackDatum_over_direct_source_iso
      (J := J) (U := U) 𝒰 D I T).inv.hom K
  inv :=
    (localized_cover_descent_pullbackDatum_over_direct_source_iso
      (J := J) (U := U) 𝒰 D I T).hom.hom K
  hom_inv_id := by
    have hK :
        (localized_cover_descent_pullbackDatum_over_direct_source_iso
          (J := J) (U := U) 𝒰 D I T).inv.hom K ≫
          (localized_cover_descent_pullbackDatum_over_direct_source_iso
            (J := J) (U := U) 𝒰 D I T).hom.hom K =
            𝟙 ((localized_cover_descent_pullbackDatum_over_direct_source
              (J := J) (U := U) 𝒰 D I T).obj K) := by
      exact congrArg
        (fun f ↦ f.hom K)
        ((localized_cover_descent_pullbackDatum_over_direct_source_iso
          (J := J) (U := U) 𝒰 D I T).inv_hom_id)
    exact hK
  inv_hom_id := by
    have hK :
        (localized_cover_descent_pullbackDatum_over_direct_source_iso
          (J := J) (U := U) 𝒰 D I T).hom.hom K ≫
          (localized_cover_descent_pullbackDatum_over_direct_source_iso
            (J := J) (U := U) 𝒰 D I T).inv.hom K =
            𝟙 ((localized_cover_descent_pullbackDatum_over_source
              (J := J) (U := U) 𝒰 D I T).obj K) := by
      exact congrArg
        (fun f ↦ f.hom K)
        ((localized_cover_descent_pullbackDatum_over_direct_source_iso
          (J := J) (U := U) 𝒰 D I T).hom_inv_id)
    exact hK

/-- Helper for Lemma 7.26.4: evaluating the direct source-side pullback datum at the terminal
object of `Over K.Y` and then transporting across the direct-to-iterated comparison recovers the
same component section of the pulled-back sheaf `((J.overMapPullback _ T.hom).obj (D.obj I))` as
the iterated source route. -/
noncomputable def localized_cover_descent_pullbackDatum_over_direct_section_equiv_component
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (K : ((𝒰.pullback I.f).pullback T.hom).Arrow) :
    (((localized_cover_descent_pullbackDatum_over_direct_source
      (J := J) (U := U) 𝒰 D I T).obj K).1.obj
        (Opposite.op (Over.mk (𝟙 K.Y)))) ≃
      ((((J.overMapPullback (Type w) T.hom).obj (D.obj I)).1).obj
        (Opposite.op (Over.mk K.f))) := by
  -- Route correction: compare the direct pullback along `((Over.map I.f).obj T).hom` with the
  -- already-stabilized iterated pullback source, then reuse the existing section-level bridge to
  -- the pulled-back component sheaf.
  refine (((sheafToPresheaf (J.over K.Y) (Type w)).mapIso
      (localized_cover_descent_pullbackDatum_over_direct_component_iso
        (J := J) (U := U) 𝒰 D I T K)).app
        (Opposite.op (Over.mk (𝟙 K.Y)))).toEquiv.trans ?_
  exact localized_cover_descent_pullbackDatum_over_section_equiv_component
    (J := J) (U := U) 𝒰 D I T K

/-- Helper for Lemma 7.26.4: these are the direct source-side terminal sections on the normalized
direct pullback cover above `((Over.map I.f).obj T)`. They are the explicit textbook families
before one switches to the iterated pullback owner. -/
abbrev localized_cover_descent_glue_direct_family_over
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :=
  ∀ K : ((𝒰.pullback I.f).pullback T.hom).Arrow,
    (((localized_cover_descent_pullbackDatum_over_direct_source
      (J := J) (U := U) 𝒰 D I T).obj K).1.obj
        (Opposite.op (Over.mk (𝟙 K.Y))))

/-- Helper for Lemma 7.26.4: the compatibility condition on the direct source-side family is
measured after transporting each terminal section to the pulled-back component sheaf. This keeps
the overlap equation on the stable sheaf `((J.overMapPullback _ T.hom).obj (D.obj I)).1`. -/
def localized_cover_descent_glue_direct_compatible
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (s : localized_cover_descent_glue_direct_family_over (J := J) (U := U) 𝒰 D I T) : Prop :=
  Presieve.Arrows.Compatible
    (((J.overMapPullback (Type w) T.hom).obj (D.obj I)).1)
    (fun K : ((𝒰.pullback I.f).pullback T.hom).Arrow ↦
      (show Over.mk K.f ⟶ Over.mk (𝟙 T.left) from Over.homMk K.f))
    (fun K ↦
      localized_cover_descent_pullbackDatum_over_direct_section_equiv_component
        (J := J) (U := U) 𝒰 D I T K (s K))

/-- Helper for Lemma 7.26.4: this is the missing direct source-compatible-family subtype from the
source proof. After normalizing the cover `𝒰.pullback ((Over.map I.f).obj T).hom` to the iterated
pullback cover, it records exactly the direct compatible families of terminal sections. -/
abbrev localized_cover_descent_glue_direct_source_over
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :=
  { s : localized_cover_descent_glue_direct_family_over (J := J) (U := U) 𝒰 D I T //
      localized_cover_descent_glue_direct_compatible
        (J := J) (U := U) 𝒰 D I T s }

/-- Helper for Lemma 7.26.4: transporting each direct source-side component section through the
direct-to-iterated comparison upgrades pointwise to an equivalence of direct families with the
standard component-side family. This is the family-level core of the missing restriction
comparison. -/
noncomputable def localized_cover_descent_glue_direct_family_equiv
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y) :
    localized_cover_descent_glue_direct_family_over (J := J) (U := U) 𝒰 D I T ≃
      (∀ K : ((𝒰.pullback I.f).pullback T.hom).Arrow,
        ((((J.overMapPullback (Type w) T.hom).obj (D.obj I)).1).obj
          (Opposite.op (Over.mk K.f)))) where
  toFun s K :=
    localized_cover_descent_pullbackDatum_over_direct_section_equiv_component
      (J := J) (U := U) 𝒰 D I T K (s K)
  invFun t K :=
    (localized_cover_descent_pullbackDatum_over_direct_section_equiv_component
      (J := J) (U := U) 𝒰 D I T K).symm (t K)
  left_inv s := by
    -- Each direct source component is inverted by the corresponding section-level equivalence.
    funext K
    exact
      (localized_cover_descent_pullbackDatum_over_direct_section_equiv_component
        (J := J) (U := U) 𝒰 D I T K).left_inv (s K)
  right_inv t := by
    -- The same pointwise inverse shows that the transported direct family is unchanged.
    funext K
    exact
      (localized_cover_descent_pullbackDatum_over_direct_section_equiv_component
        (J := J) (U := U) 𝒰 D I T K).right_inv (t K)

/-- Helper for Lemma 7.26.4: applying the direct-family equivalence is pointwise just the
direct-source section comparison with the pulled-back component sheaf. -/
theorem localized_cover_descent_glue_direct_family_equiv_apply
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (s : localized_cover_descent_glue_direct_family_over (J := J) (U := U) 𝒰 D I T)
    (K : ((𝒰.pullback I.f).pullback T.hom).Arrow) :
    localized_cover_descent_glue_direct_family_equiv (J := J) (U := U) 𝒰 D I T s K =
      localized_cover_descent_pullbackDatum_over_direct_section_equiv_component
        (J := J) (U := U) 𝒰 D I T K (s K) := by
  -- The equivalence was defined by applying this section comparison at each cover member.
  rfl

/-- Helper for Lemma 7.26.4: the inverse direct-family equivalence is pointwise the inverse
direct-source section comparison with the pulled-back component sheaf. -/
theorem localized_cover_descent_glue_direct_family_equiv_symm_apply
    (𝒰 : J.Cover U)
    (D : localized_cover_descent_category (J := J) (U := U) 𝒰)
    (I : 𝒰.Arrow)
    (T : Over I.Y)
    (t :
      ∀ K : ((𝒰.pullback I.f).pullback T.hom).Arrow,
        ((((J.overMapPullback (Type w) T.hom).obj (D.obj I)).1).obj
          (Opposite.op (Over.mk K.f))))
    (K : ((𝒰.pullback I.f).pullback T.hom).Arrow) :
    (localized_cover_descent_glue_direct_family_equiv (J := J) (U := U) 𝒰 D I T).symm t K =
      (localized_cover_descent_pullbackDatum_over_direct_section_equiv_component
        (J := J) (U := U) 𝒰 D I T K).symm (t K) := by
  -- The inverse equivalence was defined by applying the inverse section comparison pointwise.
  rfl

end

end GrothendieckTopology
end CategoryTheory
