module

public import stacks_project.Chap07.Lemma_7_17_10.LocalSheaf

@[expose] public section

set_option linter.unreachableTactic false
set_option linter.unusedTactic false
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false
set_option linter.unnecessarySimpa false
set_option linter.unusedSimpArgs false
set_option linter.deprecated false

open CategoryTheory Limits Opposite
open CategoryTheory.GrothendieckTopology

universe u v

namespace CategoryTheory

variable {C : Type u} [Category.{v} C] {K : Precoverage C}
variable [K.HasPullbacks] [K.IsStableUnderBaseChange]
variable [HasWeakSheafify K.toCoverage.toGrothendieck (Type (max u v))]

local notation "J" => K.toCoverage.toGrothendieck

section

variable (β : Ordinal.{max u v}) (F : Set.Iio β ⥤ Sheaf K.toCoverage.toGrothendieck (Type (max u v)))
variable (hcover : ∀ (U : C) (R : Presieve U),
  R ∈ K U → Cardinal.lift (Cardinal.mk R.uncurry) < β.cof)

include F

include hcover

/-- Helper for Lemma 7.17.10: the underlying presheaf colimit is already a sheaf for the
Grothendieck topology generated by `K`. -/
lemma presheafColimit_isSheaf_of_coveringPresieveCardinal_lt_cof :
    Presieve.IsSheaf J (colimit (F ⋙ sheafToPresheaf J (Type (max u v)))) := by
  -- Promote the one-cover proof to all sieves in `J = J`.
  rw [Presieve.isSheaf_coverage]
  intro U R hR
  exact presheafColimit_isSheafFor_of_coveringPresieveCardinal_lt_cof β F hcover hR

/-- Helper for Lemma 7.17.10: the underlying presheaf colimit is separated under the small-cover
cofinality hypothesis. -/
lemma presheafColimit_isSeparated_of_coveringPresieveCardinal_lt_cof :
    Presieve.IsSeparated J (colimit (F ⋙ sheafToPresheaf J (Type (max u v)))) := by
  -- Sheafness gives separatedness without reopening the local compatibility argument.
  exact
    (presheafColimit_isSheaf_of_coveringPresieveCardinal_lt_cof β F hcover).isSeparated

/-- Helper for Lemma 7.17.10: once the presheaf colimit is known to be a sheaf, the canonical
comparison on sections is an isomorphism. -/
lemma comparison_isIso_of_coveringPresieveCardinal_lt_cof
    (U : C) :
    IsIso (colimit.post F ((sheafSections J (Type (max u v))).obj (op U))) := by
  let P := colimit (F ⋙ sheafToPresheaf J (Type (max u v)))
  have hP : Presieve.IsSheaf J P :=
    presheafColimit_isSheaf_of_coveringPresieveCardinal_lt_cof β F hcover
  let e0 :
      @colimit _ _ _ _ F inferInstance ≅
        ((presheafToSheaf J (Type (max u v))).obj P) :=
    colimit.isoColimitCocone
      ⟨Sheaf.sheafifyCocone
          (colimit.cocone (F ⋙ sheafToPresheaf J (Type (max u v)))),
        Sheaf.isColimitSheafifyCocone _ (colimit.isColimit _)⟩
  -- Rewrite the comparison as a composite of three isomorphisms.
  rw [colimit_post_eq_toSheafify_comparison_app β F U]
  have hPost :
      IsIso
        (colimit.post (F ⋙ sheafToPresheaf J (Type (max u v)))
          ((evaluation Cᵒᵖ (Type (max u v))).obj (op U))) := by
    infer_instance
  have hToSheafifyApp : IsIso ((CategoryTheory.toSheafify J P).app (op U)) := by
    have hToSheafify : IsIso (CategoryTheory.toSheafify J P) := by
      exact CategoryTheory.isIso_toSheafify J ((isSheaf_iff_isSheaf_of_type J P).2 hP)
    exact (NatTrans.isIso_iff_isIso_app _).1 hToSheafify (op U)
  have hE0App : IsIso (e0.inv.1.app (op U)) := by
    have hMapIso : IsIso ((sheafToPresheaf J (Type (max u v))).map e0.inv) := by
      infer_instance
    change IsIso
      (((sheafToPresheaf J (Type (max u v))).map e0.inv).app (op U))
    exact (NatTrans.isIso_iff_isIso_app _).1 hMapIso (op U)
  change IsIso
    (colimit.post (F ⋙ sheafToPresheaf J (Type (max u v)))
        ((evaluation Cᵒᵖ (Type (max u v))).obj (op U)) ≫
      (CategoryTheory.toSheafify J P).app (op U) ≫
        e0.inv.1.app (op U))
  exact IsIso.comp_isIso' hPost (IsIso.comp_isIso' hToSheafifyApp hE0App)


end

end CategoryTheory
