module

public import ReasLib.Optimization.LineSearch.Wolfe

public section

/-!
# Linear transport of Wolfe conditions

Wolfe conditions only inspect a function on the affine line generated by a step.  Consequently
they transport along an arbitrary linear map whenever the two objectives agree on its range.
-/

noncomputable section

universe u v

namespace LineSearch.Wolfe

/-- Restricting an objective along a linear map preserves its endpoint line derivative. -/
theorem lineDeriv_map {E : Type u} {F : Type v} [AddCommGroup E] [Module ℝ E]
    [AddCommGroup F] [Module ℝ F] {f : E → ℝ} {g : F → ℝ}
    (L : E →ₗ[ℝ] F) (restricts : ∀ z, g (L z) = f z) (x s : E) :
    lineDeriv ℝ g (L x) (L s) = lineDeriv ℝ f x s := by
  have line_eq : (fun t : ℝ ↦ g (L x + t • L s)) =
      (fun t : ℝ ↦ f (x + t • s)) := by
    funext t
    rw [← restricts (x + t • s), map_add, map_smul]
  change deriv (fun t : ℝ ↦ g (L x + t • L s)) 0 =
    deriv (fun t : ℝ ↦ f (x + t • s)) 0
  rw [line_eq]

/-- Line differentiability is preserved when two objectives agree after a linear map. -/
theorem lineDifferentiable_map_iff {E : Type u} {F : Type v} [AddCommGroup E] [Module ℝ E]
    [AddCommGroup F] [Module ℝ F] {f : E → ℝ} {g : F → ℝ}
    (L : E →ₗ[ℝ] F) (restricts : ∀ z, g (L z) = f z) (x s : E) :
    LineDifferentiableAt ℝ g (L x) (L s) ↔ LineDifferentiableAt ℝ f x s := by
  have line_eq : (fun t : ℝ ↦ g (L x + t • L s)) =
      (fun t : ℝ ↦ f (x + t • s)) := by
    funext t
    rw [← restricts (x + t • s), map_add, map_smul]
  change DifferentiableAt ℝ (fun t : ℝ ↦ g (L x + t • L s)) 0 ↔
    DifferentiableAt ℝ (fun t : ℝ ↦ f (x + t • s)) 0
  rw [line_eq]

/-- Weak Wolfe satisfaction is invariant under a linear map on whose range the objectives
agree. -/
theorem IsWeak.map_iff {E : Type u} {F : Type v} [AddCommGroup E] [Module ℝ E]
    [AddCommGroup F] [Module ℝ F] {p : Coefficients} {f : E → ℝ}
    {g : F → ℝ} {x s : E} (L : E →ₗ[ℝ] F) (restricts : ∀ z, g (L z) = f z) :
    IsWeak p g (L x) (L s) ↔ IsWeak p f x s := by
  have nextPoint : L x + L s = L (x + s) := by
    rw [map_add]
  have nextLine : lineDeriv ℝ g (L x + L s) (L s) =
      lineDeriv ℝ f (x + s) s := by
    rw [nextPoint]
    exact lineDeriv_map L restricts (x + s) s
  have startLine : lineDeriv ℝ g (L x) (L s) = lineDeriv ℝ f x s :=
    lineDeriv_map L restricts x s
  constructor
  · intro h
    have nextDifferentiable : LineDifferentiableAt ℝ g (L (x + s)) (L s) := by
      rw [← nextPoint]
      exact h.lineDifferentiableAtNext
    constructor
    · exact (lineDifferentiable_map_iff L restricts x s).mp h.lineDifferentiableAt
    · exact (lineDifferentiable_map_iff L restricts (x + s) s).mp nextDifferentiable
    · have armijo := h.armijo
      rw [startLine, nextPoint, restricts x, restricts (x + s)] at armijo
      exact armijo
    · have curvature := h.weakCurvature
      rw [startLine, nextLine] at curvature
      exact curvature
  · intro h
    have nextDifferentiable := (lineDifferentiable_map_iff L restricts (x + s) s).mpr
      h.lineDifferentiableAtNext
    constructor
    · exact (lineDifferentiable_map_iff L restricts x s).mpr h.lineDifferentiableAt
    · rw [nextPoint]
      exact nextDifferentiable
    · have armijo := h.armijo
      rw [← startLine, ← restricts x, ← restricts (x + s), ← nextPoint] at armijo
      exact armijo
    · have curvature := h.weakCurvature
      rw [← startLine, ← nextLine] at curvature
      exact curvature

/-- Strong Wolfe satisfaction is invariant under a linear map on whose range the objectives
agree. -/
theorem IsStrong.map_iff {E : Type u} {F : Type v} [AddCommGroup E] [Module ℝ E]
    [AddCommGroup F] [Module ℝ F] {p : Coefficients} {f : E → ℝ}
    {g : F → ℝ} {x s : E} (L : E →ₗ[ℝ] F) (restricts : ∀ z, g (L z) = f z) :
    IsStrong p g (L x) (L s) ↔ IsStrong p f x s := by
  have nextPoint : L x + L s = L (x + s) := by
    rw [map_add]
  have nextLine : lineDeriv ℝ g (L x + L s) (L s) =
      lineDeriv ℝ f (x + s) s := by
    rw [nextPoint]
    exact lineDeriv_map L restricts (x + s) s
  have startLine : lineDeriv ℝ g (L x) (L s) = lineDeriv ℝ f x s :=
    lineDeriv_map L restricts x s
  constructor
  · intro h
    have nextDifferentiable : LineDifferentiableAt ℝ g (L (x + s)) (L s) := by
      rw [← nextPoint]
      exact h.lineDifferentiableAtNext
    constructor
    · exact (lineDifferentiable_map_iff L restricts x s).mp h.lineDifferentiableAt
    · exact (lineDifferentiable_map_iff L restricts (x + s) s).mp nextDifferentiable
    · have armijo := h.armijo
      rw [startLine, nextPoint, restricts x, restricts (x + s)] at armijo
      exact armijo
    · have curvature := h.strongCurvature
      rw [startLine, nextLine] at curvature
      exact curvature
  · intro h
    have nextDifferentiable := (lineDifferentiable_map_iff L restricts (x + s) s).mpr
      h.lineDifferentiableAtNext
    constructor
    · exact (lineDifferentiable_map_iff L restricts x s).mpr h.lineDifferentiableAt
    · rw [nextPoint]
      exact nextDifferentiable
    · have armijo := h.armijo
      rw [← startLine, ← restricts x, ← restricts (x + s), ← nextPoint] at armijo
      exact armijo
    · have curvature := h.strongCurvature
      rw [← startLine, ← nextLine] at curvature
      exact curvature

/-- Pulling an objective back by a linear map preserves weak Wolfe satisfaction. -/
theorem IsWeak.comp_iff {E : Type u} {F : Type v} [AddCommGroup E] [Module ℝ E]
    [AddCommGroup F] [Module ℝ F] {p : Coefficients} {f : F → ℝ}
    {x s : E} (L : E →ₗ[ℝ] F) :
    IsWeak p (f ∘ L) x s ↔ IsWeak p f (L x) (L s) := by
  have restricts : ∀ z, f (L z) = (f ∘ L) z := by
    intro z
    rfl
  exact (IsWeak.map_iff L restricts).symm

/-- Pulling an objective back by a linear map preserves strong Wolfe satisfaction. -/
theorem IsStrong.comp_iff {E : Type u} {F : Type v} [AddCommGroup E] [Module ℝ E]
    [AddCommGroup F] [Module ℝ F] {p : Coefficients} {f : F → ℝ}
    {x s : E} (L : E →ₗ[ℝ] F) :
    IsStrong p (f ∘ L) x s ↔ IsStrong p f (L x) (L s) := by
  have restricts : ∀ z, f (L z) = (f ∘ L) z := by
    intro z
    rfl
  exact (IsStrong.map_iff L restricts).symm

end LineSearch.Wolfe
