module

public import Mathlib.Topology.KrullDimension
public import Mathlib.Topology.Sober
import Mathlib.AlgebraicTopology.SimplexCategory.Basic

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

/-
Domain-style sampling for Lemma 5.19.9:
- primary domain: topological Krull dimension under specialization/generalization-lifting maps
- owner declarations inspected: `topologicalKrullDim`, `SpecializingMap`, `GeneralizingMap`, and
  the quasi-sober generic-point API `IsIrreducible.genericPoint`
- best owner abstraction: the canonical dimension owner `topologicalKrullDim` together with the
  map-lifting predicates `SpecializingMap f` and `GeneralizingMap f`; the only target-space
  irreducible-closed data needed in the proof is supplied canonically by `[QuasiSober Y]`
- primitive data: a surjective map carrying one of the two canonical lifting predicates, with
  quasi-sobriety on the target to choose generic points of irreducible closed subsets
- derived API: the disjunctive source-facing dimension inequality

Layer triage:
- `source-facing`: the dimension inequality for a surjective map along which specializations or
  generalizations lift
- `core/canonical`: `topologicalKrullDim`, `SpecializingMap`, `GeneralizingMap`, `QuasiSober`
- `bridge/view`: none

The file already uses the correct owner predicates, so the refinement here is only to keep the
public statement on that canonical layer, with only the quasi-sober generic-point hypothesis that
the proof actually uses, and keep the two directional cases as internal branches of one proof
rather than as separate local declarations.
-/

section

open Set Function Order TopologicalSpace Topology TopologicalSpace.IrreducibleCloseds

variable {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
variable [QuasiSober Y] {f : X → Y}

/-- Helper for Lemma 5.19.9: the irreducible closed subset generated by a point. -/
def pointClosure (x : X) : IrreducibleCloseds X :=
  ⟨closure ({x} : Set X), isIrreducible_singleton.closure, isClosed_closure⟩

/-- Helper for Lemma 5.19.9: inclusion of irreducible closed subsets makes generic points
specialize in the opposite direction. -/
lemma genericPoint_specializes_of_le {S T : IrreducibleCloseds Y} (hST : S ≤ T) :
    T.isIrreducible.genericPoint ⤳ S.isIrreducible.genericPoint := by
  -- The generic point of the larger closed set specializes to every point it contains.
  let hTgp := T.isIrreducible.isGenericPoint_genericPoint T.isClosed
  let hSgp := S.isIrreducible.isGenericPoint_genericPoint S.isClosed
  exact hTgp.specializes (hST hSgp.mem)

omit [TopologicalSpace X] [TopologicalSpace Y] [QuasiSober Y] in
/-- Helper for Lemma 5.19.9: a surjective fibration lifts a finite relation chain pointwise. -/
lemma exists_lift_of_fibration {rX : X → X → Prop} {rY : Y → Y → Prop}
    (hFib : Relation.Fibration rX rY f) (hSurj : Function.Surjective f) :
    ∀ {n : ℕ} (y : Fin (n + 1) → Y),
      (∀ i : Fin n, rY (y i.succ) (y (Fin.castSucc i))) →
      ∃ x : Fin (n + 1) → X,
        (∀ i, f (x i) = y i) ∧
        ∀ i : Fin n, rX (x i.succ) (x (Fin.castSucc i))
  | 0, y, _ => by
      -- A chain of length `0` is a single point, so surjectivity gives its lift immediately.
      rcases hSurj (y 0) with ⟨x0, hx0⟩
      refine ⟨fun _ ↦ x0, ?_, ?_⟩
      · intro i
        fin_cases i
        simpa using hx0
      · intro i
        exact Fin.elim0 i
  | n + 1, y, hy => by
      -- Lift the initial segment first, then use the fibration property for the final step.
      let yInit : Fin (n + 1) → Y := y ∘ Fin.castSucc
      have hyInit : ∀ i : Fin n, rY (yInit i.succ) (yInit (Fin.castSucc i)) := by
        intro i
        simpa [yInit, Function.comp_apply, Fin.castSucc_succ] using hy (Fin.castSucc i)
      rcases exists_lift_of_fibration hFib hSurj yInit hyInit with ⟨xInit, hxInit, hxStep⟩
      have hLast : rY (y (Fin.last (n + 1))) (f (xInit (Fin.last n))) := by
        rw [hxInit (Fin.last n)]
        simpa using hy (Fin.last n)
      rcases hFib hLast with ⟨xLast, hxLast, hfxLast⟩
      refine ⟨(Fin.snoc xInit xLast : Fin (n + 2) → X), ?_, ?_⟩
      · intro i
        refine Fin.lastCases ?_ ?_ i
        · simpa using hfxLast
        · intro j
          simpa [Fin.snoc_castSucc] using hxInit j
      · intro i
        refine Fin.lastCases ?_ ?_ i
        · simpa [Fin.snoc_last] using hxLast
        · intro j
          have hsucc : (Fin.snoc xInit xLast : Fin (n + 2) → X) j.castSucc.succ = xInit j.succ := by
            rw [show j.castSucc.succ = (j.succ).castSucc from (Fin.castSucc_succ j).symm,
              Fin.snoc_castSucc]
          rw [hsucc]
          simpa [Fin.snoc_castSucc] using hxStep j

/-- Helper for Lemma 5.19.9: lifting compatible generic points turns a strict target inclusion into
an equally strict inclusion of point-closures upstairs. -/
lemma pointClosure_lt_of_lifted_generic_points (hf : Continuous f)
    {S T : IrreducibleCloseds Y} (hST : S < T) {xS xT : X}
    (hx : xT ⤳ xS)
    (hfxS : f xS = S.isIrreducible.genericPoint)
    (hfxT : f xT = T.isIrreducible.genericPoint) :
    pointClosure xS < pointClosure xT := by
  refine lt_of_le_of_ne ?_ ?_
  · -- A specialization upstairs gives the expected inclusion of closures.
    simpa [pointClosure] using (specializes_iff_closure_subset.mp hx)
  · intro hEq
    -- Route correction: equality of the lifted closures would force a reverse specialization,
    -- whose image contradicts the strict target inclusion.
    have hEqSet : (pointClosure xS : Set X) = pointClosure xT :=
      congrArg (fun Z : IrreducibleCloseds X ↦ (Z : Set X)) hEq
    have hrev : xS ⤳ xT := by
      apply specializes_iff_closure_subset.mpr
      simpa [pointClosure] using hEqSet.symm.subset
    have hImageRev : S.isIrreducible.genericPoint ⤳ T.isIrreducible.genericPoint := by
      rw [← hfxS, ← hfxT]
      exact hf.specialization_monotone hrev
    have hTS : T ≤ S := by
      simpa [T.isIrreducible.closure_genericPoint T.isClosed,
        S.isIrreducible.closure_genericPoint S.isClosed] using
        (specializes_iff_closure_subset.mp hImageRev)
    exact hST.ne (le_antisymm hST.le hTS)

/-- Lemma 5.19.9: if `f : X → Y` is surjective, `Y` is sober, and either specializations or
generalizations lift along `f`, then the topological Krull dimension of `X` is at least that of
`Y`. For this dimension comparison, the source sober hypothesis is used only through the canonical
generic-point owner `[QuasiSober Y]`. -/
theorem topologicalKrullDim_le_of_surjective_specializing_or_generalizing
    (hf : Continuous f) (hSurj : Function.Surjective f)
    (hLift : SpecializingMap f ∨ GeneralizingMap f) :
    topologicalKrullDim Y ≤ topologicalKrullDim X := by
  classical
  -- Route correction: work chainwise on generic points and then pass to point-closures in `X`.
  rw [topologicalKrullDim, Order.krullDim]
  refine iSup_le ?_
  intro p
  let y : Fin (p.length + 1) → Y := fun i ↦ (p i).isIrreducible.genericPoint
  have hy : ∀ i : Fin p.length, y i.succ ⤳ y (Fin.castSucc i) := by
    -- Successive terms in the target chain give successive specializations of generic points.
    intro i
    exact genericPoint_specializes_of_le (p.step i).le
  rcases hLift with hSpec | hGen
  · -- Reverse the target chain so that the specializing-map fibration can be used in forward order.
    let yRev : Fin (p.length + 1) → Y := y ∘ Fin.rev
    have hyRev : ∀ i : Fin p.length, (yRev (Fin.castSucc i)) ⤳ yRev i.succ := by
      intro i
      simpa [yRev, Function.comp_apply, Fin.rev_castSucc, Fin.rev_succ] using hy i.rev
    rcases exists_lift_of_fibration (f := f) (rX := flip (· ⤳ ·)) (rY := flip (· ⤳ ·))
        hSpec hSurj yRev hyRev with ⟨xRev, hxRev, hxRevStep⟩
    let x : Fin (p.length + 1) → X := xRev ∘ Fin.rev
    have hx : ∀ i, f (x i) = y i := by
      -- Undo the reversal to recover lifts of the original generic points.
      intro i
      simpa [x, yRev, Function.comp_apply, Fin.rev_rev] using hxRev i.rev
    have hxStep : ∀ i : Fin p.length, x i.succ ⤳ x (Fin.castSucc i) := by
      -- The reversed lifted chain turns back into the desired specialization chain upstairs.
      intro i
      simpa [x, Function.comp_apply, Fin.rev_succ, Fin.rev_castSucc] using hxRevStep i.rev
    let q : LTSeries (IrreducibleCloseds X) :=
      LTSeries.mk p.length (fun i ↦ pointClosure (x i)) <|
        (Fin.strictMono_iff_lt_succ (f := fun i ↦ pointClosure (x i))).2 fun i ↦ by
          exact pointClosure_lt_of_lifted_generic_points hf (p.step i) (hxStep i)
            (hx (Fin.castSucc i)) (hx i.succ)
    -- The lifted strict chain in `IrreducibleCloseds X` has the same length as the original one.
    simpa [topologicalKrullDim, Order.krullDim] using (Order.LTSeries.length_le_krullDim q)
  · -- A generalizing map lifts the generic-point chain directly in the given order.
    rcases exists_lift_of_fibration (f := f) (rX := (· ⤳ ·)) (rY := (· ⤳ ·)) hGen hSurj y hy with
      ⟨x, hx, hxStep⟩
    let q : LTSeries (IrreducibleCloseds X) :=
      LTSeries.mk p.length (fun i ↦ pointClosure (x i)) <|
        (Fin.strictMono_iff_lt_succ (f := fun i ↦ pointClosure (x i))).2 fun i ↦ by
          exact pointClosure_lt_of_lifted_generic_points hf (p.step i) (hxStep i)
            (hx (Fin.castSucc i)) (hx i.succ)
    -- The same closure argument turns the lifted point chain into a strict chain upstairs.
    simpa [topologicalKrullDim, Order.krullDim] using (Order.LTSeries.length_le_krullDim q)

end
