module
import Mathlib.Tactic.Recall
public import Mathlib.Topology.Order

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

open TopologicalSpace

universe u

/-
Domain-style sampling for subbases:
- owner abstraction: `TopologicalSpace.generateFrom`
- same-domain declarations inspected:
  `TopologicalSpace.generateFrom`,
  `FiniteInter.finiteInterClosure`,
  `TopologicalSpace.isTopologicalBasis_of_subbasis_of_finiteInter`,
  `TopologicalSpace.eq_generateFrom_iff_isTopologicalBasis_finiteInterClosure`

Layer triage:
- `source-facing`: a family is a subbasis for a topology
- `core/canonical`: `TopologicalSpace.generateFrom`
- `bridge/view`: the finite-intersection basis criterion from
  `eq_generateFrom_iff_isTopologicalBasis_finiteInterClosure`

Primitive data is only the family `B`. The basis on `finiteInterClosure B` is derived API from the
canonical owner `generateFrom B`. The finite-intersection basis criterion belongs to the companion
bridge theorem `eq_generateFrom_iff_isTopologicalBasis_finiteInterClosure`, while this lemma should
keep the source-facing subbasis semantics centered in the main statement.
-/

/- Companion recall: `generateFrom` is the canonical owner of the topology generated by a
subbasis. -/
recall generateFrom

/-- Lemma 5.5.5: for any family `B` of subsets of `X`, there is a unique topology on `X`, namely
`generateFrom B`, for which `B` is a subbasis. The equivalent finite-intersection-basis criterion
is the companion bridge theorem
`TopologicalSpace.eq_generateFrom_iff_isTopologicalBasis_finiteInterClosure`. -/
theorem existsUnique_topology_with_subbasis {X : Type u} (B : Set (Set X)) :
    ∃! t : TopologicalSpace X, t = generateFrom B := by
  -- Use the canonical generated topology as the witness from the subbasis data `B`.
  refine ⟨generateFrom B, rfl, ?_⟩
  -- Any other topology satisfying the same characterization is equal to this witness.
  intro t ht
  exact ht
