module

public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Topology.Constructible
public import stacks_project.Chap05.Remark_5_28_5
import Mathlib.Data.Finite.Sum

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

open Set Topology
open IsClosedInitialFamily

universe u v

section

variable {X : Type u} [TopologicalSpace X]
variable {ι : Type v} [Finite ι] (T : ι → Set X)

/- Domain-style sampling for finite constructible covers and frontier stratifications:
- inspected declarations: `IsClosedInitialFamily`,
  `IsClosedInitialFamily.frontier`,
  `IsClosedInitialFamily.frontierStrata`, and
  `IsClosedInitialFamily.frontier_isStratification`
- best owner abstraction: `IsClosedInitialFamily`

Layer triage:
- `source-facing`: the indexed stratification statement of Lemma 5.28.7
- `core/canonical`: a finite constructible closed initial family subordinate to the cover
- `bridge/view`: `frontierStrata` together with `frontier_isStratification`

Primitive data are the finite constructible members of the closed initial family and their
subordination to the cover. The frontier strata, their constructibility, and the textbook
union-of-strata formulas are derived from that owner-level family by finite Boolean operations and
the canonical frontier-stratification bridge.
-/

/-- Helper for Lemma 5.28.7: a constructible set is a finite union of pieces `U ∩ Vᶜ` with
`U` and `V` open retrocompact. -/
lemma constructible_exists_eq_iUnion_open_inter_compl {E : Set X} (hE : IsConstructible E) :
    ∃ n : ℕ, ∃ U V : Fin n → Set X,
      (∀ a, IsOpen (U a) ∧ IsRetrocompact (U a) ∧ IsOpen (V a) ∧ IsRetrocompact (V a)) ∧
      E = ⋃ a, U a ∩ (V a)ᶜ := by
  classical
  have hsdiff :
      ∃ ι : Type u, ∃ _ : Finite ι, ∃ Z : ι → Set X,
        (∀ i, ∃ U V : Set X,
          IsOpen U ∧ IsRetrocompact U ∧ IsOpen V ∧ IsRetrocompact V ∧ Z i = U \ V) ∧
        E = ⋃ i, Z i := by
    -- Work in the Boolean closure directly so the retrocompact generators stay explicit.
    change E ∈ BooleanSubalgebra.closure {U : Set X | IsOpen U ∧ IsRetrocompact U} at hE
    refine BooleanSubalgebra.closure_sdiff_sup_induction
      (⟨
        fun U hU V hV ↦ ⟨hU.1.union hV.1, hU.2.union hV.2⟩,
        fun U hU V hV ↦ ⟨hU.1.inter hV.1, hU.2.inter_isOpen hV.2 hV.1⟩
      ⟩ : IsSublattice {U : Set X | IsOpen U ∧ IsRetrocompact U})
      (by simp) (by simp) ?_ ?_ E hE
    · intro U hU V hV
      -- A single generator difference already has the required form.
      refine ⟨PUnit, inferInstance, fun _ ↦ U \ V, ?_, ?_⟩
      · intro _
        exact ⟨U, V, hU.1, hU.2, hV.1, hV.2, rfl⟩
      · ext x
        simp
    · intro s hs t ht hs_ind ht_ind
      -- Finite unions are encoded by the disjoint sum of finite index sets.
      rcases hs_ind with ⟨ιs, hιs, Zs, hZs, rfl⟩
      rcases ht_ind with ⟨ιt, hιt, Zt, hZt, rfl⟩
      let _ : Finite ιs := hιs
      let _ : Finite ιt := hιt
      refine ⟨ιs ⊕ ιt, inferInstance, Sum.elim Zs Zt, ?_, ?_⟩
      · intro i
        cases i with
        | inl i => simpa using hZs i
        | inr i => simpa using hZt i
      · simp [iUnion_sum]
  rcases hsdiff with ⟨ι, hι, Z, hZ, hcover⟩
  let _ : Finite ι := hι
  let _ : Fintype ι := Fintype.ofFinite ι
  choose U V hU_open hU_retro hV_open hV_retro hpiece using hZ
  let e : Fin (Fintype.card ι) ≃ ι := (Fintype.equivFin ι).symm
  refine ⟨Fintype.card ι, fun a ↦ U (e a), fun a ↦ V (e a), ?_, ?_⟩
  · -- Reindex the decomposition along `Fin`.
    intro a
    exact ⟨hU_open (e a), hU_retro (e a), hV_open (e a), hV_retro (e a)⟩
  · -- Convert the arbitrary finite union into a `Fin`-indexed union of `U ∩ Vᶜ` pieces.
    calc
      E = ⋃ i, Z i := hcover
      _ = ⋃ i, U i ∩ (V i)ᶜ := by
        congr with i
        simpa [hpiece i, Set.diff_eq]
      _ = ⋃ a : Fin (Fintype.card ι), U (e a) ∩ (V (e a))ᶜ := by
        ext x
        constructor
        · intro hx
          rcases Set.mem_iUnion.1 hx with ⟨i, hxi⟩
          exact Set.mem_iUnion.2 ⟨e.symm i, by simpa using hxi⟩
        · intro hx
          rcases Set.mem_iUnion.1 hx with ⟨a, hxa⟩
          exact Set.mem_iUnion.2 ⟨e a, by simpa using hxa⟩

/-- Helper for Lemma 5.28.7: the intersection family generated by `C`. -/
abbrev generatedIntersectionFamily {G : Type*} (C : G → Set X) :
    OrderDual (Set G) → Set X :=
  fun A ↦ ⋂ g, ⋂ (_ : g ∈ (show Set G from A)), C g

/-- Helper for Lemma 5.28.7: finite intersections of closed generators form a closed initial
family. -/
lemma generated_intersection_family_isClosedInitialFamily
    {G : Type*} [Finite G] (C : G → Set X) (hCclosed : ∀ g, IsClosed (C g)) :
    IsClosedInitialFamily (generatedIntersectionFamily C) := by
  classical
  refine
    { isClosed := ?_
      iUnion_eq_univ := ?_
      locallyFinite := locallyFinite_of_finite (generatedIntersectionFamily C)
      inter_eq_iUnion := ?_ }
  · intro A
    -- Each member is an intersection of closed generators.
    refine isClosed_biInter ?_
    intro g hg
    exact hCclosed g
  · -- The empty generator set contributes `univ`.
    ext x
    constructor
    · intro hx
      simp
    · intro hx
      refine Set.mem_iUnion.2 ⟨OrderDual.toDual (∅ : Set G), ?_⟩
      simp only [generatedIntersectionFamily, Set.mem_iInter]
      intro g hg
      cases hg
  · intro A B
    let A0 : Set G := A
    let B0 : Set G := B
    -- Reverse inclusion on `OrderDual (Set G)` turns intersections into unions over larger sets.
    ext x
    constructor
    · intro hx
      rcases hx with ⟨hxA, hxB⟩
      refine Set.mem_iUnion.2 ?_
      refine ⟨OrderDual.toDual (A0 ∪ B0), ?_⟩
      refine Set.mem_iUnion.2 ?_
      refine ⟨?_, ?_⟩
      · constructor
        · exact subset_union_left
        · exact subset_union_right
      · have hxA' : ∀ g ∈ A0, x ∈ C g := by
          simpa [generatedIntersectionFamily, A0] using hxA
        have hxB' : ∀ g ∈ B0, x ∈ C g := by
          simpa [generatedIntersectionFamily, B0] using hxB
        simp only [generatedIntersectionFamily, Set.mem_iInter]
        intro g hg
        rcases hg with hg | hg
        · exact hxA' g hg
        · exact hxB' g hg
    · intro hx
      rcases Set.mem_iUnion.1 hx with ⟨K, hxK⟩
      rcases Set.mem_iUnion.1 hxK with ⟨hK, hxK⟩
      rcases hK with ⟨hAK, hBK⟩
      have hxK' : ∀ g ∈ (show Set G from K), x ∈ C g := by
        simpa [generatedIntersectionFamily] using hxK
      constructor
      · simp only [generatedIntersectionFamily, Set.mem_iInter]
        intro g hg
        exact hxK' g (hAK hg)
      · simp only [generatedIntersectionFamily, Set.mem_iInter]
        intro g hg
        exact hxK' g (hBK hg)

/-- Helper for Lemma 5.28.7: a frontier piece in a generated intersection family is either
contained in or disjoint from each basic piece `U ∩ Vᶜ`. -/
lemma frontier_subset_or_disjoint_of_basic_piece
    {G : Type*} (C : G → Set X) {gU gV : G} {U V : Set X} (i : OrderDual (Set G))
    (hCU : C gU = Uᶜ) (hCV : C gV = Vᶜ) :
    IsClosedInitialFamily.frontier (generatedIntersectionFamily C) i ⊆ U ∩ Vᶜ ∨
      Disjoint (IsClosedInitialFamily.frontier (generatedIntersectionFamily C) i) (U ∩ Vᶜ) := by
  classical
  by_cases hdisj :
      Disjoint (IsClosedInitialFamily.frontier (generatedIntersectionFamily C) i) (U ∩ Vᶜ)
  · exact Or.inr hdisj
  · -- A witness in the basic piece forces the `Vᶜ` generator to be present and the `Uᶜ`
    -- generator to be absent; then frontier minimality propagates the same conclusion to every
    -- point of the frontier.
    left
    obtain ⟨x, hxFrontier, hxBasic⟩ := Set.not_disjoint_iff.1 hdisj
    let A0 : Set G := i
    have hxA : x ∈ generatedIntersectionFamily C i := by
      simpa [IsClosedInitialFamily.frontier] using hxFrontier.1
    have hxA' : ∀ g ∈ A0, x ∈ C g := by
      simpa [generatedIntersectionFamily, A0] using hxA
    have hgV_mem : gV ∈ A0 := by
      by_contra hgV_not_mem
      have hxStrict :
          x ∈ generatedIntersectionFamily C (OrderDual.toDual (A0 ∪ ({gV} : Set G))) := by
        simp only [generatedIntersectionFamily, Set.mem_iInter]
        intro g hg
        rcases hg with hg | rfl
        · exact hxA' g hg
        · simpa [hCV] using hxBasic.2
      have hlt : OrderDual.toDual (A0 ∪ ({gV} : Set G)) ∈ Set.Iio i := by
        change A0 ⊂ A0 ∪ ({gV} : Set G)
        simpa [Set.union_comm, Set.union_left_comm, Set.union_assoc] using
          Set.ssubset_insert hgV_not_mem
      exact hxFrontier.2 <| Set.mem_iUnion.2
        ⟨OrderDual.toDual (A0 ∪ ({gV} : Set G)), Set.mem_iUnion.2 ⟨hlt, hxStrict⟩⟩
    have hgU_not_mem : gU ∉ A0 := by
      intro hgU_mem
      have hxUcompl : x ∈ C gU := hxA' gU hgU_mem
      have hxU_notin : x ∉ U := by
        simpa [hCU] using hxUcompl
      exact hxU_notin hxBasic.1
    intro y hyFrontier
    have hyA : y ∈ generatedIntersectionFamily C i := by
      simpa [IsClosedInitialFamily.frontier] using hyFrontier.1
    have hyA' : ∀ g ∈ A0, y ∈ C g := by
      simpa [generatedIntersectionFamily, A0] using hyA
    have hyV : y ∈ Vᶜ := by
      have hyVcompl : y ∈ C gV := hyA' gV hgV_mem
      simpa [hCV] using hyVcompl
    have hyU : y ∈ U := by
      by_contra hyU_not
      have hyStrict :
          y ∈ generatedIntersectionFamily C (OrderDual.toDual (A0 ∪ ({gU} : Set G))) := by
        simp only [generatedIntersectionFamily, Set.mem_iInter]
        intro g hg
        rcases hg with hg | rfl
        · exact hyA' g hg
        · simpa [hCU] using hyU_not
      have hlt : OrderDual.toDual (A0 ∪ ({gU} : Set G)) ∈ Set.Iio i := by
        change A0 ⊂ A0 ∪ ({gU} : Set G)
        simpa [Set.union_comm, Set.union_left_comm, Set.union_assoc] using
          Set.ssubset_insert hgU_not_mem
      exact hyFrontier.2 <| Set.mem_iUnion.2
        ⟨OrderDual.toDual (A0 ∪ ({gU} : Set G)), Set.mem_iUnion.2 ⟨hlt, hyStrict⟩⟩
    exact ⟨hyU, hyV⟩

/-- Helper for Lemma 5.28.7: if every frontier piece is homogeneous for the basic pieces in a
finite decomposition of `T k`, then it is homogeneous for `T k` itself. -/
lemma frontier_subset_or_disjoint_of_cover_member
    {I : Type*} [PartialOrder I] {Z : I → Set X} {κ : Type*} (T : κ → Set X)
    {n : κ → ℕ} (basic : (k : κ) → Fin (n k) → Set X)
    (hTbasic : ∀ k, T k = ⋃ a, basic k a)
    (hbasic :
      ∀ i k a, IsClosedInitialFamily.frontier Z i ⊆ basic k a ∨
        Disjoint (IsClosedInitialFamily.frontier Z i) (basic k a)) :
    ∀ i k, IsClosedInitialFamily.frontier Z i ⊆ T k ∨
      Disjoint (IsClosedInitialFamily.frontier Z i) (T k) := by
  intro i k
  by_cases hdisj : Disjoint (IsClosedInitialFamily.frontier Z i) (T k)
  · exact Or.inr hdisj
  · -- A witness in `T k` lies in one basic piece, and that piece controls the whole frontier.
    left
    obtain ⟨x, hxFrontier, hxTk⟩ := Set.not_disjoint_iff.1 hdisj
    rw [hTbasic k] at hxTk
    rcases Set.mem_iUnion.1 hxTk with ⟨a, hxa⟩
    rcases hbasic i k a with hsubset | hpieceDisjoint
    · intro y hy
      rw [hTbasic k]
      exact Set.mem_iUnion.2 ⟨a, hsubset hy⟩
    · exact False.elim <| Set.disjoint_left.1 hpieceDisjoint hxFrontier hxa

/-- Helper for Lemma 5.28.7: frontier pieces of a finite constructible closed initial family are
constructible. -/
lemma isConstructible_frontier_of_constructible_closedInitialFamily
    {I : Type u} [Finite I] [PartialOrder I] {Z : I → Set X}
    (hZconstruct : ∀ i, IsConstructible (Z i)) :
    ∀ i, IsConstructible (IsClosedInitialFamily.frontier Z i) := by
  classical
  intro i
  let lower : Set.Iio i → Set X := fun j ↦ Z j.1
  have hlower : ∀ j : Set.Iio i, IsConstructible (lower j) := by
    intro j
    exact hZconstruct j.1
  have hlowerUnion : IsConstructible (⋃ j : Set.Iio i, lower j) :=
    IsConstructible.iUnion hlower
  -- The frontier is a Boolean difference of constructible sets, so it remains constructible.
  simpa [IsClosedInitialFamily.frontier, lower, Set.iUnion_subtype] using
    (hZconstruct i).sdiff hlowerUnion

/-- Helper for Lemma 5.28.7: once each frontier piece is either contained in or disjoint from a
covering set, the covering set is exactly the union of the frontier strata it contains. -/
lemma cover_piece_eq_iUnion_of_frontier_subordinate
    {I : Type u} [Finite I] [PartialOrder I] {Z : I → Set X}
    (hZ : IsClosedInitialFamily Z) {κ : Type*} (T : κ → Set X)
    (hsub : ∀ i k, IsClosedInitialFamily.frontier Z i ⊆ T k ∨
      Disjoint (IsClosedInitialFamily.frontier Z i) (T k)) :
    ∀ k, T k =
      ⋃ i ∈ { j | IsClosedInitialFamily.frontierStrata Z j ⊆ T k },
        IsClosedInitialFamily.frontierStrata Z i := by
  let strata : IsClosedInitialFamily.frontierIndex Z → Set X :=
    IsClosedInitialFamily.frontierStrata Z
  have hstrata : IsStratification strata :=
    IsClosedInitialFamily.frontier_isStratification (Z := Z) hZ
  intro k
  ext x
  constructor
  · intro hx
    have hxCover : x ∈ ⋃ i, strata i := by
      simp [hstrata.cover]
    rcases Set.mem_iUnion.1 hxCover with ⟨i, hxi⟩
    rcases hsub i.1 k with hsubset | hdisjoint
    · refine Set.mem_iUnion.2 ⟨i, Set.mem_iUnion.2 ⟨hsubset, hxi⟩⟩
    · exact False.elim <| Set.disjoint_left.1 hdisjoint hxi hx
  · intro hx
    rcases Set.mem_iUnion.1 hx with ⟨i, hx⟩
    rcases Set.mem_iUnion.1 hx with ⟨hi, hxi⟩
    exact hi hxi

-- Proof sketch: organize the finite Boolean algebra generated by the constructible cover into a
-- finite closed initial family by constructible subsets. The subordinate-to-cover dichotomy only
-- holds for the frontier differences of that family, and the final stratification is obtained by
-- applying the canonical frontier construction.
/-- Owner-level bridge for Lemma 5.28.7: a finite cover of `X` by constructible subsets admits a
finite constructible closed initial family whose frontier pieces are subordinate to the cover. The
stratification of the lemma is the canonical frontier stratification attached to this family. -/
theorem exists_finite_constructible_closedInitialFamily_subordinate_to_cover
    (hT : ∀ k, IsConstructible (T k))
    (hcover : (⋃ k, T k) = (univ : Set X)) :
    ∃ (I : Type u) (_ : Finite I) (_ : PartialOrder I) (Z : I → Set X)
      (hZ : IsClosedInitialFamily Z) (hZconstruct : ∀ i, IsConstructible (Z i)),
      ∀ i k, IsClosedInitialFamily.frontier Z i ⊆ T k ∨
        Disjoint (IsClosedInitialFamily.frontier Z i) (T k) := by
  classical
  let _ : Fintype ι := Fintype.ofFinite ι
  let κ : Type := Fin (Fintype.card ι)
  let e : κ ≃ ι := (Fintype.equivFin ι).symm
  let T₀ : κ → Set X := fun k ↦ T (e k)
  have hT₀ : ∀ k, IsConstructible (T₀ k) := by
    intro k
    simpa [T₀] using hT (e k)
  let _ := hcover
  -- Route correction: the closed members themselves need not be homogeneous for the cover, but
  -- the source minimality argument proves exactly that the frontier pieces are.
  have hnorm :
      ∀ k, ∃ n : ℕ, ∃ U V : Fin n → Set X,
        (∀ a, IsOpen (U a) ∧ IsRetrocompact (U a) ∧ IsOpen (V a) ∧ IsRetrocompact (V a)) ∧
        T₀ k = ⋃ a, U a ∩ (V a)ᶜ := by
    intro k
    exact constructible_exists_eq_iUnion_open_inter_compl (hT₀ k)
  choose n U V hUV hTdecomp using hnorm
  let basic : (k : κ) → Fin (n k) → Set X := fun k a ↦ U k a ∩ (V k a)ᶜ
  let Piece : Type := Σ k : κ, Fin (n k)
  let Generator₀ : Type := Piece × Bool
  let generator₀ : Generator₀ → Set X := fun g ↦
    if g.2 then (V g.1.1 g.1.2)ᶜ else (U g.1.1 g.1.2)ᶜ
  let Generator : Type u := ULift Generator₀
  let generator : Generator → Set X := fun g ↦ generator₀ g.down
  let I : Type u := OrderDual (Set Generator)
  let Z : I → Set X := generatedIntersectionFamily generator
  have hgenerator_closed : ∀ g, IsClosed (generator g) := by
    intro g
    rcases g with ⟨⟨⟨k, a⟩, b⟩⟩
    cases b with
    | false =>
      simpa [generator, generator₀] using (hUV k a).1.isClosed_compl
    | true =>
      simpa [generator, generator₀] using (hUV k a).2.2.1.isClosed_compl
  have hgenerator_constructible : ∀ g, IsConstructible (generator g) := by
    intro g
    rcases g with ⟨⟨⟨k, a⟩, b⟩⟩
    cases b with
    | false =>
      simpa [generator, generator₀]
        using ((hUV k a).2.1.isConstructible (hUV k a).1).compl
    | true =>
      simpa [generator, generator₀]
        using ((hUV k a).2.2.2.isConstructible (hUV k a).2.2.1).compl
  have hZ : IsClosedInitialFamily Z :=
    generated_intersection_family_isClosedInitialFamily generator hgenerator_closed
  have hZconstruct : ∀ i, IsConstructible (Z i) := by
    intro i
    -- Each generated member is a finite intersection of constructible generators.
    have hsub : ∀ g : (show Set Generator from i), IsConstructible (generator g.1) := by
      intro g
      exact hgenerator_constructible g.1
    simpa [Z, generatedIntersectionFamily, Set.iInter_subtype] using IsConstructible.iInter hsub
  have hbasic_frontier :
      ∀ i (a : Piece), IsClosedInitialFamily.frontier Z i ⊆ basic a.1 a.2 ∨
        Disjoint (IsClosedInitialFamily.frontier Z i) (basic a.1 a.2) := by
    intro i a
    -- The generators `Uᶜ` and `Vᶜ` associated to a basic piece control the whole frontier piece.
    simpa [Z, basic, generator, generatedIntersectionFamily] using
      (frontier_subset_or_disjoint_of_basic_piece (C := generator) (i := i)
        (gU := ULift.up (a, false)) (gV := ULift.up (a, true))
        (U := U a.1 a.2) (V := V a.1 a.2) rfl rfl)
  have hsub₀ :
      ∀ i k, IsClosedInitialFamily.frontier Z i ⊆ T₀ k ∨
        Disjoint (IsClosedInitialFamily.frontier Z i) (T₀ k) :=
    frontier_subset_or_disjoint_of_cover_member (Z := Z) T₀ basic hTdecomp
      (fun i k a ↦ hbasic_frontier i ⟨k, a⟩)
  -- The reindexed finite cover keeps the generated family in the ambient universe `u`, and the
  -- final subordinate statement is transported back along the equivalence `e : κ ≃ ι`.
  refine ⟨I, inferInstance, inferInstance, Z, hZ, hZconstruct, ?_⟩
  intro i k
  simpa [T₀, e.apply_symm_apply] using hsub₀ i (e.symm k)

-- Proof sketch: apply the owner-level closed initial family theorem above and then pass to the
-- canonical frontier stratification. Constructibility of the strata and the source-facing
-- union-of-strata formulas are derived from the finite Boolean formulas defining the frontiers and
-- the subordinate-to-cover property of the owner family.
/-- Lemma 5.28.7: a finite cover of `X` by constructible subsets admits a finite stratification by
constructible strata such that each covering set is a union of strata. -/
theorem exists_finite_constructible_stratification_subordinate_to_cover
    (hT : ∀ k, IsConstructible (T k))
    (hcover : (⋃ k, T k) = (univ : Set X)) :
    ∃ (I : Type u) (_ : Finite I) (_ : PartialOrder I) (strata : I → Set X)
      (hstrata : IsStratification strata) (hconstruct : ∀ i, IsConstructible (strata i)),
      ∀ k, T k = ⋃ i ∈ { j | strata j ⊆ T k }, strata i := by
  obtain ⟨I, hI, hIord, Z, hZ, hZconstruct, hsub⟩ :=
    exists_finite_constructible_closedInitialFamily_subordinate_to_cover
      (T := T) hT hcover
  let _ : Finite I := hI
  let _ : PartialOrder I := hIord
  let strata : IsClosedInitialFamily.frontierIndex Z → Set X :=
    IsClosedInitialFamily.frontierStrata Z
  refine ⟨IsClosedInitialFamily.frontierIndex Z, inferInstance, inferInstance, strata, ?_, ?_, ?_⟩
  · -- The frontier pieces of a closed initial family form the canonical indexed stratification.
    exact IsClosedInitialFamily.frontier_isStratification (Z := Z) hZ
  · -- Each frontier stratum is constructible because it is a finite Boolean formula in the
    -- constructible closed family members.
    intro i
    simpa [strata, IsClosedInitialFamily.frontierStrata] using
      isConstructible_frontier_of_constructible_closedInitialFamily
        (hZconstruct := hZconstruct) i.1
  · -- The subordinate frontier dichotomy identifies exactly which strata lie inside each `T k`.
    exact cover_piece_eq_iUnion_of_frontier_subordinate (hZ := hZ) T hsub

end
