module

import Mathlib.Tactic.Recall
public import Mathlib.Topology.Order
import Mathlib.SetTheory.ZFC.PSet
import Mathlib.Topology.Compactness.Compact

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open Set TopologicalSpace

/- Domain-style sampling for Alexander's subbasis theorem:
- owner abstractions: `TopologicalSpace.generateFrom`, `CompactSpace`
- same-domain declarations inspected:
  `TopologicalSpace.generateFrom`,
  `TopologicalSpace.eq_generateFrom_iff_isTopologicalBasis_finiteInterClosure`,
  `compactSpace_generateFrom`,
  `compactSpace_generateFrom'`

Layer triage:
- `source-facing`: a subbasis cover hypothesis stated as a finite-refinement condition
- `core/canonical`: `generateFrom` for the topology and `CompactSpace` for quasi-compactness
- `bridge/view`: the finite-refinement hypothesis is converted to the finite-subcover hypothesis of
  `compactSpace_generateFrom`

Primitive data is only the family `ℬ : Set (Set X)` together with the finite-refinement cover
hypothesis. The finite subcover conclusion is derived API, so this file should stay a small bridge
to `compactSpace_generateFrom` rather than introducing a parallel subbasis owner.
-/

/-- A finite cover refining a cover by `P` yields a finite subcover by members of `P`. -/
theorem exists_finite_subcover_of_refining_cover {X : Type u} {P Q : Set (Set X)}
    (hQfinite : Q.Finite) (hQcover : ⋃₀ Q = (univ : Set X))
    (hQrefines : ∀ V ∈ Q, ∃ U ∈ P, V ⊆ U) :
    ∃ R ⊆ P, R.Finite ∧ ⋃₀ R = (univ : Set X) := by
  classical
  have hQrefines' : ∀ V : Q, ∃ U ∈ P, V.1 ⊆ U := fun V ↦ hQrefines V.1 V.2
  choose r hrP hrsub using hQrefines'
  letI : Fintype Q := hQfinite.fintype
  refine ⟨Set.range r, ?_, Set.toFinite _, ?_⟩
  · rintro U ⟨V, rfl⟩
    exact hrP V
  · apply subset_antisymm (sUnion_subset fun _ _ ↦ subset_univ _)
    rw [← hQcover]
    intro x hx
    rcases mem_sUnion.mp hx with ⟨V, hVQ, hxV⟩
    refine mem_sUnion.mpr ⟨r ⟨V, hVQ⟩, ?_, ?_⟩
    · exact ⟨⟨V, hVQ⟩, rfl⟩
    · exact hrsub ⟨V, hVQ⟩ hxV

section

variable {X : Type u} [t : TopologicalSpace X]

/- Companion recall: `compactSpace_generateFrom` is mathlib's canonical finite-subcover form of
Alexander's subbasis theorem for a topology generated by a subbasis. -/
recall compactSpace_generateFrom

-- Proof sketch: starting from a cover `P ⊆ ℬ`, use the assumed finite refinement `Q`. For
-- each `V ∈ Q`, choose some `U ∈ P` with `V ⊆ U`; the chosen finitely many members of `P` still
-- cover `X`. This upgrades the finite-refinement hypothesis to the finite-subcover hypothesis of
-- `compactSpace_generateFrom`.
/-- Lemma 5.12.15 (Alexander subbase theorem): if `ℬ` is a subbasis for the topology on `X` and
every cover of `X` by elements of `ℬ` admits a finite refining cover, then `X` is
quasi-compact. Here a refining cover is a finite family `Q` covering `X` such that each
`V ∈ Q` is contained in some member of the original cover. -/
theorem compactSpace_of_subbasis_finite_refinement {ℬ : Set (Set X)}
    (hℬ : t = generateFrom ℬ)
    (hfinite :
      ∀ P ⊆ ℬ, ⋃₀ P = (univ : Set X) →
        ∃ Q : Finset (Set X), ⋃₀ (↑Q : Set (Set X)) = (univ : Set X) ∧
          ∀ V ∈ Q, ∃ U ∈ P, V ⊆ U) :
    CompactSpace X := by
  refine compactSpace_generateFrom hℬ fun P hP hcover ↦ ?_
  obtain ⟨Q, hQcover, hQrefines⟩ := hfinite P hP hcover
  exact exists_finite_subcover_of_refining_cover Q.finite_toSet hQcover fun V hV ↦
    hQrefines V (Finset.mem_coe.mp hV)

end
