module

public import Mathlib.Topology.Constructible

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open Set TopologicalSpace Topology

namespace Topology

variable {X : Type u} [TopologicalSpace X] {E : Set X}

/-
Domain-style sampling for constructible subsets and retrocompactness:
- primary domain: constructible subsets of topological spaces, viewed through the Boolean
  subalgebra generated by open retrocompact subsets;
- sampled canonical declarations:
  `Topology.IsConstructible`,
  `BooleanSubalgebra.closure_sdiff_sup_induction`,
  `IsRetrocompact.union`,
  `IsRetrocompact.inter_isOpen`;
- best owner abstraction: `Topology.IsConstructible` is the source-facing owner notion, and its
  generator-style proofs should be organized through
  `BooleanSubalgebra.closure_sdiff_sup_induction` on the family of open retrocompact subsets;
- primitive-vs-derived split: the primitive data is only membership in that Boolean closure.
  Retrocompactness of an arbitrary constructible subset is derived API, so this file should expose
  the theorem directly and keep any lattice witness local to the proof.

Layer triage:
- `source-facing`: Lemma 5.15.10 itself, asserting that constructible subsets are retrocompact;
- `core/canonical`: the Boolean-subalgebra closure induction principle;
- `bridge/view`: none.
-/

-- Proof sketch: `IsConstructible E` means membership in the Boolean subalgebra generated by the
-- open retrocompact subsets. The generator family is a sublattice, and the difference of two
-- open retrocompact subsets is retrocompact. So
-- `BooleanSubalgebra.closure_sdiff_sup_induction` upgrades retrocompactness from the generators to
-- every constructible set.
/-- Lemma 5.15.10: every constructible subset of a topological space is retrocompact. -/
theorem IsConstructible.isRetrocompact (hE : IsConstructible E) : IsRetrocompact E := by
  -- Rewrite constructibility into membership in the Boolean closure generated by open
  -- retrocompact subsets so the source proof becomes a closure induction.
  change E ∈ BooleanSubalgebra.closure {U : Set X | IsOpen U ∧ IsRetrocompact U} at hE
  refine BooleanSubalgebra.closure_sdiff_sup_induction
    (⟨
      fun U hU V hV ↦ ⟨hU.1.union hV.1, hU.2.union hV.2⟩,
      fun U hU V hV ↦ ⟨hU.1.inter hV.1, hU.2.inter_isOpen hV.2 hV.1⟩
    ⟩ : IsSublattice {U : Set X | IsOpen U ∧ IsRetrocompact U})
    (by simp) (by simp) ?_ ?_ E hE
  · intro U hU V hV W hW_comp hW_open
    -- Intersect the locally closed piece `U \ V` with an arbitrary compact open `W`,
    -- then use compactness of `(U ∩ W) \ V` and rewrite back to the desired trace.
    simpa [sdiff_eq, inter_assoc, inter_left_comm, inter_comm] using
      (hU.2 hW_comp hW_open).diff hV.1
  · intro U _ V _ hU hV
    -- The union branch is exactly stability of retrocompactness under finite unions.
    exact hU.union hV

end Topology
