module

public import Mathlib.Topology.Sober

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

open Set TopologicalSpace

variable {X : Type u} [TopologicalSpace X]

/- Domain-style sampling for soberification via irreducible closed subsets:
- primary domain: generic points, quasi-sobriety, `T₀` separation, and the space of irreducible
  closed subsets;
- sampled owner declarations:
  `IrreducibleCloseds`,
  `IrreducibleCloseds.map`,
  `QuasiSober`,
  `irreducibleSetEquivPoints`,
  `SeparationQuotient.lift`;
- best owner abstraction: the primitive owner object is `IrreducibleCloseds X`, while the
  canonical sober-space structure is carried by `[QuasiSober _] [T0Space _]`; the map
  `toIrreducibleCloseds` is the source-facing bridge from `X` to that owner space, and the
  canonical `T₀` owner for its image-level universal property is `SeparationQuotient X`;
- primitive-vs-derived split: the primitive data in this file is the topology on
  `IrreducibleCloseds X`, generated by the canonical basic opens coming from `Opens X`; the
  quasi-sober and `T₀` instances, the open-bijection theorem, and the universal properties are
  derived API, while the codomain change to the image of `toIrreducibleCloseds` is only a thin
  bridge/view of `SeparationQuotient X` and should not be repackaged as a second owner.

Layer triage:
- `source-facing`: the Stacks soberification construction of a space `X`;
- `core/canonical`: `IrreducibleCloseds`, `QuasiSober`, `T0Space`, `SeparationQuotient`, and
  generic-point machinery;
- `bridge/view`: the canonical map `toIrreducibleCloseds`, its lift from `SeparationQuotient X`,
  and its image factorization.
-/

namespace IrreducibleCloseds

/-- The basic open of the soberification attached to an open subset `U ⊆ X` consists of the
irreducible closed subsets of `X` that meet `U`. -/
def basicOpen (U : Opens X) : Set (IrreducibleCloseds X) :=
  {Z | ((Z : Set X) ∩ (U : Set X)).Nonempty}

/-- The soberification topology on `IrreducibleCloseds X`, generated by the basic opens coming from
opens of `X`. -/
instance : TopologicalSpace (IrreducibleCloseds X) :=
  generateFrom (Set.range fun U : Opens X ↦ basicOpen U)

end IrreducibleCloseds

/-- The pointwise map sending `x` to the irreducible closed subset `closure {x}`. -/
def toIrreducibleClosedsFun (x : X) : IrreducibleCloseds X :=
  ⟨closure ({x}), isIrreducible_singleton.closure, isClosed_closure⟩

/-- Helper for Lemma 5.8.16: the canonical basic open attached to `U` pulls back along
`x ↦ closure {x}` to the original open set `U`. -/
theorem preimage_basicOpen_toIrreducibleClosedsFun (U : Opens X) :
    (toIrreducibleClosedsFun ⁻¹' IrreducibleCloseds.basicOpen U) = (U : Set X) := by
  -- Translate membership in the basic open into a specialization statement.
  ext x
  constructor
  · intro hx
    rcases hx with ⟨y, hyClosure, hyU⟩
    exact (specializes_iff_mem_closure.mpr hyClosure).mem_open U.2 hyU
  · intro hx
    exact ⟨x, subset_closure (by simp), hx⟩

-- Proof sketch: for a basic open attached to an open `U`, the preimage under
-- `x ↦ closure {x}` is exactly `U`; this proves continuity against the generating family.
/-- The pointwise soberification map is continuous. -/
theorem continuous_toIrreducibleClosedsFun : Continuous (toIrreducibleClosedsFun : X → IrreducibleCloseds X) :=
  by
    -- It suffices to check openness on the generating family of basic opens.
    rw [continuous_generateFrom_iff]
    rintro _ ⟨U, rfl⟩
    rw [preimage_basicOpen_toIrreducibleClosedsFun]
    exact U.2

/-- The canonical continuous map from `X` to its space of irreducible closed subsets. -/
def toIrreducibleCloseds : C(X, IrreducibleCloseds X) :=
  ⟨toIrreducibleClosedsFun, continuous_toIrreducibleClosedsFun⟩

-- Proof sketch: a specialization `x ⤳ y` says `y ∈ closure {x}`, hence
-- `closure {y} ⊆ closure {x}`; reinterpret this inclusion in `IrreducibleCloseds X`.
/-- A specialization `x ⤳ y` induces the reverse inclusion on irreducible point closures, viewed
in the canonical owner `IrreducibleCloseds X`. -/
theorem Specializes.toIrreducibleCloseds_le {x y : X} (hxy : x ⤳ y) :
    toIrreducibleCloseds y ≤ toIrreducibleCloseds x := by
  -- Specialization gives inclusion of singleton closures in the reverse direction.
  show closure ({y} : Set X) ⊆ closure ({x} : Set X)
  intro z hz
  exact (hxy.trans (specializes_iff_mem_closure.mpr hz)).mem_closure

-- Proof sketch: equality of the closures `closure {x}` and `closure {y}` is exactly
-- `inseparable_iff_closure_eq`; convert between equality in `IrreducibleCloseds X` and equality of
-- the underlying closed subsets.
/-- The canonical map to irreducible point closures identifies exactly the inseparable points of
`X`. This is the bridge from the source-facing soberification map to the canonical `T₀` owner
`SeparationQuotient X`. -/
theorem toIrreducibleCloseds_eq_iff_inseparable {x y : X} :
    toIrreducibleCloseds x = toIrreducibleCloseds y ↔ Inseparable x y := by
  constructor
  · intro h
    rw [inseparable_iff_closure_eq]
    exact congrArg (fun Z : IrreducibleCloseds X ↦ (Z : Set X)) h
  · intro h
    apply IrreducibleCloseds.ext
    exact inseparable_iff_closure_eq.mp h

-- Proof sketch: `SeparationQuotient.lift` is well defined because
-- `toIrreducibleCloseds_eq_iff_inseparable` identifies the fibers of `toIrreducibleCloseds` with
-- inseparability classes; continuity then follows from the quotient characterization.
/-- The separation-quotient lift of the soberification map is continuous. -/
theorem continuous_toIrreducibleClosedsFromSeparationQuotient :
    Continuous
      (SeparationQuotient.lift (toIrreducibleCloseds : X → IrreducibleCloseds X)
        (fun _ _ hxy ↦ toIrreducibleCloseds_eq_iff_inseparable.2 hxy)) := by
  -- The separation quotient is defined precisely to make such inseparability-invariant maps
  -- continuous.
  exact
    (SeparationQuotient.continuous_lift
      (f := (toIrreducibleCloseds : X → IrreducibleCloseds X))
      (hf := fun _ _ hxy ↦ toIrreducibleCloseds_eq_iff_inseparable.2 hxy)).2
      toIrreducibleCloseds.continuous

/-- The source-facing map `toIrreducibleCloseds` descends along the canonical `T₀` owner
`SeparationQuotient X`. -/
noncomputable def toIrreducibleClosedsFromSeparationQuotient :
    C(SeparationQuotient X, IrreducibleCloseds X) :=
  ⟨SeparationQuotient.lift toIrreducibleCloseds
      (fun _ _ hxy ↦ toIrreducibleCloseds_eq_iff_inseparable.2 hxy),
    continuous_toIrreducibleClosedsFromSeparationQuotient⟩

-- Proof sketch: both sides are continuous maps whose underlying functions are definitionally the
-- same composite `x ↦ closure {x}`.
/-- Composing the quotient lift with the quotient map recovers `toIrreducibleCloseds`. -/
theorem toIrreducibleClosedsFromSeparationQuotient_comp_mk :
    toIrreducibleClosedsFromSeparationQuotient.comp
        (show C(X, SeparationQuotient X) from
          ⟨SeparationQuotient.mk, SeparationQuotient.continuous_mk⟩) =
      toIrreducibleCloseds := by
  -- Both continuous maps evaluate to the same closure on each source point.
  ext x
  rfl

namespace IrreducibleCloseds

/-- Helper for Lemma 5.8.16: the basic open attached to the total open set is all of
`IrreducibleCloseds X`. -/
theorem basicOpen_top : basicOpen (⊤ : Opens X) = (Set.univ : Set (IrreducibleCloseds X)) := by
  -- Every irreducible closed subset is nonempty, so it meets the whole space.
  ext Z
  constructor
  · intro _
    trivial
  · intro _
    rcases Z.isIrreducible.nonempty with ⟨x, hxZ⟩
    exact ⟨x, hxZ, by simp⟩

/-- Helper for Lemma 5.8.16: enlarging the source open enlarges the corresponding basic open. -/
theorem basicOpen_mono {U V : Opens X} (hUV : U ≤ V) :
    basicOpen U ⊆ basicOpen V := by
  -- A witness to meeting `U` is also a witness to meeting the larger open `V`.
  intro Z hZ
  rcases hZ with ⟨x, hxZ, hxU⟩
  exact ⟨x, hxZ, hUV hxU⟩

/-- Helper for Lemma 5.8.16: the basic-open construction sends finite intersections of opens in
`X` to finite intersections of opens in the soberification. -/
theorem basicOpen_inf (U V : Opens X) :
    basicOpen (U ⊓ V) = basicOpen U ∩ basicOpen V := by
  ext Z
  constructor
  · intro hZ
    rcases hZ with ⟨x, hxZ, hxUV⟩
    exact ⟨⟨x, hxZ, hxUV.1⟩, ⟨x, hxZ, hxUV.2⟩⟩
  · intro hZ
    rcases hZ with ⟨hZU, hZV⟩
    -- Irreducibility of `Z` upgrades separate intersections to an intersection with the overlap.
    exact Z.isIrreducible.isPreirreducible _ _ U.2 V.2 hZU hZV

/-- Helper for Lemma 5.8.16: the basic-open construction sends arbitrary unions of opens in `X`
to unions of the corresponding basic opens. -/
theorem basicOpen_sSup (S : Set (Opens X)) :
    basicOpen (sSup S) = ⋃ U ∈ S, basicOpen U := by
  ext Z
  constructor
  · intro hZ
    rcases hZ with ⟨x, hxZ, hx⟩
    rcases TopologicalSpace.Opens.mem_sSup.mp hx with ⟨U, hU, hxU⟩
    exact Set.mem_iUnion.2 ⟨U, Set.mem_iUnion.2 ⟨hU, ⟨x, hxZ, hxU⟩⟩⟩
  · intro hZ
    rcases Set.mem_iUnion.1 hZ with ⟨U, hZ⟩
    rcases Set.mem_iUnion.1 hZ with ⟨hU, hZU⟩
    rcases hZU with ⟨x, hxZ, hxU⟩
    exact ⟨x, hxZ, TopologicalSpace.Opens.mem_sSup.2 ⟨U, hU, hxU⟩⟩

end IrreducibleCloseds

/-- Helper for Lemma 5.8.16: the canonical basic opens form a topological basis on
`IrreducibleCloseds X`. -/
theorem isTopologicalBasis_basicOpen :
    IsTopologicalBasis
      (Set.range fun U : Opens X ↦ IrreducibleCloseds.basicOpen U) := by
  have huniv :
      (Set.univ : Set (IrreducibleCloseds X)) ∈
        Set.range (fun U : Opens X ↦ IrreducibleCloseds.basicOpen U) := by
    exact ⟨⊤, IrreducibleCloseds.basicOpen_top⟩
  have hb :
      IsTopologicalBasis
        (insert (Set.univ : Set (IrreducibleCloseds X))
          (Set.range fun U : Opens X ↦ IrreducibleCloseds.basicOpen U)) :=
    TopologicalSpace.isTopologicalBasis_of_subbasis_of_inter (t := inferInstance) rfl (by
      rintro _ ⟨U, rfl⟩ _ ⟨V, rfl⟩
      exact ⟨U ⊓ V, IrreducibleCloseds.basicOpen_inf U V⟩)
  simpa [Set.insert_eq_of_mem huniv] using hb

/-- Helper for Lemma 5.8.16: every open of the soberification is a unique basic open coming from
an open of `X`. -/
theorem isOpen_iff_exists_basicOpen {s : Set (IrreducibleCloseds X)} :
    IsOpen s ↔ ∃ U : Opens X, s = IrreducibleCloseds.basicOpen U := by
  let B : Set (Set (IrreducibleCloseds X)) :=
    Set.range fun U : Opens X ↦ IrreducibleCloseds.basicOpen U
  have hB : IsTopologicalBasis B := isTopologicalBasis_basicOpen
  constructor
  · intro hs
    let S : Set (Opens X) := {U | IrreducibleCloseds.basicOpen U ⊆ s}
    -- Reassemble the open set from all basic opens contained in it.
    refine ⟨sSup S, ?_⟩
    ext Z
    constructor
    · intro hZ
      rcases (hB.isOpen_iff.1 hs) Z hZ with ⟨t, htB, hZt, hts⟩
      rcases htB with ⟨U, rfl⟩
      exact
        (IrreducibleCloseds.basicOpen_mono
          (show U ≤ sSup S from le_sSup hts)) hZt
    · intro hZ
      rw [IrreducibleCloseds.basicOpen_sSup] at hZ
      rcases Set.mem_iUnion.1 hZ with ⟨U, hZ⟩
      rcases Set.mem_iUnion.1 hZ with ⟨hU, hZU⟩
      exact hU hZU
  · rintro ⟨U, rfl⟩
    exact hB.isOpen ⟨U, rfl⟩

-- Proof sketch: let `T` be an irreducible closed subset of `IrreducibleCloseds X`, write its
-- complement as a basic open coming from an open `U ⊆ X`, and show that the closed subset
-- `X \ U` is irreducible; this closed subset is then the unique generic point of `T`.
/-- The soberification topology makes `IrreducibleCloseds X` quasi-sober. -/
instance : QuasiSober (IrreducibleCloseds X) where
  sober {T} hTir hTcl := by
    obtain ⟨U, hU⟩ := (isOpen_iff_exists_basicOpen).1 hTcl.isOpen_compl
    let Zset : Set X := (U : Set X)ᶜ
    have hZcl : IsClosed Zset := isClosed_compl_iff.2 U.2
    have hTmem : ∀ W : IrreducibleCloseds X, W ∈ T ↔ (W : Set X) ⊆ Zset := by
      intro W
      constructor
      · intro hWT x hxW hxU
        have hWnot : W ∉ Tᶜ := by
          simpa [Set.mem_compl_iff] using hWT
        exact hWnot (by
          rw [hU, IrreducibleCloseds.basicOpen]
          exact ⟨x, hxW, hxU⟩)
      · intro hWsub
        by_contra hWT
        have hWcompl : W ∈ Tᶜ := by
          simpa [Set.mem_compl_iff] using hWT
        have hWbasic : W ∈ IrreducibleCloseds.basicOpen U := by
          simpa [hU] using hWcompl
        rcases hWbasic with ⟨x, hxW, hxU⟩
        exact hWsub hxW hxU
    have hZnonempty : Zset.Nonempty := by
      rcases hTir.nonempty with ⟨W, hWT⟩
      rcases W.isIrreducible.nonempty with ⟨x, hxW⟩
      exact ⟨x, hTmem W |>.mp hWT hxW⟩
    have hZpreirr : IsPreirreducible Zset := by
      intro V W hV hW hZV hZW
      rcases hZV with ⟨x, hxZ, hxV⟩
      rcases hZW with ⟨y, hyZ, hyW⟩
      have hxT : toIrreducibleClosedsFun x ∈ T := by
        have hxSubset : ({x} : Set X) ⊆ Zset := by
          intro z hz
          simp only [Set.mem_singleton_iff] at hz
          simpa [hz] using hxZ
        exact hTmem _ |>.2 (closure_minimal hxSubset hZcl)
      have hyT : toIrreducibleClosedsFun y ∈ T := by
        have hySubset : ({y} : Set X) ⊆ Zset := by
          intro z hz
          simp only [Set.mem_singleton_iff] at hz
          simpa [hz] using hyZ
        exact hTmem _ |>.2 (closure_minimal hySubset hZcl)
      have hTx : (T ∩ IrreducibleCloseds.basicOpen ⟨V, hV⟩).Nonempty :=
        ⟨_, hxT, ⟨x, subset_closure (by simp), hxV⟩⟩
      have hTy : (T ∩ IrreducibleCloseds.basicOpen ⟨W, hW⟩).Nonempty :=
        ⟨_, hyT, ⟨y, subset_closure (by simp), hyW⟩⟩
      -- Transfer irreducibility of `T` back to the closed set `Zset ⊆ X`.
      have hTxy :
          (T ∩
            (IrreducibleCloseds.basicOpen ⟨V, hV⟩ ∩
              IrreducibleCloseds.basicOpen ⟨W, hW⟩)).Nonempty :=
        hTir.isPreirreducible _ _ ((isOpen_iff_exists_basicOpen).2 ⟨_, rfl⟩)
          ((isOpen_iff_exists_basicOpen).2 ⟨_, rfl⟩) hTx hTy
      rcases hTxy with ⟨A, hAT, hAboth⟩
      have hAbasic : A ∈ IrreducibleCloseds.basicOpen (⟨V, hV⟩ ⊓ ⟨W, hW⟩) := by
        rw [IrreducibleCloseds.basicOpen_inf]
        exact hAboth
      rcases hAbasic with ⟨z, hzA, hzV, hzW⟩
      exact ⟨z, hTmem A |>.mp hAT hzA, hzV, hzW⟩
    have hZirr : IsIrreducible Zset := ⟨hZnonempty, hZpreirr⟩
    let Z : IrreducibleCloseds X := ⟨Zset, hZirr, hZcl⟩
    refine ⟨Z, ?_⟩
    have hZT : Z ∈ T := hTmem Z |>.2 Subset.rfl
    -- Use the closed-set characterization of generic points.
    refine (isGenericPoint_iff_forall_closed hTcl hZT).2 ?_
    intro C hC hZC W hWT
    obtain ⟨V, hV⟩ := (isOpen_iff_exists_basicOpen).1 hC.isOpen_compl
    have hZnotbasic : Z ∉ IrreducibleCloseds.basicOpen V := by
      simpa [← hV, Set.mem_compl_iff] using hZC
    by_contra hWC
    have hWbasic : W ∈ IrreducibleCloseds.basicOpen V := by
      simpa [← hV, Set.mem_compl_iff] using hWC
    have hZbasic : Z ∈ IrreducibleCloseds.basicOpen V := by
      rcases hWbasic with ⟨x, hxW, hxV⟩
      exact ⟨x, hTmem W |>.mp hWT hxW, hxV⟩
    exact hZnotbasic hZbasic

-- Proof sketch: if two irreducible closed subsets have the same basic-open neighborhoods, then
-- they meet exactly the same open subsets of `X`; testing against complements of closed sets shows
-- the subsets are equal.
/-- The soberification topology on `IrreducibleCloseds X` is `T₀`. -/
instance : T0Space (IrreducibleCloseds X) where
  t0 x y hxy := by
    rw [inseparable_iff_forall_isOpen] at hxy
    by_contra hne
    have hdiff :
        ((x : Set X) \ (y : Set X)).Nonempty ∨ ((y : Set X) \ (x : Set X)).Nonempty := by
      by_cases hxy' : (x : Set X) ⊆ (y : Set X)
      · right
        have : ¬ (y : Set X) ⊆ (x : Set X) := by
          intro hyx
          apply hne
          exact IrreducibleCloseds.ext (Subset.antisymm hxy' hyx)
        exact Set.not_subset.1 this
      · left
        exact Set.not_subset.1 hxy'
    rcases hdiff with ⟨z, hz, hzy⟩ | ⟨z, hzy, hzx⟩
    · let V : Opens (IrreducibleCloseds X) :=
        ⟨IrreducibleCloseds.basicOpen ⟨(y : Set X)ᶜ, y.isClosed.isOpen_compl⟩,
          (isOpen_iff_exists_basicOpen).2 ⟨_, rfl⟩⟩
      have hx : x ∈ V := ⟨z, hz, hzy⟩
      have hy : y ∉ V := by
        simp [V, IrreducibleCloseds.basicOpen]
      exact hy ((hxy V V.2).1 hx)
    · let V : Opens (IrreducibleCloseds X) :=
        ⟨IrreducibleCloseds.basicOpen ⟨(x : Set X)ᶜ, x.isClosed.isOpen_compl⟩,
          (isOpen_iff_exists_basicOpen).2 ⟨_, rfl⟩⟩
      have hy : y ∈ V := ⟨z, hzy, hzx⟩
      have hx : x ∉ V := by
        simp [V, IrreducibleCloseds.basicOpen]
      exact hx ((hxy V V.2).2 hy)

-- Proof sketch: for `U : Opens X`, the preimage of the basic open attached to `U` is `U`
-- itself. Surjectivity on opens follows because every open in the generated topology is shown to
-- be of basic-open form, and `Opens.comap` already preserves finite infima and arbitrary suprema.
/-- Preimage along `toIrreducibleCloseds` gives a bijection on open sets. -/
theorem toIrreducibleCloseds_opensComap_bijective :
    Function.Bijective (Opens.comap (toIrreducibleCloseds : C(X, IrreducibleCloseds X))) := by
  let inv : Opens X → Opens (IrreducibleCloseds X) := fun U ↦
    ⟨IrreducibleCloseds.basicOpen U, (isOpen_iff_exists_basicOpen).2 ⟨U, rfl⟩⟩
  have hright :
      Function.RightInverse inv
        (Opens.comap (toIrreducibleCloseds : C(X, IrreducibleCloseds X))) := by
    intro U
    apply Opens.ext
    rw [Opens.coe_comap]
    simpa using preimage_basicOpen_toIrreducibleClosedsFun U
  have hleft :
      Function.LeftInverse inv
        (Opens.comap (toIrreducibleCloseds : C(X, IrreducibleCloseds X))) := by
    intro V
    obtain ⟨U, hU⟩ := (isOpen_iff_exists_basicOpen).1 V.2
    have hcomap : Opens.comap (toIrreducibleCloseds : C(X, IrreducibleCloseds X)) V = U := by
      apply Opens.ext
      ext x
      constructor
      · intro hx
        have hmemV : toIrreducibleCloseds x ∈ V := by
          simpa [Opens.mem_comap] using hx
        have hVset : (V : Set (IrreducibleCloseds X)) = IrreducibleCloseds.basicOpen U := by
          simpa [Opens.carrier_eq_coe] using hU
        have hbasic : toIrreducibleCloseds x ∈ IrreducibleCloseds.basicOpen U := by
          change toIrreducibleCloseds x ∈ (V : Set (IrreducibleCloseds X)) at hmemV
          simpa [hVset] using hmemV
        exact
          (Iff.of_eq
            (congrArg (fun s : Set X ↦ x ∈ s)
              (preimage_basicOpen_toIrreducibleClosedsFun U))).1 hbasic
      · intro hx
        have hbasic : toIrreducibleCloseds x ∈ IrreducibleCloseds.basicOpen U := by
          exact
            (Iff.of_eq
              (congrArg (fun s : Set X ↦ x ∈ s)
                (preimage_basicOpen_toIrreducibleClosedsFun U))).2 hx
        have hVset : (V : Set (IrreducibleCloseds X)) = IrreducibleCloseds.basicOpen U := by
          simpa [Opens.carrier_eq_coe] using hU
        have hmemV : toIrreducibleCloseds x ∈ V := by
          change toIrreducibleCloseds x ∈ (V : Set (IrreducibleCloseds X))
          simpa [hVset] using hbasic
        simpa [Opens.mem_comap] using hmemV
    apply Opens.ext
    rw [hcomap]
    simpa [inv, Opens.carrier_eq_coe] using hU.symm
  exact ⟨hleft.injective, hright.surjective⟩

section SoberTargets

variable {Y : Type v} [TopologicalSpace Y] [QuasiSober Y] [T0Space Y]

/-- Helper for Lemma 5.8.16: the universal map sends an irreducible closed subset of `X` to the
generic point of its image closure in the sober target `Y`. -/
noncomputable def universalMapFun (f : C(X, Y)) (Z : IrreducibleCloseds X) : Y :=
  ((irreducibleSetEquivPoints (α := Y)).toEquiv) (IrreducibleCloseds.map f f.continuous Z)

/-- Helper for Lemma 5.8.16: the universal map really is a generic point of the image closure. -/
theorem universalMapFun_generic (f : C(X, Y)) (Z : IrreducibleCloseds X) :
    IsGenericPoint (universalMapFun f Z)
      (↑(IrreducibleCloseds.map f f.continuous Z) : Set Y) := by
  -- Unfold the equivalence back to the closure of the chosen generic point.
  change closure ({universalMapFun f Z} : Set Y) =
      (↑(IrreducibleCloseds.map f f.continuous Z) : Set Y)
  simpa [universalMapFun, irreducibleSetEquivPoints] using
    congrArg (fun W : IrreducibleCloseds Y ↦ (W : Set Y))
      (((irreducibleSetEquivPoints (α := Y)).toEquiv).symm_apply_apply
        (IrreducibleCloseds.map f f.continuous Z))

/-- Helper for Lemma 5.8.16: preimages of opens under the universal map are the expected basic
opens coming from pulling back along `f`. -/
theorem preimage_universalMapFun (f : C(X, Y)) {V : Set Y} (hV : IsOpen V) :
    universalMapFun f ⁻¹' V =
      IrreducibleCloseds.basicOpen (Opens.comap f ⟨V, hV⟩) := by
  ext Z
  constructor
  · intro hZ
    have hgp := universalMapFun_generic f Z
    have hnonempty :
        ((↑(IrreducibleCloseds.map f f.continuous Z) : Set Y) ∩ V).Nonempty :=
      (hgp.mem_open_set_iff hV).1 hZ
    rw [IrreducibleCloseds.coe_map, closure_inter_open_nonempty_iff hV] at hnonempty
    rcases hnonempty with ⟨y, hyZ, hyV⟩
    rcases hyZ with ⟨x, hxZ, rfl⟩
    exact ⟨x, hxZ, hyV⟩
  · intro hZ
    have hgp := universalMapFun_generic f Z
    apply (hgp.mem_open_set_iff hV).2
    rw [IrreducibleCloseds.coe_map, closure_inter_open_nonempty_iff hV]
    rcases hZ with ⟨x, hxZ, hxV⟩
    exact ⟨f x, ⟨x, hxZ, rfl⟩, hxV⟩

/-- Helper for Lemma 5.8.16: the universal map is continuous because its open preimages are basic
opens. -/
theorem continuous_universalMapFun (f : C(X, Y)) : Continuous (universalMapFun f) := by
  rw [continuous_def]
  intro V hV
  rw [preimage_universalMapFun f hV]
  exact (isOpen_iff_exists_basicOpen).2 ⟨_, rfl⟩

/-- Helper for Lemma 5.8.16: the continuous-map package of the universal pointwise construction. -/
noncomputable def universalMap (f : C(X, Y)) : C(IrreducibleCloseds X, Y) :=
  ⟨universalMapFun f, continuous_universalMapFun f⟩

/-- Helper for Lemma 5.8.16: the universal map extends the original map on points. -/
theorem universalMap_comp_toIrreducibleCloseds (f : C(X, Y)) :
    (universalMap f).comp toIrreducibleCloseds = f := by
  ext x
  have hmap :
      (↑(IrreducibleCloseds.map f f.continuous (toIrreducibleCloseds x)) : Set Y) =
        closure ({f x} : Set Y) := by
    change closure (f '' closure ({x} : Set X)) = closure ({f x} : Set Y)
    rw [closure_image_closure f.continuous]
    simp
  have hgp :
      IsGenericPoint (universalMapFun f (toIrreducibleCloseds x))
        (closure ({f x} : Set Y)) := by
    rw [← hmap]
    exact universalMapFun_generic f (toIrreducibleCloseds x)
  exact hgp.eq isGenericPoint_closure

-- Proof sketch: for a sober target `Y`, send an irreducible closed subset `Z ⊆ X` to the unique
-- generic point of `closure (f '' Z)`. The equality `g ∘ c = f` is checked on points, continuity
-- is verified using the description of the opens of the soberification, and uniqueness comes from
-- the open-bijection property.
/-- The canonical map to irreducible closed subsets is universal for continuous maps into sober
spaces. -/
theorem toIrreducibleCloseds_universal (f : C(X, Y)) :
    ∃! g : C(IrreducibleCloseds X, Y), g.comp toIrreducibleCloseds = f := by
  refine ⟨universalMap f, universalMap_comp_toIrreducibleCloseds f, ?_⟩
  intro g hg
  ext Z
  have hpre :
      ∀ {V : Set Y} (hV : IsOpen V),
        g ⁻¹' V = IrreducibleCloseds.basicOpen (Opens.comap f ⟨V, hV⟩) := by
    intro V hV
    obtain ⟨U, hU⟩ := (isOpen_iff_exists_basicOpen).1 (g.continuous.isOpen_preimage V hV)
    have hUeq : U = Opens.comap f ⟨V, hV⟩ := by
      apply Opens.ext
      ext x
      constructor
      · intro hx
        have hbasic : toIrreducibleCloseds x ∈ IrreducibleCloseds.basicOpen U := by
          show x ∈ (toIrreducibleClosedsFun ⁻¹' IrreducibleCloseds.basicOpen U)
          rw [preimage_basicOpen_toIrreducibleClosedsFun]
          exact hx
        have hxg : g (toIrreducibleCloseds x) ∈ V := by
          change toIrreducibleCloseds x ∈ g ⁻¹' V
          rw [hU]
          exact hbasic
        have hgx : g (toIrreducibleCloseds x) = f x := by
          simpa using congrArg (fun h : C(X, Y) ↦ h x) hg
        simpa [hgx] using hxg
      · intro hx
        have hgx : g (toIrreducibleCloseds x) = f x := by
          simpa using congrArg (fun h : C(X, Y) ↦ h x) hg
        have hxg : g (toIrreducibleCloseds x) ∈ V := by
          simpa [hgx] using hx
        have hbasic : toIrreducibleCloseds x ∈ IrreducibleCloseds.basicOpen U := by
          have : toIrreducibleCloseds x ∈ g ⁻¹' V := hxg
          rw [hU] at this
          exact this
        show x ∈ (U : Set X)
        rw [← preimage_basicOpen_toIrreducibleClosedsFun U]
        exact hbasic
    simpa [hUeq] using hU
  have hgeneric : IsGenericPoint (g Z)
      (↑(IrreducibleCloseds.map f f.continuous Z) : Set Y) := by
    let T : Set Y := (↑(IrreducibleCloseds.map f f.continuous Z) : Set Y)
    have hTcl : IsClosed T := (IrreducibleCloseds.map f f.continuous Z).isClosed
    have hgT : g Z ∈ T := by
      by_contra hgT
      let V : Set Y := Tᶜ
      have hV : IsOpen V := hTcl.isOpen_compl
      have hZbasic : Z ∈ IrreducibleCloseds.basicOpen (Opens.comap f ⟨V, hV⟩) := by
        have hVmem : g Z ∈ V := by
          simpa [V, Set.mem_compl_iff] using hgT
        have : Z ∈ g ⁻¹' V := hVmem
        rwa [hpre hV] at this
      have hnonempty : (T ∩ V).Nonempty := by
        rw [show T = closure (f '' (Z : Set X)) by rfl, closure_inter_open_nonempty_iff hV]
        rcases hZbasic with ⟨x, hxZ, hxV⟩
        exact ⟨f x, ⟨x, hxZ, rfl⟩, hxV⟩
      simp [V] at hnonempty
    refine (isGenericPoint_iff_forall_closed hTcl hgT).2 ?_
    intro C hC hgC
    by_contra hTC
    obtain ⟨y, hyT, hyNotC⟩ := Set.not_subset.1 hTC
    let V : Set Y := Cᶜ
    have hV : IsOpen V := hC.isOpen_compl
    have hnonempty : (T ∩ V).Nonempty := by
      exact ⟨y, hyT, by simpa [V, Set.mem_compl_iff] using hyNotC⟩
    have hZbasic : Z ∈ IrreducibleCloseds.basicOpen (Opens.comap f ⟨V, hV⟩) := by
      rw [show T = closure (f '' (Z : Set X)) by rfl, closure_inter_open_nonempty_iff hV] at hnonempty
      rcases hnonempty with ⟨w, hwZ, hwV⟩
      rcases hwZ with ⟨x, hxZ, rfl⟩
      exact ⟨x, hxZ, hwV⟩
    have hgV : g Z ∈ V := by
      have : Z ∈ g ⁻¹' V := by
        rwa [hpre hV]
      exact this
    have hgNotV : g Z ∉ V := by
      simpa [V, Set.mem_compl_iff] using hgC
    exact hgNotV hgV
  exact hgeneric.eq (universalMapFun_generic f Z)

end SoberTargets

/-
Lemma 5.8.16 is carried by the canonical owner-level theorems
`toIrreducibleCloseds_opensComap_bijective` and `toIrreducibleCloseds_universal`, together with
the `QuasiSober` and `T0Space` instances on `IrreducibleCloseds X`. The range factorization below
is used through the canonical `Set.rangeFactorization`, and the `T₀`-universal clause is a
source-facing image view of the canonical owner `SeparationQuotient X`, not a second root owner.
-/

section T0Targets

variable {Y : Type v} [TopologicalSpace Y] [T0Space Y]

-- Proof sketch: first factor `f` uniquely through the canonical `T₀` owner `SeparationQuotient X`
-- using `SeparationQuotient.lift`, then use `toIrreducibleCloseds_eq_iff_inseparable` to descend
-- along the source-facing image of `toIrreducibleCloseds`.
/-- The image of the soberification map is universal for continuous maps from `X` into
Kolmogorov spaces. -/
theorem toIrreducibleClosedsImage_universal (f : C(X, Y)) :
    ∃! g : C(Set.range toIrreducibleCloseds, Y),
      g.comp
          ⟨Set.rangeFactorization toIrreducibleCloseds,
            toIrreducibleCloseds.continuous.rangeFactorization⟩ =
        f := by
  -- Factor through the range by choosing a representative of each image point.
  let cRange : C(X, Set.range toIrreducibleCloseds) :=
    ⟨Set.rangeFactorization toIrreducibleCloseds,
      toIrreducibleCloseds.continuous.rangeFactorization⟩
  let rangeLiftFun :
      Set.range (toIrreducibleCloseds : X → IrreducibleCloseds X) → Y :=
    fun z ↦ f (Classical.choose z.2)
  have hRangeLift_mk :
      ∀ x : X, rangeLiftFun ⟨toIrreducibleCloseds x, ⟨x, rfl⟩⟩ = f x := by
    intro x
    let x' : X :=
      Classical.choose (show ∃ y, toIrreducibleCloseds y = toIrreducibleCloseds x from ⟨x, rfl⟩)
    have hx' : toIrreducibleCloseds x' = toIrreducibleCloseds x :=
      Classical.choose_spec
        (show ∃ y, toIrreducibleCloseds y = toIrreducibleCloseds x from ⟨x, rfl⟩)
    change f x' = f x
    exact (toIrreducibleCloseds_eq_iff_inseparable.1 hx').map f.continuous |>.eq
  have hRangeLift_preimage :
      ∀ {V : Set Y} (hV : IsOpen V),
        rangeLiftFun ⁻¹' V =
          Subtype.val ⁻¹' IrreducibleCloseds.basicOpen (Opens.comap f ⟨V, hV⟩) := by
    intro V hV
    ext z
    let x : X := Classical.choose z.2
    have hx : toIrreducibleCloseds x = z.1 := Classical.choose_spec z.2
    change x ∈ Opens.comap f ⟨V, hV⟩ ↔
        z.1 ∈ IrreducibleCloseds.basicOpen (Opens.comap f ⟨V, hV⟩)
    rw [← hx]
    exact
      (Iff.of_eq
        (congrArg (fun s : Set X ↦ x ∈ s)
          (preimage_basicOpen_toIrreducibleClosedsFun (Opens.comap f ⟨V, hV⟩)))).symm
  have hRangeLift_cont : Continuous rangeLiftFun := by
    rw [continuous_def]
    intro V hV
    rw [hRangeLift_preimage hV]
    exact ((isOpen_iff_exists_basicOpen).2 ⟨_, rfl⟩).preimage continuous_subtype_val
  let rangeLift : C(Set.range toIrreducibleCloseds, Y) := ⟨rangeLiftFun, hRangeLift_cont⟩
  refine ⟨rangeLift, ?_, ?_⟩
  · ext x
    exact hRangeLift_mk x
  · intro g hg
    ext z
    rcases z with ⟨z, hz⟩
    rcases hz with ⟨x, rfl⟩
    have hx := congrArg (fun h : C(X, Y) ↦ h x) hg
    simpa [rangeLift, cRange, hRangeLift_mk] using hx

end T0Targets

-- Proof sketch: combine the canonical open-set bijection with the universal mapping property of
-- `toIrreducibleCloseds`; the codomain `IrreducibleCloseds X` is sober because it carries the
-- previously stated `QuasiSober` and `T0Space` instances.
/-- Lemma 5.8.16: the canonical map `X → IrreducibleCloseds X` presents `IrreducibleCloseds X` as
the soberification of `X`, in the sense that inverse image gives a bijection on opens and the map
is universal for continuous maps from `X` to sober spaces. -/
theorem irreducibleCloseds_soberification :
    Function.Bijective (Opens.comap (toIrreducibleCloseds : C(X, IrreducibleCloseds X))) ∧
      ∀ {Y : Type v} [TopologicalSpace Y] [QuasiSober Y] [T0Space Y] (f : C(X, Y)),
        ∃! g : C(IrreducibleCloseds X, Y), g.comp toIrreducibleCloseds = f := by
  -- The lemma is exactly the conjunction of the open-set bijection and the universal property.
  refine ⟨toIrreducibleCloseds_opensComap_bijective, ?_⟩
  intro Y _ _ _ f
  exact toIrreducibleCloseds_universal f
