module

public import Mathlib.CategoryTheory.EffectiveEpi.Comp
public import Mathlib.CategoryTheory.Sites.EffectiveEpimorphic
public import Mathlib.CategoryTheory.Sites.EqualizerSheafCondition
public import stacks_project.Chap04.Definition_4_6_4
public import stacks_project.Chap07.Definition_7_8_1
public import stacks_project.Chap07.Definition_7_8_2

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe w v u

namespace CategoryTheory

open Limits
open Equalizer.Presieve.Arrows

variable {C : Type u} [Category.{v} C]

namespace SemiRepresentableFamily
namespace Over

open CategoryTheory.Over (pullbackId)

variable {U : C}

/- Domain-style sampling for Definition 7.12.1:
- primary domain: effective epimorphic families in slice categories, expressed through the owner
  `SemiRepresentableFamily.Over U` and the canonical presieve generated by such a family;
- sampled owner declarations:
  `SemiRepresentableFamily.Over`,
  `SemiRepresentableFamily.Over.toPresieve`,
  `Presieve.EffectiveEpimorphic`,
  `(𝟭 C).relativelyRepresentable`;
- best owner abstraction:
  the source-facing owner remains `SemiRepresentableFamily.Over U`, while the canonical
  foundational notions are the generated-presieve owner `K.toPresieve.EffectiveEpimorphic` and
  the componentwise morphism property `(𝟭 C).relativelyRepresentable`;
- primitive-vs-derived split:
  primitive data: a fixed-target family `K : Over U`;
  derived API: effective-epimorphicity of the generated presieve, the induced
  `EffectiveEpiFamily` instance, pullback existence along each component, the Yoneda equalizer
  criterion, and the universal base-change stability predicate;
- source/core/bridge triage:
  `source-facing`: `IsEffectiveEpimorphism`, `IsUniversalEffectiveEpimorphism`;
  `core/canonical`: `K.toPresieve.EffectiveEpimorphic`, `(𝟭 C).relativelyRepresentable`;
  `bridge/view`: `baseChange`, which keeps only the pullbacks of the listed family members and so
  is more general than the ambient owner `Over.pullback f`, which would require
  `HasPullbacksAlong f`; under that stronger owner hypothesis, the companion bridge theorem
  `baseChange_eq_map_pullback` identifies it with `SemiRepresentableFamily.map
  (CategoryTheory.Over.pullback f)`. -/

/-- The componentwise slice pullback of a fixed-target family along a morphism `f : V ⟶ U`. -/
noncomputable abbrev baseChange (K : Over U) {V : C} (f : V ⟶ U)
    [∀ i : K.index, Limits.HasPullback (K.obj i).hom f] : Over V :=
  ofArrows
    (fun i : K.index ↦ Limits.pullback (K.obj i).hom f)
    (fun i ↦ Limits.pullback.snd (K.obj i).hom f)

/-- The `i`th component of `baseChange K f` is the pullback object over the new target. -/
@[simp] theorem baseChange_obj_hom (K : Over U) {V : C} (f : V ⟶ U)
    [∀ i : K.index, Limits.HasPullback (K.obj i).hom f] (i : K.index) :
    ((baseChange K f).obj i).hom = Limits.pullback.snd (K.obj i).hom f := rfl

instance hasPullback_of_hasPullbacksAlong
    (K : Over U) {V : C} (f : V ⟶ U) [Limits.HasPullbacksAlong f] (i : K.index) :
    Limits.HasPullback (K.obj i).hom f :=
  (inferInstance : Limits.HasPullbacksAlong f) (K.obj i).hom

attribute [instance 100] hasPullback_of_hasPullbacksAlong

/-- Definition 7.12.1 (1): a fixed-target family is an effective epimorphism when each component
arrow is representable and the presieve generated by the family is effective epimorphic. By
`Presieve.EffectiveEpimorphic.iff_forall_isSheafFor_yoneda` and
`Equalizer.Presieve.Arrows.sheaf_condition`, this is equivalent to the textbook equalizer
condition on representable presheaves. -/
class IsEffectiveEpimorphism (K : Over U) : Prop where
  /-- Every component arrow of the family is representable. -/
  representable (i : K.index) : (𝟭 C).relativelyRepresentable (K.obj i).hom
  /-- The canonical presieve generated by the family is effective epimorphic. -/
  effectiveEpimorphic : K.toPresieve.EffectiveEpimorphic

instance (K : Over U) [hK : IsEffectiveEpimorphism K] :
    EffectiveEpiFamily (fun i : K.index ↦ (K.obj i).left) (fun i ↦ (K.obj i).hom) :=
  (Sieve.effectiveEpimorphic_family
      (fun i : K.index ↦ (K.obj i).left)
      (fun i : K.index ↦ (K.obj i).hom)).mp
    hK.effectiveEpimorphic

theorem toPresieveHasPairwisePullbacks (K : Over U)
    (hK : ∀ i : K.index, Limits.HasPullbacksAlong (K.obj i).hom) :
    K.toPresieve.HasPairwisePullbacks where
  has_pullbacks := by
    intro Y Z f hf g hg
    obtain ⟨i, hi, rfl⟩ :=
      Presieve.ofArrows_surj (fun i : K.index ↦ (K.obj i).hom) f hf
    obtain ⟨j, hj, rfl⟩ :=
      Presieve.ofArrows_surj (fun i : K.index ↦ (K.obj i).hom) g hg
    subst hi
    subst hj
    simpa using hK j (K.obj i).hom

instance (K : Over U) [hK : IsEffectiveEpimorphism K] (i : K.index) :
    Limits.HasPullbacksAlong (K.obj i).hom :=
  (relativelyRepresentable_iff_hasPullbacksAlong _).mp (hK.representable i)

theorem hasPullback_of_representable {V W : C} (f : V ⟶ U) {g : W ⟶ U}
    (hg : (𝟭 C).relativelyRepresentable g) : Limits.HasPullback g f := by
  haveI : Limits.HasPullback f g := (relativelyRepresentable_iff_hasPullbacksAlong _).mp hg f
  exact Limits.hasPullback_symmetry f g

instance (K : Over U) [hK : IsEffectiveEpimorphism K] {V : C} (f : V ⟶ U) (i : K.index) :
    Limits.HasPullback (K.obj i).hom f :=
  hasPullback_of_representable f (hK.representable i)

instance (K : Over U) [hK : IsEffectiveEpimorphism K] :
    K.toPresieve.HasPairwisePullbacks :=
  toPresieveHasPairwisePullbacks K fun i ↦
    (inferInstance : Limits.HasPullbacksAlong (K.obj i).hom)

instance ofArrowsHasPairwisePullbacks (K : Over U) [IsEffectiveEpimorphism K] :
    (Presieve.ofArrows (fun i : K.index ↦ (K.obj i).left)
      fun i ↦ (K.obj i).hom).HasPairwisePullbacks := by
  simpa [toPresieve] using (inferInstance : K.toPresieve.HasPairwisePullbacks)

/-- The textbook equalizer fork on `Hom_{\mathcal C}(-, X)` attached to an effective epimorphism
family `K`. -/
noncomputable abbrev yonedaEqualizerFork
    (K : Over U) [IsEffectiveEpimorphism K] (X : C) :
    Fork
      (firstMap (yoneda.obj X)
        (fun i : K.index ↦ (K.obj i).left)
        (fun i ↦ (K.obj i).hom))
      (secondMap (yoneda.obj X)
        (fun i : K.index ↦ (K.obj i).left)
        (fun i ↦ (K.obj i).hom)) :=
  Limits.Fork.ofι
    (forkMap (yoneda.obj X)
      (fun i : K.index ↦ (K.obj i).left)
      (fun i ↦ (K.obj i).hom))
    (w (yoneda.obj X)
      (fun i : K.index ↦ (K.obj i).left)
      (fun i ↦ (K.obj i).hom))

-- Proof sketch: apply `sheaf_condition` to the representable presheaf
-- `yoneda.obj X` and the presieve generated by the component arrows of `K`; the pairwise pullbacks
-- come from the representability of the component arrows.
theorem isEffectiveEpimorphism_yoneda_equalizer_nonempty (K : Over U)
    [hK : IsEffectiveEpimorphism K] (X : C) :
    Nonempty (Limits.IsLimit (yonedaEqualizerFork K X)) := by
  have hSheaf : K.toPresieve.IsSheafFor (yoneda.obj X) :=
    Presieve.EffectiveEpimorphic.isSheafFor_of_isRepresentable
      hK.effectiveEpimorphic (yoneda.obj X)
  simpa [toPresieve] using
    (sheaf_condition
      (yoneda.obj X)
      (fun i : K.index ↦ (K.obj i).left)
      (fun i ↦ (K.obj i).hom)).mp hSheaf

/-- An effective epimorphism family satisfies the textbook equalizer diagram on
`Hom_{\mathcal C}(-, X)` for every object `X`. -/
noncomputable def IsEffectiveEpimorphism.yonedaEqualizerIsLimit (K : Over U)
    [IsEffectiveEpimorphism K] (X : C) :
    Limits.IsLimit (yonedaEqualizerFork K X) :=
  (isEffectiveEpimorphism_yoneda_equalizer_nonempty K X).some

instance hasPullbacksAlong_id : Limits.HasPullbacksAlong (𝟙 U) := by
  intro W g
  exact (IsPullback.id_horiz g).hasPullback

/-- Helper for Definition 7.12.1: the identity base change has a canonical comparison map from the
pulled-back component back to the original slice object. -/
noncomputable abbrev baseChangeIdHom (K : Over U) (i : K.index) :
    ((baseChange K (𝟙 U)).obj i) ⟶ K.obj i :=
  -- The pullback over the identity maps back to the original arrow by the first projection.
  CategoryTheory.Over.homMk (Limits.pullback.fst (K.obj i).hom (𝟙 U)) (by
    simpa using
      (Limits.pullback.condition :
        Limits.pullback.fst (K.obj i).hom (𝟙 U) ≫ (K.obj i).hom =
          Limits.pullback.snd (K.obj i).hom (𝟙 U) ≫ 𝟙 U))

/-- Helper for Definition 7.12.1: the comparison map from the identity base change is an
isomorphism on the underlying object. -/
instance baseChangeIdHom_left_isIso (K : Over U) (i : K.index) :
    IsIso ((baseChangeIdHom K i).left) := by
  letI : Limits.HasPullback (K.obj i).hom (𝟙 U) :=
    (IsPullback.id_horiz (K.obj i).hom).hasPullback
  change IsIso (Limits.pullback.fst (K.obj i).hom (𝟙 U))
  have hIsoId : IsIso (𝟙 U) := by
    exact ⟨⟨𝟙 U, by simp, by simp⟩⟩
  exact @Limits.pullback_fst_iso_of_right_iso _ _ _ _ _ (K.obj i).hom (𝟙 U) hIsoId

/-- Helper for Definition 7.12.1: the comparison map from the identity base change is epi on the
underlying object because it is an isomorphism. -/
instance baseChangeIdHom_left_epi (K : Over U) (i : K.index) :
    Epi ((baseChangeIdHom K i).left) := by
  infer_instance

theorem isEffectiveEpimorphism_of_baseChangeId (K : Over U)
    (hK : IsEffectiveEpimorphism (baseChange K (𝟙 U))) :
    IsEffectiveEpimorphism K where
  representable i := by
    -- Route correction: transport representability along the concrete pullback projection rather
    -- than through a nonexistent category structure on fixed-target families.
    have hw :
        (baseChangeIdHom K i).left ≫ (K.obj i).hom =
          ((baseChange K (𝟙 U)).obj i).hom :=
      Over.w (baseChangeIdHom K i)
    exact
      (((𝟭 C).relativelyRepresentable).cancel_left_of_respectsIso
          ((baseChangeIdHom K i).left) ((K.obj i).hom)).mp
        (hw ▸ hK.representable i)
  effectiveEpimorphic := by
    -- The base-changed family is effective with composite arrows equal to the original pullback
    -- family, so composing by the epi comparison maps preserves effective epimorphicity.
    let g : (i : K.index) → ((baseChange K (𝟙 U)).obj i).left ⟶ (K.obj i).left :=
      fun i ↦ (baseChangeIdHom K i).left
    have hcomp :
        (fun i ↦ g i ≫ (K.obj i).hom) =
          fun i ↦ ((baseChange K (𝟙 U)).obj i).hom := by
      funext i
      exact Over.w (baseChangeIdHom K i)
    have hEffective :
        EffectiveEpiFamily
          (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).left)
          (fun i ↦ g i ≫ (K.obj i).hom) := by
      let hEffective' :
          EffectiveEpiFamily
            (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).left)
            (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).hom) :=
        (Sieve.effectiveEpimorphic_family
          (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).left)
          (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).hom)).mp hK.effectiveEpimorphic
      exact hcomp.symm ▸ hEffective'
    letI :
        ∀ i : K.index, Epi (g i) :=
      fun i ↦ by
        simpa [g] using (inferInstance : Epi ((baseChangeIdHom K i).left))
    letI :
        EffectiveEpiFamily
          (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).left)
          (fun i ↦ g i ≫ (K.obj i).hom) :=
      hEffective
    let hFinal :
        EffectiveEpiFamily (fun i : K.index ↦ (K.obj i).left)
          (fun i ↦ (K.obj i).hom) :=
      @effectiveEpiFamily_of_effectiveEpi_epi_comp _ _ _ _ _ _
        (fun i ↦ (K.obj i).hom)
        g
        (fun i ↦ by
          simpa [g] using (inferInstance : Epi ((baseChangeIdHom K i).left)))
        hEffective
    simpa [toPresieve] using
      (Sieve.effectiveEpimorphic_family
        (fun i : K.index ↦ (K.obj i).left)
        (fun i : K.index ↦ (K.obj i).hom)).mpr hFinal

/-- Definition 7.12.1 (2): a fixed-target family is a universal effective epimorphism when every
base change of the family is again an effective epimorphism. -/
class IsUniversalEffectiveEpimorphism (K : Over U) : Prop where
  /-- Pulling back the family along any morphism into the target yields another effective
  epimorphism family. -/
  effective_baseChange {V : C} (f : V ⟶ U)
      [∀ i : K.index, Limits.HasPullback (K.obj i).hom f] :
      IsEffectiveEpimorphism (baseChange K f)

theorem IsUniversalEffectiveEpimorphism.representable {K : Over U}
    (hK : IsUniversalEffectiveEpimorphism K) (i : K.index) :
    (𝟭 C).relativelyRepresentable (K.obj i).hom :=
  (isEffectiveEpimorphism_of_baseChangeId K (hK.effective_baseChange (𝟙 U))).representable i

instance (K : Over U) [hK : IsUniversalEffectiveEpimorphism K] {V : C} (f : V ⟶ U)
    (i : K.index) : Limits.HasPullback (K.obj i).hom f :=
  hasPullback_of_representable f (hK.representable i)

instance (K : Over U) [hK : IsUniversalEffectiveEpimorphism K] :
    IsEffectiveEpimorphism K :=
  isEffectiveEpimorphism_of_baseChangeId K (hK.effective_baseChange (𝟙 U))

instance (K : Over U) [hK : IsUniversalEffectiveEpimorphism K] {V : C} (f : V ⟶ U) :
    IsEffectiveEpimorphism (baseChange K f) :=
  hK.effective_baseChange f

end Over
end SemiRepresentableFamily

end CategoryTheory
