module

public import Mathlib.CategoryTheory.Sites.PrecoverageToGrothendieck
public import stacks_project.Chap07.Definition_7_8_1

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe w₂ w₁ w v u

namespace CategoryTheory

variable {C : Type u} [Category.{v} C] {U : C}

namespace SemiRepresentableFamily

namespace Over

/-- Helper for Definition 7.8.2: the indexed-arrow presentation of a fixed-target family. -/
def ofArrows {I : Type w₁} (Uᵢ : I → C) (π : ∀ i : I, Uᵢ i ⟶ U) :
    SemiRepresentableFamily.Over.{w₁} U where
  index := I
  obj := fun i ↦ CategoryTheory.Over.mk (π i)

/- Domain-style sampling for Definition 7.8.2:
- primary domain: fixed-target families of arrows, viewed as objects of
  `SemiRepresentableFamily.Over U`, together with the presieves and sieves they generate;
- sampled owner declarations:
  `SemiRepresentableFamily.Over` from `Definition_7_8_1`,
  `Presieve.ofArrows_comp_eq_of_surjective`,
  `Sieve.ofArrows`,
  `CategoryTheory.Over.isoMk`;
- best owner abstraction: the source-facing owner remains `SemiRepresentableFamily.Over U`;
  `toPresieve` and `toSieve` are bridge/view API from that owner to the canonical mathlib presieve
  and sieve constructions on indexed arrow families;
- primitive data: a fixed-target family `𝒰 : Over U`;
- derived API: the generated presieve/sieve and the equivalence relations defined in terms of those
  canonical generated objects.

Source/core/bridge triage:
- `source-facing`: `CombinatoriallyEquivalent`, `TautologicallyEquivalent`;
- `core/canonical`: `SemiRepresentableFamily.Over U`;
- `bridge/view`: `toPresieve`, `toSieve`.
-/

/-- The canonical presieve on `U` generated by a fixed-target family. -/
abbrev toPresieve (𝒰 : Over.{w} U) : Presieve U :=
  Presieve.ofArrows (fun i ↦ (𝒰.obj i).left) fun i ↦ (𝒰.obj i).hom

@[simp]
theorem toPresieve_ofArrows {I : Type w₁} (Uᵢ : I → C) (π : ∀ i : I, Uᵢ i ⟶ U) :
    toPresieve (ofArrows Uᵢ π) = Presieve.ofArrows Uᵢ π :=
  rfl

@[simp]
theorem toPresieve_ofArrows_ulift {I : Type w₁} (Uᵢ : I → C) (π : ∀ i : I, Uᵢ i ⟶ U) :
    toPresieve (ofArrows (fun i : ULift.{w₂} I ↦ Uᵢ i.down) fun i ↦ π i.down) =
      Presieve.ofArrows Uᵢ π := by
  -- Compare the two indexed presentations through the surjective map `ULift.down`.
  simpa [ofArrows, toPresieve] using
    (Presieve.ofArrows_comp_eq_of_surjective π ULift.down_surjective)

/-- The canonical sieve on `U` generated by a fixed-target family. -/
abbrev toSieve (𝒰 : Over.{w} U) : Sieve U :=
  Sieve.generate (toPresieve 𝒰)

@[simp]
theorem toSieve_ofArrows {I : Type w₁} (Uᵢ : I → C) (π : ∀ i : I, Uᵢ i ⟶ U) :
    toSieve (ofArrows Uᵢ π) = Sieve.ofArrows Uᵢ π :=
  rfl

@[simp]
theorem toSieve_ofArrows_ulift {I : Type w₁} (Uᵢ : I → C) (π : ∀ i : I, Uᵢ i ⟶ U) :
    toSieve (ofArrows (fun i : ULift.{w₂} I ↦ Uᵢ i.down) fun i ↦ π i.down) =
      Sieve.ofArrows Uᵢ π := by
  -- The sieve comparison is just the generated-sieve image of the presieve comparison.
  simpa [toSieve, Sieve.ofArrows] using
    congrArg Sieve.generate (toPresieve_ofArrows_ulift Uᵢ π)

/-- A fixed-target family is covering for a precoverage precisely when the presieve it generates as
an indexed family belongs to that precoverage. This applies in particular to pretopologies. -/
abbrev IsCovering (K : Precoverage C) (𝒰 : Over.{w} U) : Prop :=
  toPresieve 𝒰 ∈ K U

/-- Definition 7.8.2 (1): in canonical form, two families of morphisms with fixed target `U` are
combinatorially equivalent when they determine the same presieve on `U`, equivalently when each
member of either family is literally one of the members of the other family after a reindexing. -/
def CombinatoriallyEquivalent
    (𝒰 𝒱 : Over.{w} U) : Prop :=
  toPresieve 𝒰 = toPresieve 𝒱

/-- Definition 7.8.2 (2): two families of morphisms with fixed target `U` are tautologically
equivalent if they admit reindexings in both directions whose component maps are isomorphisms in
the slice category `C / U`. -/
def TautologicallyEquivalent
    (𝒰 𝒱 : Over.{w} U) : Prop :=
  ∃ f : 𝒰 ⟶ 𝒱, ∃ g : 𝒱 ⟶ 𝒰,
    (∀ i : 𝒰.index, IsIso (f.f i)) ∧ ∀ j : 𝒱.index, IsIso (g.f j)

/-- Helper for Definition 7.8.2: rewrite the commutativity witness for an equality of slice
objects into the shape expected by `Over.isoMk`. -/
private theorem eqToIso_hom_comp_hom
    {A B : CategoryTheory.Over U}
    (hleft : B.left = A.left)
    (hhom : A.hom = eqToHom hleft.symm ≫ B.hom) :
    (eqToIso hleft.symm).hom ≫ B.hom = A.hom := by
  -- This is just the same triangle equation with the coercion from `eqToIso`.
  simpa using hhom.symm

/-- Helper for Definition 7.8.2: an equality of underlying slice arrows produces an isomorphism of
slice objects. -/
private def over_iso_of_left_eq_hom
    {A B : CategoryTheory.Over U}
    (hleft : B.left = A.left)
    (hhom : A.hom = eqToHom hleft.symm ≫ B.hom) :
    A ≅ B :=
  CategoryTheory.Over.isoMk (eqToIso hleft.symm) (eqToIso_hom_comp_hom hleft hhom)

/-- Helper for Definition 7.8.2: the previous witness recovers literal equality of slice objects. -/
private theorem over_obj_eq_of_left_eq_hom
    {A B : CategoryTheory.Over U}
    (hleft : B.left = A.left)
    (hhom : A.hom = eqToHom hleft.symm ≫ B.hom) :
    A = B := by
  -- Extensionality in the slice category reduces object equality to equality of domains and maps.
  simpa using
    (CostructuredArrow.obj_ext A B hleft.symm hhom.symm)

/-- Helper for Definition 7.8.2: equality of slice objects gives the `eqToHom` presentation needed
for `Presieve.ofArrows.mk'`. -/
private theorem over_hom_eq_eqToHom_comp_hom
    {A B : CategoryTheory.Over U} (h : A = B) :
    A.hom = eqToHom (congrArg (fun X : CategoryTheory.Over U ↦ X.left) h) ≫ B.hom := by
  -- After reducing to reflexivity, the statement becomes the trivial identity triangle.
  cases h
  simp

/-- Companion source-facing formulation of combinatorial equivalence: two fixed-target families are
combinatorially equivalent exactly when each is obtained from the other by reindexing its members
without changing the corresponding objects of the slice category. -/
theorem combinatoriallyEquivalent_iff_exists_reindexings
    {𝒰 𝒱 : Over.{w} U} :
    CombinatoriallyEquivalent 𝒰 𝒱 ↔
      ∃ α : 𝒰.index → 𝒱.index, ∃ β : 𝒱.index → 𝒰.index,
        (∀ i : 𝒰.index, 𝒰.obj i = 𝒱.obj (α i)) ∧
          ∀ j : 𝒱.index, 𝒱.obj j = 𝒰.obj (β j) := by
  constructor
  · intro h
    -- Equality of presieves lets us read off, for each component of `𝒰`, a matching component of
    -- `𝒱`, and conversely.
    have hα :
        ∀ i : 𝒰.index, ∃ j : 𝒱.index, 𝒰.obj i = 𝒱.obj j := by
      intro i
      have hi₀ : toPresieve 𝒰 ((𝒰.obj i).hom) := Presieve.ofArrows.mk i
      obtain ⟨j, hobj, hhom⟩ := Presieve.ofArrows_surj
        (fun j : 𝒱.index ↦ (𝒱.obj j).hom) ((𝒰.obj i).hom) (h.le _ _ hi₀)
      refine ⟨j, ?_⟩
      exact over_obj_eq_of_left_eq_hom hobj hhom
    have hβ :
        ∀ j : 𝒱.index, ∃ i : 𝒰.index, 𝒱.obj j = 𝒰.obj i := by
      intro j
      have hj₀ : toPresieve 𝒱 ((𝒱.obj j).hom) := Presieve.ofArrows.mk j
      obtain ⟨i, hobj, hhom⟩ := Presieve.ofArrows_surj
        (fun i : 𝒰.index ↦ (𝒰.obj i).hom) ((𝒱.obj j).hom) (h.ge _ _ hj₀)
      refine ⟨i, ?_⟩
      exact over_obj_eq_of_left_eq_hom hobj hhom
    choose α hα using hα
    choose β hβ using hβ
    exact ⟨α, β, hα, hβ⟩
  · rintro ⟨α, β, hα, hβ⟩
    -- The reindexing data shows that each generator on one side is literally a generator on the
    -- other side, so the presieves agree by antisymmetry.
    change toPresieve 𝒰 = toPresieve 𝒱
    apply le_antisymm
    · rw [Presieve.ofArrows_le_iff]
      intro i
      refine Presieve.ofArrows.mk' (α i) ?_ ?_
      · exact congrArg (fun X : CategoryTheory.Over U ↦ X.left) (hα i)
      · simpa using over_hom_eq_eqToHom_comp_hom (hα i)
    · rw [Presieve.ofArrows_le_iff]
      intro j
      refine Presieve.ofArrows.mk' (β j) ?_ ?_
      · exact congrArg (fun X : CategoryTheory.Over U ↦ X.left) (hβ j)
      · simpa using over_hom_eq_eqToHom_comp_hom (hβ j)

/-- Helper for Definition 7.8.2: a presieve witness gives an isomorphism on the corresponding
slice component. -/
private theorem over_hom_isIso_of_left_eq_hom
    {A B : CategoryTheory.Over U}
    (hleft : B.left = A.left)
    (hhom : A.hom = eqToHom hleft.symm ≫ B.hom) :
    IsIso (over_iso_of_left_eq_hom hleft hhom).hom := by
  -- The component map is the hom of an explicit slice isomorphism.
  infer_instance

/-- A presieve inclusion between fixed-target families yields a refinement whose components are
isomorphisms in the slice category. -/
private theorem exists_componentwiseIso_hom_of_toPresieve_le
    {𝒰 𝒱 : Over.{w} U} (h : toPresieve 𝒰 ≤ toPresieve 𝒱) :
    ∃ f : 𝒰 ⟶ 𝒱, ∀ i : 𝒰.index, IsIso (f.f i) := by
  classical
  -- For each component of `𝒰`, use the presieve inclusion to choose a matching component of `𝒱`.
  have hi :
      ∀ i : 𝒰.index,
        ∃ j : 𝒱.index,
          ∃ hobj : (𝒱.obj j).left = (𝒰.obj i).left,
            (𝒰.obj i).hom = eqToHom hobj.symm ≫ (𝒱.obj j).hom := by
    intro i
    exact Presieve.ofArrows_surj (fun j : 𝒱.index ↦ (𝒱.obj j).hom) ((𝒰.obj i).hom)
      (h _ _ (Presieve.ofArrows.mk i))
  choose α hαobj hαhom using hi
  refine ⟨
    { α := α
      f := fun i ↦ (over_iso_of_left_eq_hom (hαobj i) (hαhom i)).hom },
    ?_⟩
  intro i
  -- Each chosen component map is the hom of the explicit slice isomorphism above.
  exact over_hom_isIso_of_left_eq_hom (hαobj i) (hαhom i)

-- Proof sketch: a combinatorial equivalence is equality of the canonical presieves, so each
-- direction gives a refinement whose components are slice isomorphisms.
/-- Lemma 7.8.3 (1): combinatorially equivalent families of morphisms with fixed target are
tautologically equivalent. -/
theorem combinatoriallyEquivalent_implies_tautologicallyEquivalent
    {𝒰 𝒱 : Over.{w} U}
    (h : CombinatoriallyEquivalent 𝒰 𝒱) :
    TautologicallyEquivalent 𝒰 𝒱 := by
  -- Use the common presieve to build reindexing morphisms in both directions.
  rcases exists_componentwiseIso_hom_of_toPresieve_le h.le with ⟨f, hf⟩
  rcases exists_componentwiseIso_hom_of_toPresieve_le h.ge with ⟨g, hg⟩
  exact ⟨f, g, hf, hg⟩

/-- A morphism of fixed-target families induces inclusion of the generated sieves. -/
theorem toSieve_le_of_hom {𝒰 𝒱 : Over.{w} U} (φ : 𝒰 ⟶ 𝒱) :
    toSieve 𝒰 ≤ toSieve 𝒱 := by
  rw [toSieve, toSieve, Sieve.generate_le_iff, Presieve.ofArrows_le_iff]
  intro i
  -- Each generator of `𝒰` factors through the corresponding chosen generator of `𝒱`.
  refine ⟨_, (φ.f i).left, _, Presieve.ofArrows.mk (φ.α i), ?_⟩
  simpa using CategoryTheory.Over.w (φ.f i)

-- Proof sketch: a tautological equivalence supplies morphisms in both directions, and any
-- morphism of fixed-target families induces inclusion of the generated sieves.
/-- Tautologically equivalent fixed-target families generate the same sieve. -/
theorem toSieve_eq_of_tautologicallyEquivalent
    {𝒰 𝒱 : Over.{w} U} (h : TautologicallyEquivalent 𝒰 𝒱) :
    toSieve 𝒰 = toSieve 𝒱 := by
  -- Antisymmetry reduces the result to the two sieve inclusions coming from the comparison maps.
  rcases h with ⟨f, g, -, -⟩
  exact le_antisymm (toSieve_le_of_hom f) (toSieve_le_of_hom g)

end Over
end SemiRepresentableFamily

end CategoryTheory
