module

import Mathlib.Tactic.Recall
public import stacks_project.Chap07.Definition_7_8_2

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe v u

namespace CategoryTheory

variable {C : Type u} [Category.{v} C]

/- Domain-style sampling for Definition 7.47.3:
- primary domain: sieves generated by fixed-target families in a category;
- sampled owner abstractions:
  `SemiRepresentableFamily.Over`,
  `SemiRepresentableFamily.Over.toSieve`,
  `CategoryTheory.Sieve.ofArrows`,
  `CategoryTheory.Sieve.mem_ofArrows_iff`;
- source-facing layer: the sieve generated by a family of arrows with common target `U`;
- core/canonical owner: `Sieve U`;
- bridge/view layer: `SemiRepresentableFamily.Over.toSieve`, with indexed-family presentation
  `(ofArrows Y f).toSieve = Sieve.ofArrows Y f`.

Primitive data are the fixed-target family itself. The generated sieve is derived data, already
owned in the chapter by `SemiRepresentableFamily.Over.toSieve`; `Sieve.ofArrows` is the underlying
mathlib presentation when the family is given by an explicit index type.
-/

/- Definition 7.47.3: for a family of morphisms with common target `U`, the generated sieve is the
canonical chapter-level bridge `SemiRepresentableFamily.Over.toSieve`; for the indexed family
`ofArrows Y f`, this is definitionally `Sieve.ofArrows Y f`. -/
recall SemiRepresentableFamily.Over.toSieve

/- Companion recall: in the indexed presentation, an arrow `g : W ⟶ U` lies in the generated sieve
if and only if it factors through one of the generating morphisms. -/
recall Sieve.mem_ofArrows_iff

end CategoryTheory
