module

public import Mathlib.CategoryTheory.Action.Concrete
public import Mathlib.CategoryTheory.Action.Limits
public import Mathlib.CategoryTheory.Sites.JointlySurjective
public import Mathlib.CategoryTheory.Sites.PrecoverageToGrothendieck
public import Mathlib.CategoryTheory.Sites.Sheafification
public import Mathlib.CategoryTheory.Sites.Sheaf


@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory

universe u

/- Domain-style sampling for Example 7.6.5:
- primary domain: source-facing sites presented by a `Precoverage`, specialized to the category
  `Action (Type u) G` of universe-sized `G`-sets;
- sampled owner API:
  `CategoryTheory.Precoverage`,
  `Types.jointlySurjectivePrecoverage`,
  `Presieve.mem_comap_jointlySurjectivePrecoverage_iff`,
  `Scheme.jointlySurjectivePrecoverage` / `Scheme.jointlySurjectiveTopology`;
- best owner abstraction: the primitive owner is the pulled-back jointly surjective
  `Precoverage`; the Grothendieck topology is derived from that owner by
  `Precoverage.toGrothendieck`, so it should not be stored as independent primitive data;
- source/core/bridge triage:
  `source-facing`: the jointly surjective covering families on `G`-sets and the associated site;
  `core/canonical`: `Precoverage` and `Precoverage.toGrothendieck`;
  `bridge/view`: the pointwise topology-membership characterization below.

This refinement follows the existing mathlib owner pattern for surjective sites by placing the
`G`-set site in the `Action` namespace, deleting the file-local `tG...` wrappers, and exposing the
primitive precoverage first and the derived topology second.
-/

namespace Action

section

variable (G : Type u) [Group G]

/- Example 7.6.5: the source first replaces the proper-class category `G-Sets` by a
size-restricted full subcategory `G-Sets_α`, then equips it with the jointly surjective
coverings. In Lean the universe-sized category `Action (Type u) G` is the corresponding
size-restricted category of `G`-sets, and the pulled-back jointly surjective precoverage is the
canonical restricted covering class from which the site is generated. -/

/-- The primitive covering families for Example 7.6.5: presieves on the universe-sized category
of `G`-sets whose underlying maps are jointly surjective. This is the source-facing owner
abstraction; the Grothendieck topology is derived from it. -/
abbrev jointlySurjectivePrecoverage : Precoverage (Action (Type u) G) :=
  Types.jointlySurjectivePrecoverage.comap (Action.forget (Type u) G)

/-- Example 7.6.5: the site `\mathcal T_G` on `G`-sets is the Grothendieck topology generated by
jointly surjective families of equivariant maps, modeled in Lean on the universe-sized category
`Action (Type u) G`. -/
abbrev jointlySurjectiveTopology : GrothendieckTopology (Action (Type u) G) :=
  (jointlySurjectivePrecoverage G).toGrothendieck

-- Proof sketch: the Grothendieck topology generated by `jointlySurjectivePrecoverage` is
-- covering exactly when the sieve contains a jointly surjective family, and the canonical comap
-- theorem identifies those families pointwise.
/-- A sieve on a `G`-set is covering for `\mathcal T_G` exactly when its arrows are jointly
surjective on the underlying set. -/
theorem mem_jointlySurjectiveTopology_iff
    {X : Action (Type u) G} {R : Sieve X} :
    R ∈ jointlySurjectiveTopology G X ↔
      ∀ x : X.V, ∃ (Y : Action (Type u) G) (f : Y ⟶ X), R f ∧ x ∈ Set.range f.hom :=
  by
    -- Reduce Grothendieck-topology membership to the existence of a covering presieve below `R`.
    rw [Precoverage.mem_toGrothendieck_iff_of_isStableUnderComposition
      (J := jointlySurjectivePrecoverage G) (S := R)]
    constructor
    · rintro ⟨R₀, hR₀, hR₀R⟩ x
      -- Convert the covering presieve witness into the pointwise jointly surjective formulation.
      have hsurj :
          ∀ x : X.V, ∃ (Y : Action (Type u) G) (f : Y ⟶ X), R₀ f ∧ x ∈ Set.range f.hom := by
        simpa [jointlySurjectivePrecoverage, Action.forget_obj, Action.forget_map] using
          (Presieve.mem_comap_jointlySurjectivePrecoverage_iff
            (F := Action.forget (Type u) G) (X := X) (R := R₀)).1 hR₀
      -- Enlarge the jointly surjective subfamily from `R₀` to the ambient sieve `R`.
      rcases hsurj x with ⟨Y, f, hf, hx⟩
      exact ⟨Y, f, hR₀R Y f hf, hx⟩
    · intro hR
      -- The sieve itself is already jointly surjective, so it can serve as the covering witness.
      refine ⟨R, ?_, le_rfl⟩
      simpa [jointlySurjectivePrecoverage, Action.forget_obj, Action.forget_map] using
        (Presieve.mem_comap_jointlySurjectivePrecoverage_iff
          (F := Action.forget (Type u) G) (X := X) (R := R)).2 hR

end

end Action
