module

public import Mathlib.CategoryTheory.Sites.Coverage
import Mathlib.Tactic.Recall

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

namespace CategoryTheory

variable {C : Type u} [Category.{v} C]

/- Domain-style sampling for Lemma 7.48.1:
- primary domain: sites presented by a coverage and the induced Grothendieck topology;
- sampled owner API:
  `Coverage.toGrothendieck`,
  `GrothendieckTopology.toCoverage`,
  `Coverage.toGrothendieck_eq_sInf`,
  `Presieve.isSheaf_coverage`;
- source/core/bridge triage:
  `source-facing`: the passage from covering families to the generated topology, together with the
  sheaf condition stated directly for those covering families;
  `core/canonical`: `Coverage.toGrothendieck` and `Presieve.isSheaf_coverage`;
  `bridge/view`: `GrothendieckTopology.toCoverage` and `Coverage.toGrothendieck_eq_sInf`, which
  compare the coverage presentation with the ambient Grothendieck-topology lattice.

Primitive data are only the coverage `K` and the set-valued presheaf `F`. The generated topology
and the coverage-level sheaf criterion are derived canonical API from the owner abstraction
`Coverage`, so this file should stay at direct recall/use rather than introducing a parallel local
definition or wrapper theorem.
-/

/- Lemma 7.48.1 (part 1): the covering sieves generated by the covering families of a site form
the canonical Grothendieck topology `K.toGrothendieck`. -/
recall Coverage.toGrothendieck

/- Lemma 7.48.1 (part 2): a set-valued presheaf is a sheaf for the topology generated by the
covering families of the site if and only if it satisfies the sheaf condition for every covering
family of the site. This is the canonical mathlib theorem `Presieve.isSheaf_coverage`. -/
recall Presieve.isSheaf_coverage

end CategoryTheory
