module

public import Mathlib.CategoryTheory.Sites.Sieves
import Mathlib.Tactic.Recall

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe v u w

namespace CategoryTheory

variable {C : Type u} [Category.{v} C]

/- Domain-style sampling for Lemma 7.47.2:
- primary domain: sieves on a fixed object in a category;
- sampled canonical declarations:
  `CategoryTheory.Sieve`,
  `CategoryTheory.Sieve.instCompleteLattice`,
  `CategoryTheory.Sieve.ofArrows`,
  `CategoryTheory.Sieve.ofArrows_mk`,
  `CategoryTheory.Sieve.generate_le_iff`,
  `CategoryTheory.Presieve.ofArrows_le_iff`,
  `CategoryTheory.Sieve.sSup_apply`,
  `CategoryTheory.Sieve.sInf_apply`,
  `CategoryTheory.Sieve.bot_apply`;
- layer triage for this item:
  `source-facing`: the poset/lattice of sieves on `U`;
  `core/canonical`: `Sieve U` with its upstream `CompleteLattice` instance;
  `bridge/view`: the pointwise characterizations of arbitrary joins and meets by
  `Sieve.sSup_apply` and `Sieve.sInf_apply`, the sieve `Sieve.ofArrows` generated by a family of
  arrows, and the extreme sieves `⊤` and `⊥`.

Primitive data are only the object `U`. Arbitrary unions, intersections, top, and bottom are
already packaged by the canonical complete-lattice owner, and the smallest sieve generated by a
family of arrows is already the canonical owner `Sieve.ofArrows`. This file should therefore recall
those owners directly and expose only the exact upstream pointwise companion lemmas for joins,
meets, the generated sieve, and the extreme sieves.
-/

variable (U : C)

/- Lemma 7.47.2: the sieves on `U` form a complete lattice under inclusion; in particular,
arbitrary unions and intersections are sieves, every family of arrows into `U` generates a unique
smallest sieve, and the maximal and minimal sieves are `⊤` and `⊥`. -/
recall Sieve.instCompleteLattice : CompleteLattice (Sieve U)

/- Companion recall: an arrow lies in the supremum of a set of sieves exactly when it lies in one
of them, so arbitrary unions of sieves are again sieves. -/
recall Sieve.sSup_apply

/- Companion recall: an arrow lies in the infimum of a set of sieves exactly when it lies in every
member, so arbitrary intersections of sieves are again sieves. -/
recall Sieve.sInf_apply

/- Companion recall: the canonical sieve on `U` generated by a family of arrows into `U` is
`Sieve.ofArrows`. -/
recall Sieve.ofArrows

/- Companion recall: each displayed arrow of a generating family belongs to the sieve generated by
that family. -/
recall Sieve.ofArrows_mk

/- Companion recall: the maximal sieve on `U` is the top element `⊤`, containing every arrow into
`U`. -/
recall Sieve.top_apply

/- Companion recall: the minimal sieve on `U` is the bottom element `⊥`, containing no arrows into
`U`. -/
recall Sieve.bot_apply

namespace Sieve

/-- The sieve generated by a family of arrows into `U` is the unique smallest sieve on `U`
containing every displayed arrow. -/
-- Proof sketch: `Sieve.ofArrows_mk` puts each generator into `Sieve.ofArrows Y f`. If `S` is any
-- sieve on `U` containing every `f i`, then `Presieve.ofArrows_le_iff` shows the underlying
-- presieve of the family is contained in `S`, and `Sieve.generate_le_iff` upgrades this to
-- `Sieve.ofArrows Y f ≤ S`; uniqueness is then the order-theoretic uniqueness of a least element.
theorem ofArrows_isLeast {I : Type w} (Y : I → C) (f : ∀ i, Y i ⟶ U) :
    IsLeast { S : Sieve U | ∀ i, S (f i) } (Sieve.ofArrows Y f) := by
  refine ⟨?_, ?_⟩
  · -- Each generator belongs to the sieve generated by the family.
    intro i
    exact Sieve.ofArrows_mk Y f i
  · -- Any sieve containing every generator also contains the generated sieve.
    intro S hS
    rw [Sieve.ofArrows, Sieve.generate_le_iff, Presieve.ofArrows_le_iff]
    exact hS

end Sieve
end CategoryTheory
