module

public import Mathlib.CategoryTheory.Sites.Sheafification
public import Mathlib.CategoryTheory.Sites.Sheaf
public import stacks_project.Chap07.Definition_7_13_1
public import stacks_project.Chap07.Situation_7_18_1
public import stacks_project.Chap07.Lemma_7_18_2.ColimitCategory

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe uI uC vC

open CategoryTheory
open CategoryTheory.Limits
open Opposite

noncomputable section

/- Domain-style sampling for Lemma 7.18.2 (refactored):
- primary domain: the colimit site of a cofiltered inverse system of sites, constructed
  explicitly as in the source text;
- sampled owner API:
  `CategoryTheory.Precoverage`,
  `CategoryTheory.Precoverage.HasIsos`,
  `CategoryTheory.Precoverage.HasPullbacks`,
  `CategoryTheory.Precoverage.IsStableUnderBind`,
  `CategoryTheory.Precoverage.IsStableUnderPullbackArrows`,
  `CategoryTheory.Functor.IsContinuousSiteFunctor`;
- source/core/bridge triage:
  `source-facing`: the explicit colimit category `S.ColimitCategory` (built in the proof-support
  file `Lemma_7_18_2/ColimitCategory.lean` exactly as in the source: objects and arrows are the
  colimits of the stage objects and arrows) and the covering families
  `\text{Cov}(\mathcal C) = \bigcup u_i(\text{Cov}(\mathcal C_i))`;
  `core/canonical`: the literal Stacks site axioms on `Precoverage` from Situation 7.18.1;
  `bridge/view`: the generated Grothendieck topology `colimitTopology` and the topology-level
  continuity of the cocone functors.

Route correction relative to the previous encoding: the lemma is now stated for the explicit
colimit category instead of an abstract `colimit` in `Cat`. The abstract form is unprovable at
this universe generality (a `Cat.{vC, uC}`-colimit of `B`-groupoids of finite alternating groups
over a `vC⁺`-sized cofiltered index can be the terminal category, refuting the Hom-colimit
formula), and the mathlib classes `IsStableUnderComposition`/`IsStableUnderBaseChange` are false
for finite-covering precoverages because they allow arbitrary re-indexing with repetitions; the
faithful axioms (2) and (3) are stated in `Presieve.bind` and pullback form, as in
Definition 7.6.2. -/

namespace CofilteredSiteDiagram

variable (S : CofilteredSiteDiagram.{uI, uC, vC})

/-- The image on the colimit category of a stage covering family, after identifying its target
with an arbitrary colimit object `x`. This is the building block of the source-text covering
set `\text{Cov}(\mathcal C)`. -/
def stageCover {x : S.ColimitCategory} (i : S.I) (X : S.stage i)
    (hX : S.ιObj i X = x) (R : Presieve X) : Presieve x :=
  hX ▸ (R.map (S.stageCoconeFunctor i))

theorem stageCover_rfl_eq_map (i : S.I) (X : S.stage i) (R : Presieve X) :
    S.stageCover i X rfl R = R.map (S.stageCoconeFunctor i) :=
  rfl

/-- Membership in a transported image covering family. -/
theorem stageCover_apply_iff {x : S.ColimitCategory} (i : S.I) (X : S.stage i)
    (hX : S.ιObj i X = x) (R : Presieve X) {Z : S.ColimitCategory} (t : Z ⟶ x) :
    S.stageCover i X hX R t ↔ (R.map (S.stageCoconeFunctor i)) (t ≫ eqToHom hX.symm) := by
  subst hX
  rw [S.stageCover_rfl_eq_map]
  have hid : t ≫ eqToHom (Eq.symm (rfl : S.ιObj i X = S.ιObj i X)) = t := by
    have hp : Eq.symm (rfl : S.ιObj i X = S.ιObj i X) = rfl := rfl
    rw [hp, eqToHom_refl, Category.comp_id]
  exact (iff_of_eq (congrArg
    (fun w : Z ⟶ S.ιObj i X => Presieve.map (S.stageCoconeFunctor i) R w) hid)).symm

/-- Lemma 7.18.2, the covering families: `\text{Cov}(\mathcal C)` is the union of the images of
the chosen stage covering families under the cocone functors
`u_i : \mathcal C_i \to \mathop{\mathrm{colim}} \mathcal C_i`. -/
def colimitSite : Precoverage (S.ColimitCategory) where
  coverings x := {T | ∃ (i : S.I) (X : S.stage i) (hX : S.ιObj i X = x) (R : Presieve X),
    R ∈ S.stageCov i X ∧ S.stageCover i X hX R = T}

/-- Any stage covering family becomes a covering family in the colimit site after applying the
corresponding cocone functor. -/
theorem map_mem_colimitSite (i : S.I) {X : S.stage i} {R : Presieve X}
    (hR : R ∈ S.stageCov i X) :
    R.map (S.stageCoconeFunctor i) ∈ S.colimitSite (S.ιObj i X) :=
  ⟨i, X, rfl, R, hR, S.stageCover_rfl_eq_map i X R⟩

/-- The cocone functors are continuous at the level of the chosen covering families: this is the
cover-preservation half of Definition 7.13.1 for `u_i`. -/
theorem stageCov_le_comap (i : S.I) :
    S.stageCov i ≤ S.colimitSite.comap (S.stageCoconeFunctor i) := by
  intro X R hR
  exact S.map_mem_colimitSite i hR

/-- The Grothendieck topology on the colimit category generated by the colimit-site covering
families. -/
def colimitTopology : GrothendieckTopology (S.ColimitCategory) :=
  S.colimitSite.toGrothendieck

/-- Each cocone functor from a stage site into the colimit site is cover-preserving for the
generated Grothendieck topologies. -/
theorem colimitTopology_coverPreserving (i : S.I) :
    CoverPreserving (S.stageTopology i) S.colimitTopology (S.stageCoconeFunctor i) := by
  constructor
  intro U T hT
  obtain ⟨R, hR, hle⟩ := Precoverage.exists_mem_generate_le_of_mem_toGrothendieck hT
  apply S.colimitTopology.superset_covering
    (Sieve.functorPushforward_monotone (S.stageCoconeFunctor i) U
      ((Sieve.giGenerate.gc R T).2 (by
        intro Z g hg
        exact hle _ ⟨Z, 𝟙 Z, g, hg, Category.id_comp g⟩)))
  rw [← Sieve.generate_map_eq_functorPushforward]
  exact Precoverage.generate_mem_toGrothendieck (S.map_mem_colimitSite i hR)

/-- Lemma 7.18.2 (5): the generated colimit topology is the smallest Grothendieck topology on the
colimit category for which every cocone functor from a stage site is cover-preserving. -/
theorem colimitTopology_isLeast :
    IsLeast
      {Jc : GrothendieckTopology (S.ColimitCategory) |
        ∀ i : S.I, CoverPreserving (S.stageTopology i) Jc (S.stageCoconeFunctor i)}
      S.colimitTopology := by
  refine ⟨S.colimitTopology_coverPreserving, ?_⟩
  intro Jc hJc
  rw [colimitTopology, Precoverage.toGrothendieck_le_iff_le_toPrecoverage]
  rintro x T ⟨i, X, hX, R, hR, rfl⟩
  subst hX
  rw [GrothendieckTopology.mem_toPrecoverage_iff, S.stageCover_rfl_eq_map]
  change Sieve.generate (Presieve.map (S.stageCoconeFunctor i) R) ∈
    Jc ((S.stageCoconeFunctor i).obj X)
  rw [Sieve.generate_map_eq_functorPushforward]
  exact (hJc i).cover_preserve (Precoverage.generate_mem_toGrothendieck hR)

section SiteAxioms

/-- Transporting a singleton presieve along an object identification composes the arrow with the
corresponding transport. -/
theorem singleton_transport {C : Type*} [Category C] {X X' Z : C} (h : X = X') (f : Z ⟶ X) :
    h ▸ Presieve.singleton f = Presieve.singleton (f ≫ eqToHom h) := by
  subst h; simp

/-- Singleton presieves with equal arrow images are equal. -/
theorem singleton_eq_of_arrowMk {C : Type*} [Category C] {X : C} {Y Z : C}
    {f : Y ⟶ X} {g : Z ⟶ X} (h : Arrow.mk f = Arrow.mk g) :
    Presieve.singleton f = Presieve.singleton g := by
  obtain ⟨h₁, h₂, hf⟩ := (arrowMk_eq_iff _ _).1 h
  subst h₁
  simp only [eqToHom_refl, Category.id_comp, Category.comp_id] at hf
  rw [hf]

/-- Membership constructor for singleton coverings of the colimit site: any morphism whose arrow
image agrees with the image of a stage isomorphism is a singleton covering. -/
theorem singleton_mem_colimitSite {i : S.I} {W X : S.stage i} (g₀ : W ⟶ X) [IsIso g₀]
    {x : S.ColimitCategory} (hX : S.ιObj i X = x) {Z : S.ColimitCategory} {f : Z ⟶ x}
    (harr : Arrow.mk f = Arrow.mk ((S.stageCoconeFunctor i).map g₀ ≫ eqToHom hX)) :
    Presieve.singleton f ∈ S.colimitSite x := by
  subst hX
  refine ⟨i, X, rfl, Presieve.singleton g₀, Precoverage.mem_coverings_of_isIso g₀, ?_⟩
  rw [S.stageCover_rfl_eq_map, Presieve.map_singleton]
  refine (singleton_eq_of_arrowMk (harr.trans (arrowMk_comp_eqToHom _ _))).symm

/-- Lemma 7.18.2 (1): the colimit covering families contain the singleton isomorphisms, as
required by axiom (1) of Definition 7.6.2. The source omits this proof; it descends an
isomorphism and its inverse to a common stage where the two inverse identities already hold. -/
instance colimitSite_hasIsos : S.colimitSite.HasIsos := by
  constructor
  intro x y f hf
  haveI := hf
  obtain ⟨i₀, X₀, hX₀⟩ := S.ιObj_surjective x
  obtain ⟨j₀, Y₀, hY₀⟩ := S.ιObj_surjective y
  subst hX₀; subst hY₀
  obtain ⟨k, a, b, g, hg⟩ := exists_hom_rep f
  rw [mk_eq_eqToHom_comp] at hg
  -- The cocone image of the descended representative is an isomorphism.
  have hf' := hf
  rw [hg] at hf'
  haveI := hf'
  haveI h2 : IsIso ((S.stageCoconeFunctor k).map g ≫ eqToHom (S.ιObj_lower b Y₀)) :=
    @IsIso.of_isIso_comp_left _ _ _ _ _ (eqToHom (S.ιObj_lower a X₀).symm) _ inferInstance hf'
  haveI h3 : IsIso ((S.stageCoconeFunctor k).map g) :=
    @IsIso.of_isIso_comp_right _ _ _ _ _ _ (eqToHom (S.ιObj_lower b Y₀)) inferInstance h2
  -- Descend the isomorphism property to a stage below `k`.
  obtain ⟨l, c, hgiso⟩ := exists_stageFunctor_map_isIso g
  haveI := hgiso
  -- Present the singleton covering from the lowered stage isomorphism.
  have hstrip : Arrow.mk f = Arrow.mk ((S.stageCoconeFunctor k).map g) := by
    refine (congrArg (fun t => Arrow.mk t) hg).trans ?_
    exact (arrowMk_eqToHom_comp _ _).trans (arrowMk_comp_eqToHom _ _)
  refine S.singleton_mem_colimitSite ((S.stageFunctor c).map g)
    ((S.ιObj_lower c ((S.stageFunctor b).obj Y₀)).trans (S.ιObj_lower b Y₀)) ?_
  refine hstrip.trans ?_
  refine (S.arrowMk_cocone_map_lower c g).trans ?_
  exact (arrowMk_comp_eqToHom _ _).symm

/-- Transport preserves membership in a precoverage. -/
theorem transport_mem_stageCov {m : S.I} {A B : S.stage m} (h : A = B) {P : Presieve A}
    (hP : P ∈ S.stageCov m A) : (h ▸ P : Presieve B) ∈ S.stageCov m B := by
  subst h
  exact hP

/-- Lemma 7.18.2 (2): the colimit covering families are stable under per-arrow refinement, as in
axiom (2) of Definition 7.6.2. The source proof synchronizes the finitely many participating
stages first and applies the stage axiom there. -/
instance colimitSite_isStableUnderBind : S.colimitSite.IsStableUnderBind := by
  constructor
  rintro x T ⟨l, X', hX', R', hR', rfl⟩ T' hT'
  subst hX'
  -- The image members of the outer covering family.
  have hmem : ∀ ω : R'.uncurry, S.stageCover l X' rfl R'
      ((S.stageCoconeFunctor l).map ω.1.2) := by
    intro ω
    rw [S.stageCover_rfl_eq_map]
    exact Presieve.map.of ω.2
  -- Choose inner presentations canonically, indexed by the image members themselves.
  choose iF XF hXF RF hRF hpres using
    fun s : (S.stageCover l X' rfl R').uncurry => hT' s.2
  -- The canonical image pair attached to an outer member datum.
  let σm : R'.uncurry → (S.stageCover l X' rfl R').uncurry :=
    fun ω => ⟨⟨_, (S.stageCoconeFunctor l).map ω.1.2⟩, hmem ω⟩
  -- Align the inner bases with the outer sources at common stages.
  choose kF αF βF halF using fun ω : R'.uncurry =>
    S.ιObj_exact ((hXF (σm ω)) : S.ιObj (iF (σm ω)) (XF (σm ω)) = S.ιObj l ω.1.1)
  -- One common refinement of `l` and all the alignment stages.
  haveI : Finite R'.uncurry :=
    ((Precoverage.mem_finite_iff).1 (S.stageCov_finite hR')).to_subtype
  classical
  haveI : Finite (WidePullbackShape R'.uncurry) :=
    inferInstanceAs (Finite (Option R'.uncurry))
  obtain ⟨c⟩ := IsCofiltered.cone_nonempty
    (WidePullbackShape.wideCospan l kF βF)
  have hπ : ∀ ω : R'.uncurry, c.π.app (some ω) ≫ βF ω = c.π.app none := by
    intro ω
    simpa using (c.π.naturality (WidePullbackShape.Hom.term ω)).symm
  -- The lowered outer covering family.
  have hRout : R'.map (S.stageFunctor (c.π.app none)) ∈
      S.stageCov c.pt ((S.stageFunctor (c.π.app none)).obj X') :=
    (S.stageFunctor_isContinuousSiteFunctor (c.π.app none)).toLeComap _ hR'
  -- The lowered inner covering families, transported onto the lowered outer sources.
  have hRin : ∀ ω : R'.uncurry,
      (RF (σm ω)).map (S.stageFunctor (c.π.app (some ω) ≫ αF ω)) ∈
        S.stageCov c.pt ((S.stageFunctor (c.π.app (some ω) ≫ αF ω)).obj (XF (σm ω))) :=
    fun ω => (S.stageFunctor_isContinuousSiteFunctor _).toLeComap _ (hRF (σm ω))
  have hbase : ∀ ω : R'.uncurry,
      (S.stageFunctor (c.π.app (some ω) ≫ αF ω)).obj (XF (σm ω)) =
        (S.stageFunctor (c.π.app none)).obj ω.1.1 := by
    intro ω
    calc (S.stageFunctor (c.π.app (some ω) ≫ αF ω)).obj (XF (σm ω))
        = (S.stageFunctor (c.π.app (some ω))).obj
            ((S.stageFunctor (αF ω)).obj (XF (σm ω))) :=
          (S.stageFunctor_obj_comp (αF ω) (c.π.app (some ω)) (XF (σm ω))).symm
      _ = (S.stageFunctor (c.π.app (some ω))).obj ((S.stageFunctor (βF ω)).obj ω.1.1) := by
          rw [halF ω]
      _ = (S.stageFunctor (c.π.app (some ω) ≫ βF ω)).obj ω.1.1 :=
          S.stageFunctor_obj_comp (βF ω) (c.π.app (some ω)) ω.1.1
      _ = (S.stageFunctor (c.π.app none)).obj ω.1.1 :=
          congrArg (fun t : c.pt ⟶ l => (S.stageFunctor t).obj ω.1.1) (hπ ω)
  -- Choose, for each lowered outer member, a matching outer member datum.
  have memElim : ∀ ⦃Y : S.stage c.pt⦄ ⦃f' : Y ⟶ (S.stageFunctor (c.π.app none)).obj X'⦄,
      (R'.map (S.stageFunctor (c.π.app none))) f' → ∃ ω : R'.uncurry,
        Arrow.mk f' = Arrow.mk ((S.stageFunctor (c.π.app none)).map ω.1.2) := by
    intro Y f' hf'
    obtain ⟨W, g, hg, harr⟩ := map_apply_elim (S.stageFunctor (c.π.app none)) hf'
    exact ⟨⟨⟨W, g⟩, hg⟩, harr⟩
  -- The stage-level refinement: bind the lowered outer family with the transported lowered
  -- inner families.
  refine ⟨c.pt, (S.stageFunctor (c.π.app none)).obj X', S.ιObj_lower (c.π.app none) X',
    (R'.map (S.stageFunctor (c.π.app none))).bind
      (fun Y f' hf' =>
        (show (S.stageFunctor (c.π.app none)).obj ((memElim hf').choose).1.1 = Y from
          (congrArg Comma.left (memElim hf').choose_spec).symm) ▸
          ((hbase (memElim hf').choose) ▸ ((RF (σm (memElim hf').choose)).map
            (S.stageFunctor (c.π.app (some (memElim hf').choose) ≫
              αF (memElim hf').choose))))),
    Precoverage.bind_mem hRout _
      (fun Y f' hf' => S.transport_mem_stageCov _ (S.transport_mem_stageCov _ (hRin _))), ?_⟩
  -- The image of the stage-level bind is the colimit-level bind.
  funext Z₀
  funext h
  apply propext
  constructor
  · -- Every image of a stage-level bind member is a colimit-level bind member.
    intro hL
    rw [S.stageCover_apply_iff] at hL
    obtain ⟨Q, q, hq, harrH⟩ := map_apply_elim (S.stageCoconeFunctor c.pt) hL
    have hZ₀ : Z₀ = (S.stageCoconeFunctor c.pt).obj Q := congrArg Comma.left harrH
    subst hZ₀
    have hh2 : h = (S.stageCoconeFunctor c.pt).map q ≫
        eqToHom (S.ιObj_lower (c.π.app none) X') := by
      rw [← eq_of_arrowMk_eq harrH]
      exact (comp_eqToHom_symm_comp_self _ _).symm
    obtain ⟨Y₁, t, f', hf', ht, rfl⟩ := hq
    set ωc := (memElim hf').choose with hωcdef
    obtain ⟨hY₁, hX₂, hf'c⟩ := (arrowMk_eq_iff _ _).1 (memElim hf').choose_spec
    have hf'2 : f' = eqToHom hY₁ ≫ (S.stageFunctor (c.π.app none)).map ωc.1.2 := by
      have hf'3 : f' = eqToHom hY₁ ≫
          (S.stageFunctor (c.π.app none)).map ωc.1.2 ≫ 𝟙 _ := hf'c
      rw [Category.comp_id] at hf'3
      exact hf'3
    have ht1 := (presieve_transport_apply _ _ _).mp ht
    have ht2 := (presieve_transport_apply _ _ _).mp ht1
    obtain ⟨V, r, hr, harrT⟩ := map_apply_elim _ ht2
    have hQ : Q = (S.stageFunctor (c.π.app (some ωc) ≫ αF ωc)).obj V :=
      congrArg Comma.left harrT
    subst hQ
    refine ⟨_, eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
        (S.stageCoconeFunctor (iF (σm ωc))).map r ≫ eqToHom (hXF (σm ωc)),
      (S.stageCoconeFunctor l).map ωc.1.2, hmem ωc, ?_, ?_⟩
    · -- The inner factor is a member of the inner covering family.
      have hg₀ : S.stageCover (iF (σm ωc)) (XF (σm ωc)) (hXF (σm ωc)) (RF (σm ωc))
          (eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
            (S.stageCoconeFunctor (iF (σm ωc))).map r ≫ eqToHom (hXF (σm ωc))) := by
        rw [S.stageCover_apply_iff]
        refine mem_of_arrowMk_eq _ ?_ (Presieve.map.of hr)
        refine (congrArg (fun u => Arrow.mk u) (conj_unsymm _ _ _)).trans ?_
        exact arrowMk_eqToHom_comp _ _
      exact hpres (σm ωc) ▸ hg₀
    · -- The composite equation: flatten both sides to the canonical four-factor form.
      rw [hh2]
      -- Flatten the constructed side.
      have hflatL : (eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
            (S.stageCoconeFunctor (iF (σm ωc))).map r ≫ eqToHom (hXF (σm ωc))) ≫
            (S.stageCoconeFunctor l).map ωc.1.2 =
          eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
            (S.stageCoconeFunctor (iF (σm ωc))).map r ≫ eqToHom (hXF (σm ωc)) ≫
            (S.stageCoconeFunctor l).map ωc.1.2 :=
        conj_assoc₄ _ _ _ _
      -- Flatten the image side.
      obtain ⟨p₁, p₂, hconj⟩ := (arrowMk_eq_iff _ _).1 harrT
      have ht3 := eq_of_comp_comp_eqToHom _ _ hconj
      have ht4 : t = eqToHom p₁ ≫
          (S.stageFunctor (c.π.app (some ωc) ≫ αF ωc)).map r ≫
          eqToHom ((p₂.symm.trans (hbase ωc)).trans
            ((congrArg Comma.left (memElim hf').choose_spec).symm)) :=
        ht3.trans (conj_flat_right₂ _ _ _ _ _)
      have hcl := conj_of_conj
        (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V).symm
        (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) (XF (σm ωc)))
        (S.stageCoconeFunctor_map_lower (i := iF (σm ωc)) (k := c.pt)
          (c.π.app (some ωc) ≫ αF ωc) r)
      have hlow := conj_of_conj
        (S.ιObj_lower (c.π.app none) ωc.1.1).symm
        (S.ιObj_lower (c.π.app none) X')
        (S.stageCoconeFunctor_map_lower (i := l) (k := c.pt) (c.π.app none) ωc.1.2)
      -- the lowered inner core
      have hmt : (S.stageCoconeFunctor c.pt).map t =
          eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
            (S.stageCoconeFunctor (iF (σm ωc))).map r ≫
            eqToHom ((S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc)
                (XF (σm ωc))).symm.trans
              ((congrArg (fun A => S.ιObj c.pt A) (hbase ωc)).trans
                (congrArg (fun A => S.ιObj c.pt A)
                  ((congrArg Comma.left (memElim hf').choose_spec).symm)))) := by
        calc (S.stageCoconeFunctor c.pt).map t
            = (eqToHom (congrArg (fun A => S.ιObj c.pt A) p₁) ≫
                (S.stageCoconeFunctor c.pt).map
                  ((S.stageFunctor (c.π.app (some ωc) ≫ αF ωc)).map r) ≫
                eqToHom (congrArg (fun A => S.ιObj c.pt A)
                  ((p₂.symm.trans (hbase ωc)).trans
                    ((congrArg Comma.left (memElim hf').choose_spec).symm))) :
                (S.stageCoconeFunctor c.pt).obj ((S.stageFunctor (c.π.app (some ωc) ≫ αF ωc)).obj V) ⟶ (S.stageCoconeFunctor c.pt).obj Y₁) := by
              rw [ht4]
              exact map_conj_distrib (S.stageCoconeFunctor c.pt) _ _ _
          _ = (eqToHom (congrArg (fun A => S.ιObj c.pt A) p₁) ≫
                (eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
                  (S.stageCoconeFunctor (iF (σm ωc))).map r ≫
                  eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc)
                    (XF (σm ωc))).symm) ≫
                eqToHom (congrArg (fun A => S.ιObj c.pt A)
                  ((p₂.symm.trans (hbase ωc)).trans
                    ((congrArg Comma.left (memElim hf').choose_spec).symm))) :
                (S.stageCoconeFunctor c.pt).obj ((S.stageFunctor (c.π.app (some ωc) ≫ αF ωc)).obj V) ⟶ (S.stageCoconeFunctor c.pt).obj Y₁) := by
              exact congrArg (fun w => eqToHom (congrArg (fun A => S.ιObj c.pt A) p₁) ≫
                w ≫ eqToHom (((congrArg (fun A => S.ιObj c.pt A) p₂.symm).trans
                  (congrArg (fun A => S.ιObj c.pt A) (hbase ωc))).trans
                  (congrArg (fun A => S.ιObj c.pt A)
                    ((congrArg Comma.left (memElim hf').choose_spec).symm)))) hcl
          _ = (eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
                (S.stageCoconeFunctor (iF (σm ωc))).map r ≫
                eqToHom ((S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc)
                    (XF (σm ωc))).symm.trans
                  ((congrArg (fun A => S.ιObj c.pt A) (hbase ωc)).trans
                    (congrArg (fun A => S.ιObj c.pt A)
                      ((congrArg Comma.left (memElim hf').choose_spec).symm)))) :
                (S.stageCoconeFunctor c.pt).obj ((S.stageFunctor (c.π.app (some ωc) ≫ αF ωc)).obj V) ⟶ (S.stageCoconeFunctor c.pt).obj Y₁) :=
              conj_collapse₂ _ _ _ _ _ _ _
      -- the lowered outer core
      have hAA : (S.stageCoconeFunctor c.pt).map
            ((S.stageFunctor (c.π.app none)).map ωc.1.2) ≫
            eqToHom (S.ιObj_lower (c.π.app none) X') =
          eqToHom (S.ιObj_lower (c.π.app none) ωc.1.1) ≫
            (S.stageCoconeFunctor l).map ωc.1.2 :=
        (congrArg (fun w => w ≫ eqToHom (S.ιObj_lower (c.π.app none) X')) hlow).trans
          (conj_unsymm _ _ _)
      have hmf : (S.stageCoconeFunctor c.pt).map f' ≫
            eqToHom (S.ιObj_lower (c.π.app none) X') =
          eqToHom ((congrArg (fun A => S.ιObj c.pt A) hY₁).trans
              (S.ιObj_lower (c.π.app none) ωc.1.1)) ≫
            (S.stageCoconeFunctor l).map ωc.1.2 := by
        calc (S.stageCoconeFunctor c.pt).map f' ≫
              eqToHom (S.ιObj_lower (c.π.app none) X')
            = ((S.stageCoconeFunctor c.pt).map (eqToHom hY₁ ≫
                (S.stageFunctor (c.π.app none)).map ωc.1.2) ≫
                eqToHom (S.ιObj_lower (c.π.app none) X') : (S.stageCoconeFunctor c.pt).obj Y₁ ⟶ S.ιObj l X') :=
              congrArg (fun w => (S.stageCoconeFunctor c.pt).map w ≫
                eqToHom (S.ιObj_lower (c.π.app none) X')) hf'2
          _ = (eqToHom (congrArg (fun A => S.ιObj c.pt A) hY₁) ≫
              ((S.stageCoconeFunctor c.pt).map
                ((S.stageFunctor (c.π.app none)).map ωc.1.2) ≫
                eqToHom (S.ιObj_lower (c.π.app none) X')) : (S.stageCoconeFunctor c.pt).obj Y₁ ⟶ S.ιObj l X') := by
              refine (congrArg (fun w => w ≫ eqToHom (S.ιObj_lower (c.π.app none) X'))
                (map_eqToHom_comp_distrib (S.stageCoconeFunctor c.pt) hY₁
                  ((S.stageFunctor (c.π.app none)).map ωc.1.2))).trans ?_
              exact Category.assoc _ _ _
          _ = (eqToHom (congrArg (fun A => S.ιObj c.pt A) hY₁) ≫
              (eqToHom (S.ιObj_lower (c.π.app none) ωc.1.1) ≫
                (S.stageCoconeFunctor l).map ωc.1.2) : (S.stageCoconeFunctor c.pt).obj Y₁ ⟶ S.ιObj l X') := by
              exact congrArg (fun w => eqToHom (congrArg (fun A => S.ιObj c.pt A) hY₁) ≫ w) hAA
          _ = (eqToHom ((congrArg (fun A => S.ιObj c.pt A) hY₁).trans
                (S.ιObj_lower (c.π.app none) ωc.1.1)) ≫
              (S.stageCoconeFunctor l).map ωc.1.2 : (S.stageCoconeFunctor c.pt).obj Y₁ ⟶ S.ιObj l X') := by
              rw [← Category.assoc, eqToHom_trans]
      calc (eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
              (S.stageCoconeFunctor (iF (σm ωc))).map r ≫ eqToHom (hXF (σm ωc))) ≫
              (S.stageCoconeFunctor l).map ωc.1.2
          = eqToHom (S.ιObj_lower (c.π.app (some ωc) ≫ αF ωc) V) ≫
              (S.stageCoconeFunctor (iF (σm ωc))).map r ≫ eqToHom (hXF (σm ωc)) ≫
              (S.stageCoconeFunctor l).map ωc.1.2 := hflatL
        _ = (S.stageCoconeFunctor c.pt).map t ≫
              ((S.stageCoconeFunctor c.pt).map f' ≫
                eqToHom (S.ιObj_lower (c.π.app none) X')) := by
            refine Eq.trans ?_ (congrArg₂ (fun u v => u ≫ v) hmt.symm hmf.symm)
            exact (conj_assemble _ _ _ _ _).symm
        _ = (S.stageCoconeFunctor c.pt).map (t ≫ f') ≫
              eqToHom (S.ιObj_lower (c.π.app none) X') := by
            rw [Functor.map_comp, Category.assoc]
  · -- Every colimit-level bind member is the image of a stage-level bind member.
    rintro ⟨Yc, g', e, He, hg', rfl⟩
    have He' := He
    rw [S.stageCover_rfl_eq_map] at He'
    obtain ⟨W, g, hg, harrE⟩ := map_apply_elim _ He'
    have hYc : Yc = (S.stageCoconeFunctor l).obj W := congrArg Comma.left harrE
    subst hYc
    have he2 : e = (S.stageCoconeFunctor l).map g := eq_of_arrowMk_eq harrE
    subst he2
    -- the lowered outer member
    have hf₀ : (R'.map (S.stageFunctor (c.π.app none)))
        ((S.stageFunctor (c.π.app none)).map g) := Presieve.map.of hg
    -- coherence between the canonical pair of our member and that of the chosen slot
    have hσ : σm (memElim hf₀).choose = σm (⟨⟨W, g⟩, hg⟩ : R'.uncurry) := by
      apply Subtype.ext
      apply sigma_pair_eq_of_arrowMk
      refine (S.arrowMk_cocone_map_lower (c.π.app none)
        ((memElim hf₀).choose).1.2).trans ?_
      refine Eq.trans ?_ (S.arrowMk_cocone_map_lower (c.π.app none) g).symm
      exact (congrArg ((S.stageCoconeFunctor c.pt).mapArrow.obj)
        (memElim hf₀).choose_spec).symm
    -- the inner member against the canonical presentation
    have hg'' : S.stageCover (iF (σm ⟨⟨W, g⟩, hg⟩)) (XF (σm ⟨⟨W, g⟩, hg⟩))
        (hXF (σm ⟨⟨W, g⟩, hg⟩)) (RF (σm ⟨⟨W, g⟩, hg⟩)) g' := by
      rw [hpres (σm ⟨⟨W, g⟩, hg⟩)]
      exact hg'
    rw [S.stageCover_apply_iff] at hg''
    obtain ⟨V, r, hr, harrG⟩ := map_apply_elim _ hg''
    have hZ₀ : Z₀ = (S.stageCoconeFunctor (iF (σm ⟨⟨W, g⟩, hg⟩))).obj V :=
      congrArg Comma.left harrG
    subst hZ₀
    have hg'4 : g' = (S.stageCoconeFunctor (iF (σm ⟨⟨W, g⟩, hg⟩))).map r ≫
        eqToHom (hXF (σm ⟨⟨W, g⟩, hg⟩)) := by
      rw [← eq_of_arrowMk_eq harrG]
      exact (comp_eqToHom_symm_comp_self _ _).symm
    -- transport the inner member to the chosen presentation
    obtain ⟨V', r', hr', hcast⟩ : ∃ (V' : S.stage (iF (σm (memElim hf₀).choose)))
        (r' : V' ⟶ XF (σm (memElim hf₀).choose)),
        RF (σm (memElim hf₀).choose) r' ∧
          Arrow.mk ((S.stageCoconeFunctor (iF (σm (memElim hf₀).choose))).map r') =
            Arrow.mk ((S.stageCoconeFunctor (iF (σm ⟨⟨W, g⟩, hg⟩))).map r) := by
      rw [hσ]
      exact ⟨V, r, hr, rfl⟩
    -- membership of the transported inner member in the chosen slot
    have hslot : ((show (S.stageFunctor (c.π.app none)).obj ((memElim hf₀).choose).1.1 =
          (S.stageFunctor (c.π.app none)).obj W from
          (congrArg Comma.left (memElim hf₀).choose_spec).symm) ▸
        ((hbase (memElim hf₀).choose) ▸
          ((RF (σm (memElim hf₀).choose)).map
            (S.stageFunctor (c.π.app (some (memElim hf₀).choose) ≫
              αF (memElim hf₀).choose)))))
        ((S.stageFunctor (c.π.app (some (memElim hf₀).choose) ≫
            αF (memElim hf₀).choose)).map r' ≫
          eqToHom ((hbase (memElim hf₀).choose).trans
            ((congrArg Comma.left (memElim hf₀).choose_spec).symm))) := by
      refine (presieve_transport_apply _ _ _).mpr ?_
      refine (presieve_transport_apply _ _ _).mpr ?_
      refine mem_of_arrowMk_eq _ ?_ (Presieve.map.of hr')
      exact ((arrowMk_comp_eqToHom _ _).trans (arrowMk_comp_eqToHom _ _)).trans
        (arrowMk_comp_eqToHom _ _)
    rw [S.stageCover_apply_iff]
    refine mem_of_arrowMk_eq _ ?_ (Presieve.map.of
      (⟨_, (S.stageFunctor (c.π.app (some (memElim hf₀).choose) ≫
            αF (memElim hf₀).choose)).map r' ≫
          eqToHom ((hbase (memElim hf₀).choose).trans
            ((congrArg Comma.left (memElim hf₀).choose_spec).symm)),
        (S.stageFunctor (c.π.app none)).map g, hf₀, hslot, rfl⟩))
    -- the final arrow comparison
    have hcl' := conj_of_conj
      (S.ιObj_lower (c.π.app (some (memElim hf₀).choose) ≫
        αF (memElim hf₀).choose) V').symm
      (S.ιObj_lower (c.π.app (some (memElim hf₀).choose) ≫
        αF (memElim hf₀).choose) (XF (σm (memElim hf₀).choose)))
      (S.stageCoconeFunctor_map_lower (i := iF (σm (memElim hf₀).choose)) (k := c.pt)
        (c.π.app (some (memElim hf₀).choose) ≫ αF (memElim hf₀).choose) r')
    have hlow' := conj_of_conj
      (S.ιObj_lower (c.π.app none) W).symm
      (S.ιObj_lower (c.π.app none) X')
      (S.stageCoconeFunctor_map_lower (i := l) (k := c.pt) (c.π.app none) g)
    have hRflat : (S.stageCoconeFunctor c.pt).map
        (((S.stageFunctor (c.π.app (some (memElim hf₀).choose) ≫
            αF (memElim hf₀).choose)).map r' ≫
          eqToHom ((hbase (memElim hf₀).choose).trans
            ((congrArg Comma.left (memElim hf₀).choose_spec).symm))) ≫
          (S.stageFunctor (c.π.app none)).map g) =
        eqToHom (S.ιObj_lower (c.π.app (some (memElim hf₀).choose) ≫
            αF (memElim hf₀).choose) V') ≫
          (S.stageCoconeFunctor (iF (σm (memElim hf₀).choose))).map r' ≫
          eqToHom (((S.ιObj_lower (c.π.app (some (memElim hf₀).choose) ≫
              αF (memElim hf₀).choose) (XF (σm (memElim hf₀).choose))).symm.trans
            (congrArg (S.stageCoconeFunctor c.pt).obj
              ((hbase (memElim hf₀).choose).trans
                ((congrArg Comma.left (memElim hf₀).choose_spec).symm)))).trans
            (S.ιObj_lower (c.π.app none) W)) ≫
          (S.stageCoconeFunctor l).map g ≫
          eqToHom (S.ιObj_lower (c.π.app none) X').symm := by
      refine ((S.stageCoconeFunctor c.pt).map_comp _ _).trans ?_
      refine (congrArg (fun w => w ≫ (S.stageCoconeFunctor c.pt).map
        ((S.stageFunctor (c.π.app none)).map g))
        (map_comp_eqToHom_distrib (S.stageCoconeFunctor c.pt) _ _)).trans ?_
      refine (congrArg (fun w => (w ≫ eqToHom (congrArg (S.stageCoconeFunctor c.pt).obj
        ((hbase (memElim hf₀).choose).trans
          ((congrArg Comma.left (memElim hf₀).choose_spec).symm)))) ≫
        (S.stageCoconeFunctor c.pt).map
          ((S.stageFunctor (c.π.app none)).map g)) hcl').trans ?_
      refine (congrArg (fun w => (((eqToHom (S.ιObj_lower (c.π.app
        (some (memElim hf₀).choose) ≫ αF (memElim hf₀).choose) V') ≫
        (S.stageCoconeFunctor (iF (σm (memElim hf₀).choose))).map r' ≫
        eqToHom (S.ιObj_lower (c.π.app (some (memElim hf₀).choose) ≫
          αF (memElim hf₀).choose) (XF (σm (memElim hf₀).choose))).symm) ≫
        eqToHom (congrArg (S.stageCoconeFunctor c.pt).obj
          ((hbase (memElim hf₀).choose).trans
            ((congrArg Comma.left (memElim hf₀).choose_spec).symm)))) ≫ w)) hlow').trans ?_
      refine (congrArg (fun w => w ≫ (eqToHom (S.ιObj_lower (c.π.app none) W) ≫
        (S.stageCoconeFunctor l).map g ≫
        eqToHom (S.ιObj_lower (c.π.app none) X').symm))
        (conj_flat_right₁ _ _ _ _)).trans ?_
      exact conj_paste₅ _ _ _ _ _ _
    calc Arrow.mk ((g' ≫ (S.stageCoconeFunctor l).map g) ≫
            eqToHom (S.ιObj_lower (c.π.app none) X').symm)
        = Arrow.mk (g' ≫ (S.stageCoconeFunctor l).map g) := arrowMk_comp_eqToHom _ _
      _ = Arrow.mk (((S.stageCoconeFunctor (iF (σm ⟨⟨W, g⟩, hg⟩))).map r ≫
            eqToHom (hXF (σm ⟨⟨W, g⟩, hg⟩))) ≫ (S.stageCoconeFunctor l).map g) :=
          congrArg (fun w => Arrow.mk (w ≫ (S.stageCoconeFunctor l).map g)) hg'4
      _ = Arrow.mk ((S.stageCoconeFunctor (iF (σm ⟨⟨W, g⟩, hg⟩))).map r ≫
            eqToHom (hXF (σm ⟨⟨W, g⟩, hg⟩)) ≫ (S.stageCoconeFunctor l).map g) :=
          congrArg (fun w => Arrow.mk w) (Category.assoc _ _ _)
      _ = Arrow.mk ((S.stageCoconeFunctor (iF (σm (memElim hf₀).choose))).map r' ≫
            eqToHom (((S.ιObj_lower (c.π.app (some (memElim hf₀).choose) ≫
                αF (memElim hf₀).choose) (XF (σm (memElim hf₀).choose))).symm.trans
              (congrArg (S.stageCoconeFunctor c.pt).obj
                ((hbase (memElim hf₀).choose).trans
                  ((congrArg Comma.left (memElim hf₀).choose_spec).symm)))).trans
              (S.ιObj_lower (c.π.app none) W)) ≫
            ((S.stageCoconeFunctor l).map g ≫
              eqToHom (S.ιObj_lower (c.π.app none) X').symm)) :=
          arrowMk_glue_comp_congr hcast.symm
            (arrowMk_comp_eqToHom _ _).symm _ _
      _ = Arrow.mk (eqToHom (S.ιObj_lower (c.π.app (some (memElim hf₀).choose) ≫
            αF (memElim hf₀).choose) V') ≫
            (S.stageCoconeFunctor (iF (σm (memElim hf₀).choose))).map r' ≫
            eqToHom (((S.ιObj_lower (c.π.app (some (memElim hf₀).choose) ≫
                αF (memElim hf₀).choose) (XF (σm (memElim hf₀).choose))).symm.trans
              (congrArg (S.stageCoconeFunctor c.pt).obj
                ((hbase (memElim hf₀).choose).trans
                  ((congrArg Comma.left (memElim hf₀).choose_spec).symm)))).trans
              (S.ιObj_lower (c.π.app none) W)) ≫
            (S.stageCoconeFunctor l).map g ≫
            eqToHom (S.ιObj_lower (c.π.app none) X').symm) :=
          (arrowMk_eqToHom_comp _ _).symm
      _ = Arrow.mk ((S.stageCoconeFunctor c.pt).map
            (((S.stageFunctor (c.π.app (some (memElim hf₀).choose) ≫
                αF (memElim hf₀).choose)).map r' ≫
              eqToHom ((hbase (memElim hf₀).choose).trans
                ((congrArg Comma.left (memElim hf₀).choose_spec).symm))) ≫
              (S.stageFunctor (c.π.app none)).map g)) :=
          (congrArg (fun w => Arrow.mk w) hRflat).symm

/-- The key preservation lemma for Lemma 7.18.2 (3): the cocone functor preserves pullbacks of
members of chosen stage covering families. This is the source argument that
`\mathop{\mathrm{Mor}}(W, u_i(U^t \times_U V))` is computed by the filtered colimit of the stage
Hom-sets, which commutes with finite limits. -/
theorem stageCoconeFunctor_preservesPullback
    (i : S.I) {V : S.stage i} {R : Presieve V} (hR : R ∈ S.stageCov i V)
    {Y : S.stage i} {g : Y ⟶ V} (hg : R g) {T : S.stage i} (f : T ⟶ V)
    [HasPullback f g] :
    PreservesLimit (cospan f g) (S.stageCoconeFunctor i) := by
  apply preservesLimit_of_preserves_limit_cone (pullbackIsPullback f g)
  refine (isLimitMapConePullbackConeEquiv (S.stageCoconeFunctor i) pullback.condition).symm ?_
  -- Existence of fill-ins: descend the test cone to a common stage and lift there.
  have hex : ∀ s : PullbackCone ((S.stageCoconeFunctor i).map f) ((S.stageCoconeFunctor i).map g),
      ∃ ℓ : s.pt ⟶ (S.stageCoconeFunctor i).obj (pullback f g),
        ℓ ≫ (S.stageCoconeFunctor i).map (pullback.fst f g) = s.fst ∧
        ℓ ≫ (S.stageCoconeFunctor i).map (pullback.snd f g) = s.snd := by
    intro s
    obtain ⟨k₀, W₀, hW⟩ := S.ιObj_surjective s.pt
    obtain ⟨k, a, b, G₁, G₂, hG₁, hG₂⟩ :=
      exists_hom_rep_pair (eqToHom hW ≫ s.fst) (eqToHom hW ≫ s.snd)
    -- Descend the cone condition to stage `k`.
    have hcond : (S.stageCoconeFunctor k).map (G₁ ≫ (S.stageFunctor b).map f) =
        (S.stageCoconeFunctor k).map (G₂ ≫ (S.stageFunctor b).map g) := by
      apply eq_of_conj_eq (S.ιObj_lower a W₀).symm (S.ιObj_lower b V)
      calc eqToHom (S.ιObj_lower a W₀).symm ≫
            (S.stageCoconeFunctor k).map (G₁ ≫ (S.stageFunctor b).map f) ≫
            eqToHom (S.ιObj_lower b V)
          = (eqToHom (S.ιObj_lower a W₀).symm ≫ (S.stageCoconeFunctor k).map G₁ ≫
              eqToHom (S.ιObj_lower b T)) ≫
            eqToHom (S.ιObj_lower b T).symm ≫
              (S.stageCoconeFunctor k).map ((S.stageFunctor b).map f) ≫
              eqToHom (S.ιObj_lower b V) := by
            rw [Functor.map_comp]
            exact (conj_fuse _ _ _ _ _).symm
        _ = ((eqToHom hW ≫ s.fst) ≫ (S.stageCoconeFunctor i).map f :
              S.ιObj k₀ W₀ ⟶ S.ιObj i V) := by
            exact congrArg₂ (fun u v => u ≫ v) hG₁.symm
              (S.stageCoconeFunctor_map_lower b f).symm
        _ = ((eqToHom hW ≫ s.snd) ≫ (S.stageCoconeFunctor i).map g :
              S.ιObj k₀ W₀ ⟶ S.ιObj i V) := by
            rw [Category.assoc, Category.assoc]
            exact congrArg (fun t => eqToHom hW ≫ t) s.condition
        _ = (eqToHom (S.ιObj_lower a W₀).symm ≫ (S.stageCoconeFunctor k).map G₂ ≫
              eqToHom (S.ιObj_lower b Y)) ≫
            eqToHom (S.ιObj_lower b Y).symm ≫
              (S.stageCoconeFunctor k).map ((S.stageFunctor b).map g) ≫
              eqToHom (S.ιObj_lower b V) := by
            exact congrArg₂ (fun u v => u ≫ v) hG₂
              (S.stageCoconeFunctor_map_lower b g)
        _ = eqToHom (S.ιObj_lower a W₀).symm ≫
            (S.stageCoconeFunctor k).map (G₂ ≫ (S.stageFunctor b).map g) ≫
            eqToHom (S.ιObj_lower b V) := by
            rw [Functor.map_comp]
            exact conj_fuse _ _ _ _ _
    obtain ⟨n, γ, hsq₀⟩ := exists_stageFunctor_map_eq hcond
    -- Transport the descended square to the `(γ ≫ b)`-lowered cospan.
    have hsq := square_transport (S.stageFunctor_obj_comp b γ T)
      (S.stageFunctor_obj_comp b γ Y) (S.stageFunctor_obj_comp b γ V)
      (S.stageFunctor_map_map b γ f) (S.stageFunctor_map_map b γ g)
      (by simpa only [Functor.map_comp] using hsq₀)
    -- The transition functor preserves the stage pullback.
    haveI : PreservesLimit (cospan f g) (S.stageFunctor (γ ≫ b)) :=
      (S.stageFunctor_isContinuousSiteFunctor (γ ≫ b)).preservesPullback hR hg f
    have hpb := isLimitPullbackConeMapOfIsLimit (S.stageFunctor (γ ≫ b))
      pullback.condition (pullbackIsPullback f g)
    obtain ⟨L, hL₁, hL₂⟩ :
        ∃ L : (S.stageFunctor γ).obj ((S.stageFunctor a).obj W₀) ⟶
            (S.stageFunctor (γ ≫ b)).obj (pullback f g),
          L ≫ (S.stageFunctor (γ ≫ b)).map (pullback.fst f g) =
            (S.stageFunctor γ).map G₁ ≫ eqToHom (S.stageFunctor_obj_comp b γ T) ∧
          L ≫ (S.stageFunctor (γ ≫ b)).map (pullback.snd f g) =
            (S.stageFunctor γ).map G₂ ≫ eqToHom (S.stageFunctor_obj_comp b γ Y) := by
      obtain ⟨L₀, h₁, h₂⟩ := PullbackCone.IsLimit.lift' hpb
        ((S.stageFunctor γ).map G₁ ≫ eqToHom (S.stageFunctor_obj_comp b γ T))
        ((S.stageFunctor γ).map G₂ ≫ eqToHom (S.stageFunctor_obj_comp b γ Y)) hsq
      exact ⟨L₀, by simpa using h₁, by simpa using h₂⟩
    have hγG₁ := conj_of_conj (S.ιObj_lower γ ((S.stageFunctor a).obj W₀)).symm
      (S.ιObj_lower γ ((S.stageFunctor b).obj T)) (S.stageCoconeFunctor_map_lower γ G₁)
    have hγG₂ := conj_of_conj (S.ιObj_lower γ ((S.stageFunctor a).obj W₀)).symm
      (S.ιObj_lower γ ((S.stageFunctor b).obj Y)) (S.stageCoconeFunctor_map_lower γ G₂)
    refine ⟨eqToHom (((S.ιObj_lower γ ((S.stageFunctor a).obj W₀)).trans
        ((S.ιObj_lower a W₀).trans hW)).symm) ≫
      (S.stageCoconeFunctor n).map L ≫ eqToHom (S.ιObj_lower (γ ≫ b) (pullback f g)), ?_, ?_⟩
    · rw [S.stageCoconeFunctor_map_lower (γ ≫ b) (pullback.fst f g)]
      refine (conj_fuse _ _ _ _ _).trans ?_
      refine Eq.trans (congrArg (fun t => eqToHom (((S.ιObj_lower γ
          ((S.stageFunctor a).obj W₀)).trans ((S.ιObj_lower a W₀).trans hW)).symm) ≫ t ≫
          eqToHom (S.ιObj_lower (γ ≫ b) T))
        (((S.stageCoconeFunctor n).map_comp L
            ((S.stageFunctor (γ ≫ b)).map (pullback.fst f g))).symm.trans
          ((congrArg (S.stageCoconeFunctor n).map hL₁).trans
            (((S.stageCoconeFunctor n).map_comp ((S.stageFunctor γ).map G₁)
                (eqToHom (S.stageFunctor_obj_comp b γ T))).trans
              ((congrArg (fun t => (S.stageCoconeFunctor n).map
                  ((S.stageFunctor γ).map G₁) ≫ t)
                (eqToHom_map (S.stageCoconeFunctor n)
                  (S.stageFunctor_obj_comp b γ T))).trans
                (congrArg (fun t => t ≫ eqToHom (congrArg (S.stageCoconeFunctor n).obj
                  (S.stageFunctor_obj_comp b γ T))) hγG₁)))))) ?_
      refine (conj_collapse₂' _ _ _ _ _ _
        (((S.ιObj_lower a W₀).trans hW).symm) (S.ιObj_lower b T)).trans ?_
      rw [eq_eqToHom_comp_of_comp_eq hW hG₁]
      exact (conj_flat_left _ _ _ _ (((S.ιObj_lower a W₀).trans hW).symm)
        (S.ιObj_lower b T)).symm
    · rw [S.stageCoconeFunctor_map_lower (γ ≫ b) (pullback.snd f g)]
      refine (conj_fuse _ _ _ _ _).trans ?_
      refine Eq.trans (congrArg (fun t => eqToHom (((S.ιObj_lower γ
          ((S.stageFunctor a).obj W₀)).trans ((S.ιObj_lower a W₀).trans hW)).symm) ≫ t ≫
          eqToHom (S.ιObj_lower (γ ≫ b) Y))
        (((S.stageCoconeFunctor n).map_comp L
            ((S.stageFunctor (γ ≫ b)).map (pullback.snd f g))).symm.trans
          ((congrArg (S.stageCoconeFunctor n).map hL₂).trans
            (((S.stageCoconeFunctor n).map_comp ((S.stageFunctor γ).map G₂)
                (eqToHom (S.stageFunctor_obj_comp b γ Y))).trans
              ((congrArg (fun t => (S.stageCoconeFunctor n).map
                  ((S.stageFunctor γ).map G₂) ≫ t)
                (eqToHom_map (S.stageCoconeFunctor n)
                  (S.stageFunctor_obj_comp b γ Y))).trans
                (congrArg (fun t => t ≫ eqToHom (congrArg (S.stageCoconeFunctor n).obj
                  (S.stageFunctor_obj_comp b γ Y))) hγG₂)))))) ?_
      refine (conj_collapse₂' _ _ _ _ _ _
        (((S.ιObj_lower a W₀).trans hW).symm) (S.ιObj_lower b Y)).trans ?_
      rw [eq_eqToHom_comp_of_comp_eq hW hG₂]
      exact (conj_flat_left _ _ _ _ (((S.ιObj_lower a W₀).trans hW).symm)
        (S.ιObj_lower b Y)).symm
  -- Pairwise uniqueness of fill-ins: separate at a common stage and use the stage pullback.
  have huniq : ∀ (s : PullbackCone ((S.stageCoconeFunctor i).map f)
        ((S.stageCoconeFunctor i).map g))
      (m₁ m₂ : s.pt ⟶ (S.stageCoconeFunctor i).obj (pullback f g)),
      m₁ ≫ (S.stageCoconeFunctor i).map (pullback.fst f g) = s.fst →
      m₁ ≫ (S.stageCoconeFunctor i).map (pullback.snd f g) = s.snd →
      m₂ ≫ (S.stageCoconeFunctor i).map (pullback.fst f g) = s.fst →
      m₂ ≫ (S.stageCoconeFunctor i).map (pullback.snd f g) = s.snd → m₁ = m₂ := by
    intro s m₁ m₂ h₁₁ h₁₂ h₂₁ h₂₂
    obtain ⟨k₀, W₀, hW⟩ := S.ιObj_surjective s.pt
    obtain ⟨k, a, b, M₁, M₂, hM₁, hM₂⟩ :=
      exists_hom_rep_pair (eqToHom hW ≫ m₁) (eqToHom hW ≫ m₂)
    have hp₁ : (S.stageCoconeFunctor k).map (M₁ ≫ (S.stageFunctor b).map (pullback.fst f g)) =
        (S.stageCoconeFunctor k).map (M₂ ≫ (S.stageFunctor b).map (pullback.fst f g)) := by
      apply eq_of_conj_eq (S.ιObj_lower a W₀).symm (S.ιObj_lower b T)
      calc eqToHom (S.ιObj_lower a W₀).symm ≫
            (S.stageCoconeFunctor k).map (M₁ ≫ (S.stageFunctor b).map (pullback.fst f g)) ≫
            eqToHom (S.ιObj_lower b T)
          = (eqToHom (S.ιObj_lower a W₀).symm ≫ (S.stageCoconeFunctor k).map M₁ ≫
              eqToHom (S.ιObj_lower b (pullback f g))) ≫
            eqToHom (S.ιObj_lower b (pullback f g)).symm ≫
              (S.stageCoconeFunctor k).map ((S.stageFunctor b).map (pullback.fst f g)) ≫
              eqToHom (S.ιObj_lower b T) := by
            rw [Functor.map_comp]
            exact (conj_fuse _ _ _ _ _).symm
        _ = ((eqToHom hW ≫ m₁) ≫ (S.stageCoconeFunctor i).map (pullback.fst f g) :
              S.ιObj k₀ W₀ ⟶ S.ιObj i _) := by
            exact congrArg₂ (fun u v => u ≫ v) hM₁.symm
              (S.stageCoconeFunctor_map_lower b (pullback.fst f g)).symm
        _ = ((eqToHom hW ≫ m₂) ≫ (S.stageCoconeFunctor i).map (pullback.fst f g) :
              S.ιObj k₀ W₀ ⟶ S.ιObj i _) := by
            rw [Category.assoc, Category.assoc]
            exact congrArg (fun t => eqToHom hW ≫ t) (h₁₁.trans h₂₁.symm)
        _ = (eqToHom (S.ιObj_lower a W₀).symm ≫ (S.stageCoconeFunctor k).map M₂ ≫
              eqToHom (S.ιObj_lower b (pullback f g))) ≫
            eqToHom (S.ιObj_lower b (pullback f g)).symm ≫
              (S.stageCoconeFunctor k).map ((S.stageFunctor b).map (pullback.fst f g)) ≫
              eqToHom (S.ιObj_lower b T) := by
            exact congrArg₂ (fun u v => u ≫ v) hM₂
              (S.stageCoconeFunctor_map_lower b (pullback.fst f g))
        _ = eqToHom (S.ιObj_lower a W₀).symm ≫
            (S.stageCoconeFunctor k).map (M₂ ≫ (S.stageFunctor b).map (pullback.fst f g)) ≫
            eqToHom (S.ιObj_lower b T) := by
            rw [Functor.map_comp]
            exact conj_fuse _ _ _ _ _
    have hp₂ : (S.stageCoconeFunctor k).map (M₁ ≫ (S.stageFunctor b).map (pullback.snd f g)) =
        (S.stageCoconeFunctor k).map (M₂ ≫ (S.stageFunctor b).map (pullback.snd f g)) := by
      apply eq_of_conj_eq (S.ιObj_lower a W₀).symm (S.ιObj_lower b Y)
      calc eqToHom (S.ιObj_lower a W₀).symm ≫
            (S.stageCoconeFunctor k).map (M₁ ≫ (S.stageFunctor b).map (pullback.snd f g)) ≫
            eqToHom (S.ιObj_lower b Y)
          = (eqToHom (S.ιObj_lower a W₀).symm ≫ (S.stageCoconeFunctor k).map M₁ ≫
              eqToHom (S.ιObj_lower b (pullback f g))) ≫
            eqToHom (S.ιObj_lower b (pullback f g)).symm ≫
              (S.stageCoconeFunctor k).map ((S.stageFunctor b).map (pullback.snd f g)) ≫
              eqToHom (S.ιObj_lower b Y) := by
            rw [Functor.map_comp]
            exact (conj_fuse _ _ _ _ _).symm
        _ = ((eqToHom hW ≫ m₁) ≫ (S.stageCoconeFunctor i).map (pullback.snd f g) :
              S.ιObj k₀ W₀ ⟶ S.ιObj i _) := by
            exact congrArg₂ (fun u v => u ≫ v) hM₁.symm
              (S.stageCoconeFunctor_map_lower b (pullback.snd f g)).symm
        _ = ((eqToHom hW ≫ m₂) ≫ (S.stageCoconeFunctor i).map (pullback.snd f g) :
              S.ιObj k₀ W₀ ⟶ S.ιObj i _) := by
            rw [Category.assoc, Category.assoc]
            exact congrArg (fun t => eqToHom hW ≫ t) (h₁₂.trans h₂₂.symm)
        _ = (eqToHom (S.ιObj_lower a W₀).symm ≫ (S.stageCoconeFunctor k).map M₂ ≫
              eqToHom (S.ιObj_lower b (pullback f g))) ≫
            eqToHom (S.ιObj_lower b (pullback f g)).symm ≫
              (S.stageCoconeFunctor k).map ((S.stageFunctor b).map (pullback.snd f g)) ≫
              eqToHom (S.ιObj_lower b Y) := by
            exact congrArg₂ (fun u v => u ≫ v) hM₂
              (S.stageCoconeFunctor_map_lower b (pullback.snd f g))
        _ = eqToHom (S.ιObj_lower a W₀).symm ≫
            (S.stageCoconeFunctor k).map (M₂ ≫ (S.stageFunctor b).map (pullback.snd f g)) ≫
            eqToHom (S.ιObj_lower b Y) := by
            rw [Functor.map_comp]
            exact conj_fuse _ _ _ _ _
    obtain ⟨n₁, δ₁, hd₁⟩ := exists_stageFunctor_map_eq hp₁
    obtain ⟨n₂, δ₂, hd₂⟩ := exists_stageFunctor_map_eq hp₂
    obtain ⟨n, w₁, w₂, hw⟩ := S.exists_span δ₁ δ₂
    have hd₁' := S.stageFunctor_map_eq_lower δ₁ w₁ hd₁
    have hd₂' := S.stageFunctor_map_eq_lower δ₂ w₂ hd₂
    rw [← hw] at hd₂'
    -- Transport the two projection identities to the `((w₁ ≫ δ₁) ≫ b)`-lowered cone.
    have hk₁ := square_transport (S.stageFunctor_obj_comp b (w₁ ≫ δ₁) (pullback f g))
      (S.stageFunctor_obj_comp b (w₁ ≫ δ₁) (pullback f g))
      (S.stageFunctor_obj_comp b (w₁ ≫ δ₁) T)
      (S.stageFunctor_map_map b (w₁ ≫ δ₁) (pullback.fst f g))
      (S.stageFunctor_map_map b (w₁ ≫ δ₁) (pullback.fst f g))
      (by simpa only [Functor.map_comp] using hd₁')
    have hk₂ := square_transport (S.stageFunctor_obj_comp b (w₁ ≫ δ₁) (pullback f g))
      (S.stageFunctor_obj_comp b (w₁ ≫ δ₁) (pullback f g))
      (S.stageFunctor_obj_comp b (w₁ ≫ δ₁) Y)
      (S.stageFunctor_map_map b (w₁ ≫ δ₁) (pullback.snd f g))
      (S.stageFunctor_map_map b (w₁ ≫ δ₁) (pullback.snd f g))
      (by simpa only [Functor.map_comp] using hd₂')
    haveI : PreservesLimit (cospan f g) (S.stageFunctor ((w₁ ≫ δ₁) ≫ b)) :=
      (S.stageFunctor_isContinuousSiteFunctor ((w₁ ≫ δ₁) ≫ b)).preservesPullback hR hg f
    have hpb := isLimitPullbackConeMapOfIsLimit (S.stageFunctor ((w₁ ≫ δ₁) ≫ b))
      pullback.condition (pullbackIsPullback f g)
    have hK := PullbackCone.IsLimit.hom_ext hpb hk₁ hk₂
    have hM : (S.stageFunctor (w₁ ≫ δ₁)).map M₁ = (S.stageFunctor (w₁ ≫ δ₁)).map M₂ :=
      eq_of_comp_eqToHom_eq _ hK
    have hMk : (S.stageCoconeFunctor k).map M₁ = (S.stageCoconeFunctor k).map M₂ := by
      rw [S.stageCoconeFunctor_map_lower (w₁ ≫ δ₁) M₁,
        S.stageCoconeFunctor_map_lower (w₁ ≫ δ₁) M₂, hM]
    refine eq_of_eqToHom_comp_eq hW ?_
    refine hM₁.trans (Eq.trans ?_ hM₂.symm)
    exact congrArg (fun t => eqToHom (S.ιObj_lower a W₀).symm ≫ t ≫
      eqToHom (S.ιObj_lower b (pullback f g))) hMk
  refine PullbackCone.IsLimit.mk _ (fun s => (hex s).choose)
    (fun s => (hex s).choose_spec.1) (fun s => (hex s).choose_spec.2) ?_
  intro s m hm₁ hm₂
  exact huniq s m (hex s).choose hm₁ hm₂ (hex s).choose_spec.1 (hex s).choose_spec.2

/-- Lemma 7.18.2 (3), existence part: covering members of the colimit site admit pullbacks along
arbitrary morphisms of the colimit category. The pullback is the image of a stage pullback, which
the cocone functor preserves. -/
instance colimitSite_hasPullbacks : S.colimitSite.HasPullbacks := by
  constructor
  rintro x y T f ⟨l, X', hX', R', hR', rfl⟩
  subst hX'
  constructor
  intro Z h hh
  rw [S.stageCover_rfl_eq_map] at hh
  obtain ⟨W₁, g₀, hg₀, harr⟩ := map_apply_elim (S.stageCoconeFunctor l) hh
  have hZ : Z = (S.stageCoconeFunctor l).obj W₁ := congrArg Comma.left harr
  subst hZ
  have hh2 : h = (S.stageCoconeFunctor l).map g₀ := eq_of_arrowMk_eq harr
  obtain ⟨k₀, W₀, hW⟩ := S.ιObj_surjective x
  obtain ⟨k, a, b, F', hF'⟩ := exists_hom_rep (eqToHom hW ≫ f)
  rw [mk_eq_eqToHom_comp] at hF'
  have hf3 : f = eqToHom (((S.ιObj_lower a W₀).trans hW)).symm ≫
      (S.stageCoconeFunctor k).map F' ≫ eqToHom (S.ιObj_lower b X') :=
    (eq_eqToHom_comp_of_comp_eq hW hF').trans (conj_flat_left _ _ _ _ _ _)
  have hRb : R'.map (S.stageFunctor b) ∈ S.stageCov k ((S.stageFunctor b).obj X') :=
    (S.stageFunctor_isContinuousSiteFunctor b).toLeComap _ hR'
  haveI hpbs : Presieve.HasPullbacks (R'.map (S.stageFunctor b)) F' :=
    (S.stageCov k).hasPullbacks_of_mem F' hRb
  haveI : HasPullback ((S.stageFunctor b).map g₀) F' :=
    Presieve.hasPullback F' (Presieve.map.of hg₀)
  haveI : HasPullback F' ((S.stageFunctor b).map g₀) := hasPullback_symmetry _ _
  haveI : PreservesLimit (cospan F' ((S.stageFunctor b).map g₀)) (S.stageCoconeFunctor k) :=
    S.stageCoconeFunctor_preservesPullback k hRb (Presieve.map.of hg₀) F'
  haveI : HasPullback ((S.stageCoconeFunctor k).map F')
      ((S.stageCoconeFunctor k).map ((S.stageFunctor b).map g₀)) :=
    hasPullback_of_preservesPullback _ _ _
  haveI : HasPullback ((S.stageCoconeFunctor k).map ((S.stageFunctor b).map g₀))
      ((S.stageCoconeFunctor k).map F') := hasPullback_symmetry _ _
  have h1 := conj_of_conj (S.ιObj_lower b W₁).symm (S.ιObj_lower b X')
    (S.stageCoconeFunctor_map_lower b g₀)
  have wf : (eqToIso (S.ιObj_lower b W₁)).hom ≫ h =
      (S.stageCoconeFunctor k).map ((S.stageFunctor b).map g₀) ≫
        (eqToIso (S.ιObj_lower b X')).hom := by
    rw [eqToIso.hom, eqToIso.hom, hh2, h1]
    exact (conj_unsymm (S.ιObj_lower b W₁) (S.ιObj_lower b X').symm
      ((S.stageCoconeFunctor l).map g₀)).symm
  have wg : (eqToIso ((S.ιObj_lower a W₀).trans hW)).hom ≫ f =
      (S.stageCoconeFunctor k).map F' ≫ (eqToIso (S.ιObj_lower b X')).hom := by
    rw [eqToIso.hom, eqToIso.hom, hf3]
    exact eqToHom_comp_conj _ _ _
  exact hasLimit_of_iso
    (F := cospan ((S.stageCoconeFunctor k).map ((S.stageFunctor b).map g₀))
      ((S.stageCoconeFunctor k).map F'))
    (cospanExt (iX := eqToIso (S.ιObj_lower b W₁))
      (iY := eqToIso ((S.ιObj_lower a W₀).trans hW))
      (iZ := eqToIso (S.ιObj_lower b X')) wf wg)

/-- Lemma 7.18.2 (3), covering part: a covering family of the colimit site pulled back along an
arbitrary morphism is refined by a covering family that factors through it. The refining family
is the image of a stage pullback family, as in the source proof. -/
instance colimitSite_hasFactoringPullbacks : S.colimitSite.HasFactoringPullbacks := by
  constructor
  rintro x y f T ⟨l, X', hX', R', hR', rfl⟩
  subst hX'
  obtain ⟨k₀, W₀, hW⟩ := S.ιObj_surjective y
  subst hW
  obtain ⟨k, a, b, F', hF'⟩ := exists_hom_rep f
  rw [mk_eq_eqToHom_comp] at hF'
  have hRb : R'.map (S.stageFunctor b) ∈ S.stageCov k ((S.stageFunctor b).obj X') :=
    (S.stageFunctor_isContinuousSiteFunctor b).toLeComap _ hR'
  obtain ⟨T₀, hT₀, hfac₀⟩ := Precoverage.exists_factors F' hRb
  refine ⟨S.stageCover k ((S.stageFunctor a).obj W₀) (S.ιObj_lower a W₀) T₀,
    ⟨k, _, _, T₀, hT₀, rfl⟩, ?_⟩
  intro Z t ht
  rw [S.stageCover_apply_iff] at ht
  obtain ⟨W₂, s₀, hs₀, harr⟩ := map_apply_elim (S.stageCoconeFunctor k) ht
  have hZ : Z = (S.stageCoconeFunctor k).obj W₂ := congrArg Comma.left harr
  subst hZ
  have ht2 : t ≫ eqToHom (S.ιObj_lower a W₀).symm = (S.stageCoconeFunctor k).map s₀ :=
    eq_of_arrowMk_eq harr
  have ht3 : t = (S.stageCoconeFunctor k).map s₀ ≫ eqToHom (S.ιObj_lower a W₀) := by
    rw [← ht2]
    exact (comp_eqToHom_symm_comp_self _ _).symm
  obtain ⟨W₃, q', e', he', hqe⟩ := hfac₀ hs₀
  obtain ⟨W₄, g₁, hg₁, harr'⟩ := map_apply_elim (S.stageFunctor b) he'
  have hW₃ : W₃ = (S.stageFunctor b).obj W₄ := congrArg Comma.left harr'
  subst hW₃
  have he2 : e' = (S.stageFunctor b).map g₁ := eq_of_arrowMk_eq harr'
  have h1 := conj_of_conj (S.ιObj_lower b W₄).symm (S.ιObj_lower b X')
    (S.stageCoconeFunctor_map_lower b g₁)
  refine ⟨(S.stageCoconeFunctor l).obj W₄,
    (S.stageCoconeFunctor k).map q' ≫ eqToHom (S.ιObj_lower b W₄),
    (S.stageCoconeFunctor l).map g₁, ?_, ?_⟩
  · rw [S.stageCover_rfl_eq_map]
    exact Presieve.map.of hg₁
  · calc ((S.stageCoconeFunctor k).map q' ≫ eqToHom (S.ιObj_lower b W₄)) ≫
          (S.stageCoconeFunctor l).map g₁
        = (S.stageCoconeFunctor k).map q' ≫ eqToHom (S.ιObj_lower b W₄) ≫
            (S.stageCoconeFunctor l).map g₁ := by rw [Category.assoc]
      _ = (S.stageCoconeFunctor k).map q' ≫
            (S.stageCoconeFunctor k).map ((S.stageFunctor b).map g₁) ≫
            eqToHom (S.ιObj_lower b X') := by
          refine congrArg (fun u => (S.stageCoconeFunctor k).map q' ≫ u) ?_
          rw [h1]
          exact (conj_unsymm (S.ιObj_lower b W₄) (S.ιObj_lower b X').symm
            ((S.stageCoconeFunctor l).map g₁)).symm
      _ = (S.stageCoconeFunctor k).map (q' ≫ e') ≫ eqToHom (S.ιObj_lower b X') := by
          rw [he2, CategoryTheory.Functor.map_comp, Category.assoc]
      _ = (S.stageCoconeFunctor k).map (s₀ ≫ F') ≫ eqToHom (S.ιObj_lower b X') := by
          rw [hqe]
      _ = (S.stageCoconeFunctor k).map s₀ ≫
            ((S.stageCoconeFunctor k).map F' ≫ eqToHom (S.ιObj_lower b X')) := by
          rw [CategoryTheory.Functor.map_comp, Category.assoc]
      _ = ((S.stageCoconeFunctor k).map s₀ ≫ eqToHom (S.ιObj_lower a W₀)) ≫ f := by
          rw [hF', Category.assoc]
          exact congrArg (fun u => (S.stageCoconeFunctor k).map s₀ ≫ u)
            (eqToHom_comp_conj (S.ιObj_lower a W₀) (S.ιObj_lower b X')
              ((S.stageCoconeFunctor k).map F')).symm
      _ = t ≫ f := by rw [← ht3]

end SiteAxioms

section Continuity

/-- Lemma 7.18.2 (4)/(6): each cocone functor is continuous in the Stacks Project sense
(Definition 7.13.1) from the stage site to the colimit site. -/
instance stageCocone_isContinuousSiteFunctor (i : S.I) :
    Functor.IsContinuousSiteFunctor
      (S.stageCoconeFunctor i) (S.stageCov i) S.colimitSite where
  toLeComap := S.stageCov_le_comap i
  preservesPullback := fun {_V _R} hR {_Y _g} hg {_T} f =>
    S.stageCoconeFunctor_preservesPullback _ hR hg f

/-- The cocone functors are continuous for the generated Grothendieck topologies. This is the
load-bearing instance for the sheaf-pullback functors used by Lemmas 7.18.3-7.18.5. -/
instance stageCoconeFunctor_isContinuous (i : S.I) :
    Functor.IsContinuous (S.stageCoconeFunctor i) (S.stageTopology i) S.colimitTopology :=
  Functor.isContinuous_toGrothendieck_of_isContinuousSiteFunctor
    (S.stageCoconeFunctor i) (S.stageCov i) S.colimitSite

/-- Stage pullback followed by colimit-stage pullback is canonically the colimit-stage pullback
from the source stage. -/
noncomputable def colimitStageSheafPullbackCompIso
    (A : Type*) [Category A]
    {i j : S.I} (a : j ⟶ i)
    [HasWeakSheafify (S.stageTopology j) A]
    [HasWeakSheafify S.colimitTopology A]
    [∀ F : (S.stage i)ᵒᵖ ⥤ A, (S.stageFunctor a).op.HasLeftKanExtension F]
    [∀ F : (S.stage j)ᵒᵖ ⥤ A, (S.stageCoconeFunctor j).op.HasLeftKanExtension F]
    [∀ F : (S.stage i)ᵒᵖ ⥤ A, (S.stageCoconeFunctor i).op.HasLeftKanExtension F] :
    (S.stageFunctor a).sheafPullback A (S.stageTopology i) (S.stageTopology j) ⋙
        (S.stageCoconeFunctor j).sheafPullback A (S.stageTopology j) S.colimitTopology ≅
      (S.stageCoconeFunctor i).sheafPullback A (S.stageTopology i) S.colimitTopology :=
  Adjunction.leftAdjointCompIso
    ((S.stageFunctor a).sheafAdjunctionContinuous A
      (S.stageTopology i) (S.stageTopology j))
    ((S.stageCoconeFunctor j).sheafAdjunctionContinuous A
      (S.stageTopology j) S.colimitTopology)
    ((S.stageCoconeFunctor i).sheafAdjunctionContinuous A
      (S.stageTopology i) S.colimitTopology)
    (Functor.sheafPushforwardContinuousComp'
      (eqToIso (S.stageCoconeFunctor_comp_eq a))
      A (S.stageTopology i) (S.stageTopology j) S.colimitTopology)

end Continuity

end CofilteredSiteDiagram

end
