module

public import stacks_project.Chap07.Definition_7_8_2
public import stacks_project.Chap07.Lemma_7_12_4
public import stacks_project.Chap07.Definition_7_17_1
@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory
open CategoryTheory.SemiRepresentableFamily.Over

universe w u v

namespace CategoryTheory.GrothendieckTopology

variable {C : Type u} [Category.{v} C]

/- Domain-style sampling for Lemma 7.17.2:
- primary domain: Grothendieck-topology covering families, presieves, and refinements;
- sampled owner/bridge declarations:
  `CategoryTheory.Presieve`,
  `GrothendieckTopology.Cover`,
  `GrothendieckTopology.QuasiCompactObject`,
  `QuasiCompactObject.finite_image_refinement_of_family`,
  `SemiRepresentableFamily.Over.toPresieve`,
  `SemiRepresentableFamily.Over.toSieve`;
- source-facing owners: `HasFiniteSubcoverProperty`, `HasFiniteRefinementProperty`;
- core/canonical consequence already present upstream: `J.QuasiCompactObject U`;
- bridge/view layer: explicit indexed covering families `SemiRepresentableFamily.Over U`.

Primitive data for the source-facing properties are the topology `J`, the object `U`, and a
presieve `R : Presieve U`, which records the actual arrows in the chosen covering family without
fixing an index universe. Explicit `SemiRepresentableFamily.Over U` presentations are derived
bridge/view API from that presieve owner. The downstream consequence `J.QuasiCompactObject U`
already has its canonical sieve-level owner upstream, so this file keeps only the genuinely
stronger source-facing owners and their implication to that canonical consequence.
-/

/-- A site object satisfies the finite-refinement condition when every covering presieve on `U`
admits a finite covering family refining that presieve. -/
class HasFiniteRefinementProperty (J : GrothendieckTopology C) (U : C) : Prop where
  finite_refinement
    (R : Presieve U) (hR : Sieve.generate R ∈ J U) :
    ∃ (𝒱 : SemiRepresentableFamily.Over.{max u v} U) (_ : Finite 𝒱.index)
      (_ : 𝒱.toSieve ∈ J U),
      𝒱.toSieve ≤ Sieve.generate R

/-- A site object satisfies the finite-subcover condition when every covering presieve on `U`
already contains finitely many of its own arrows generating a covering sieve. -/
class HasFiniteSubcoverProperty (J : GrothendieckTopology C) (U : C) : Prop where
  finite_subcover
    (R : Presieve U) (hR : Sieve.generate R ∈ J U) :
    ∃ (S : Set R.uncurry) (_ : S.Finite),
      Sieve.ofArrows
        (fun i : S ↦ i.1.1.1)
        (fun i ↦ i.1.1.2) ∈ J U

/-- The canonical presieve generated by all arrows already lying in `R` is exactly `R` itself. -/
theorem presieve_of_uncurry_eq {U : C} (R : Presieve U) :
    Presieve.ofArrows (fun i : R.uncurry ↦ i.1.1) (fun i ↦ i.1.2) = R := by
  funext Y f
  apply propext
  constructor
  · intro hf
    rcases hf with ⟨i⟩
    exact i.2
  · intro hf
    let i : R.uncurry := ⟨⟨Y, f⟩, hf⟩
    exact Presieve.ofArrows.mk i

/-- The presieve-level finite-refinement owner applies to any explicit indexed covering family,
independently of the indexing universe. -/
theorem HasFiniteRefinementProperty.finite_refinement_of_family
    {J : GrothendieckTopology C} {U : C} (hU : HasFiniteRefinementProperty J U)
    (𝒰 : SemiRepresentableFamily.Over.{w} U) (h𝒰 : 𝒰.toSieve ∈ J U) :
    ∃ (𝒱 : SemiRepresentableFamily.Over.{max u v} U) (_ : Finite 𝒱.index)
      (_ : 𝒱.toSieve ∈ J U),
      𝒱.toSieve ≤ 𝒰.toSieve := by
  simpa [toSieve] using hU.finite_refinement 𝒰.toPresieve h𝒰

-- Proof sketch: given a finite covering subfamily, use that same subfamily as the finite refining
-- covering family, together with the evident refinement maps into the original cover.
/-- Lemma 7.17.2 (1): if every covering of `U` contains a finite covering subfamily, then every
covering of `U` admits a finite covering refinement. -/
theorem hasFiniteSubcoverProperty_implies_hasFiniteRefinementProperty
    {J : GrothendieckTopology C} {U : C} (hU : HasFiniteSubcoverProperty J U) :
    HasFiniteRefinementProperty J U :=
  { finite_refinement := fun R hR ↦ by
      obtain ⟨S, hS, hSieve⟩ := hU.finite_subcover R hR
      let 𝒱 : SemiRepresentableFamily.Over.{max u v} U :=
        ofArrows
          (fun i : S ↦ i.1.1.1)
          (fun i ↦ i.1.1.2)
      have hle : 𝒱.toSieve ≤ Sieve.generate R := by
        apply Sieve.generate_mono
        rw [Presieve.ofArrows_le_iff]
        intro i
        exact i.1.2
      refine ⟨𝒱, hS.to_subtype, ?_, hle⟩
      simpa [𝒱, toSieve, toPresieve, ofArrows] using hSieve }

-- Proof sketch: a finite refining covering has finite index type, so the image of its index map
-- in the original family is finite; this is exactly the finite-image refinement required in the
-- definition of quasi-compactness above.
/-- Lemma 7.17.2 (2): if every covering of `U` admits a finite covering refinement, then `U` is
quasi-compact. -/
theorem hasFiniteRefinementProperty_implies_quasiCompactObject
    {J : GrothendieckTopology C} {U : C} (hU : HasFiniteRefinementProperty J U) :
    J.QuasiCompactObject U := by
  change
    ∀ S : J.Cover U,
      ∃ (T : Set S.Arrow) (_ : T.Finite),
        Sieve.ofArrows (fun I : T ↦ I.1.Y) (fun I ↦ I.1.f) ∈ J U
  intro S
  have hS : Sieve.generate (S : Sieve U) ∈ J U := by
    simpa using S.condition
  obtain ⟨𝒱₀, h𝒱₀fin, h𝒱₀, hle⟩ := hU.finite_refinement (S : Sieve U) hS
  have hle' : 𝒱₀.toSieve ≤ (S : Sieve U) := by
    simpa using hle
  let toArrow : 𝒱₀.index → S.Arrow := fun i ↦
    { Y := (𝒱₀.obj i).left
      f := (𝒱₀.obj i).hom
      hf := by
        have hi : 𝒱₀.toSieve ((𝒱₀.obj i).hom) := by
          exact (Sieve.le_generate 𝒱₀.toPresieve) _ _ (Presieve.ofArrows.mk i)
        have hi' : (S : Sieve U) ((𝒱₀.obj i).hom) := by
          exact hle' (𝒱₀.obj i).hom hi
        simpa using hi' }
  let T : Set S.Arrow := Set.range toArrow
  have hT : T.Finite := by
    let _ : Finite 𝒱₀.index := h𝒱₀fin
    letI := Fintype.ofFinite 𝒱₀.index
    simpa [T, toArrow] using Set.finite_range toArrow
  have hTpresieve :
      Presieve.ofArrows (fun I : T ↦ I.1.Y) (fun I ↦ I.1.f) = 𝒱₀.toPresieve := by
    let a : 𝒱₀.index → T := fun i ↦ ⟨toArrow i, ⟨i, rfl⟩⟩
    have ha : Function.Surjective a := by
      rintro ⟨I, i, rfl⟩
      exact ⟨i, rfl⟩
    calc
      Presieve.ofArrows (fun I : T ↦ I.1.Y) (fun I ↦ I.1.f)
          =
            Presieve.ofArrows
              (fun i : 𝒱₀.index ↦ (a i).1.Y)
              (fun i ↦ (a i).1.f) := by
        symm
        exact Presieve.ofArrows_comp_eq_of_surjective (fun I : T ↦ I.1.f) ha
      _ = 𝒱₀.toPresieve := by
        rfl
  have hTcover : Sieve.ofArrows (fun I : T ↦ I.1.Y) (fun I ↦ I.1.f) ∈ J U := by
    rw [Sieve.ofArrows, hTpresieve]
    exact h𝒱₀
  refine ⟨T, hT, ?_⟩
  exact hTcover

/-- Helper for Lemma 7.17.2: a morphism into the canonical uncurry family factors through the
subfamily indexed by the image of its index map. -/
theorem toSieve_le_range_family_of_hom
    {U : C} (R : Presieve U) {𝒱 : SemiRepresentableFamily.Over.{max u v} U}
    (φ : 𝒱 ⟶ ofArrows (fun i : R.uncurry ↦ i.1.1) (fun i ↦ i.1.2)) :
    𝒱.toSieve ≤
      (ofArrows (fun i : Set.range φ.α ↦ i.1.1.1) (fun i ↦ i.1.1.2)).toSieve := by
  let 𝒲 : SemiRepresentableFamily.Over.{max u v} U :=
    ofArrows (fun i : Set.range φ.α ↦ i.1.1.1) (fun i ↦ i.1.1.2)
  -- Reindex `𝒱` by the image of `φ.α`; the component maps are unchanged.
  let ψ : 𝒱 ⟶ 𝒲 :=
    { α := fun i ↦ ⟨φ.α i, ⟨i, rfl⟩⟩
      f := fun i ↦ φ.f i }
  -- The induced family morphism gives the required sieve inclusion.
  simpa [𝒲] using toSieve_le_of_hom ψ

/-- Helper for Lemma 7.17.2: a sieve refinement by `Sieve.generate R` chooses, for each component
of an explicit family, an actual arrow of `R` through which that component factors. -/
theorem exists_hom_to_uncurry_family_of_sieve_refinement
    {U : C} (R : Presieve U) (𝒱 : SemiRepresentableFamily.Over.{max u v} U)
    (hle : 𝒱.toSieve ≤ Sieve.generate R) :
    Nonempty (𝒱 ⟶ ofArrows (fun i : R.uncurry ↦ i.1.1) (fun i ↦ i.1.2)) := by
  classical
  let 𝒰 : SemiRepresentableFamily.Over.{max u v} U :=
    ofArrows (fun i : R.uncurry ↦ i.1.1) (fun i ↦ i.1.2)
  have hfactor :
      ∀ i : 𝒱.index,
        ∃ j : R.uncurry, ∃ g : (𝒱.obj i).left ⟶ j.1.1, g ≫ j.1.2 = (𝒱.obj i).hom := by
    intro i
    -- Each generator of `𝒱.toSieve` lies in `Sieve.generate R`, so it factors through a chosen
    -- arrow of `R`.
    have hi : 𝒱.toSieve ((𝒱.obj i).hom) := by
      exact Sieve.le_generate 𝒱.toPresieve _ _ (Presieve.ofArrows.mk i)
    have hi' : Sieve.generate R ((𝒱.obj i).hom) := by
      exact hle (𝒱.obj i).hom hi
    rcases hi' with ⟨Y, g, f, hf, hgf⟩
    exact ⟨⟨⟨Y, f⟩, hf⟩, g, hgf⟩
  choose α g hg using hfactor
  -- Package the chosen factorizations as a morphism of fixed-target families.
  refine ⟨
    { α := α
      f := fun i ↦ Over.homMk (g i) (by simpa [𝒰] using hg i) }⟩

-- In the source text, condition (1) is a covering-family notion of quasi-compactness. The
-- current Mathlib owner `QuasiCompactObject` is sieve-based and is strong enough to produce the
-- finite-refinement property directly, so the source counterexample should not be stated as a
-- negation involving this owner.
/-- Lemma 7.17.2 (3), repaired owner form: with the current sieve-level owner,
`QuasiCompactObject` implies the finite-refinement condition. The source counterexample to the
reverse implication belongs to the covering-family presentation of quasi-compactness, not to this
formal owner. -/
theorem exists_quasiCompactObject_not_hasFiniteRefinementProperty
    {J : GrothendieckTopology C} {U : C} (hU : J.QuasiCompactObject U) :
    HasFiniteRefinementProperty J U := by
  refine
    { finite_refinement := fun R hR ↦ by
        let 𝒰 : SemiRepresentableFamily.Over.{max u v} U :=
          ofArrows (fun i : R.uncurry ↦ i.1.1) (fun i ↦ i.1.2)
        have h𝒰toPresieve : 𝒰.toPresieve = R := by
          simpa [𝒰, toPresieve, ofArrows] using presieve_of_uncurry_eq R
        have h𝒰toSieve : 𝒰.toSieve = Sieve.generate R := by
          simp [toSieve, h𝒰toPresieve]
        -- Apply quasi-compactness to the canonical uncurry family attached to `R`.
        obtain ⟨𝒱, h𝒱, φ, hφfin⟩ :=
          hU.finite_image_refinement_of_family 𝒰 (by simpa [h𝒰toSieve] using hR)
        let 𝒲 : SemiRepresentableFamily.Over.{max u v} U :=
          ofArrows (fun i : Set.range φ.α ↦ i.1.1.1) (fun i ↦ i.1.1.2)
        have hle_cover : 𝒱.toSieve ≤ 𝒲.toSieve := by
          simpa [𝒲] using toSieve_le_range_family_of_hom R φ
        have h𝒲 : 𝒲.toSieve ∈ J U := by
          exact J.superset_covering hle_cover h𝒱
        have h𝒲le : 𝒲.toSieve ≤ Sieve.generate R := by
          -- The range family is literally a subfamily of the uncurry family for `R`.
          change
            Sieve.generate
                (Presieve.ofArrows (fun i : Set.range φ.α ↦ i.1.1.1) (fun i ↦ i.1.1.2)) ≤
              Sieve.generate R
          refine (Sieve.generate_le_iff _ _).2 ?_
          rw [Presieve.ofArrows_le_iff]
          intro i
          exact Sieve.le_generate R _ _ i.1.2
        exact ⟨𝒲, hφfin.to_subtype, h𝒲, h𝒲le⟩ }

-- Proof sketch: under the current presieve-level owner, a finite covering refinement of a
-- covering presieve already determines finitely many arrows of the original presieve whose
-- generated sieve is covering. Thus the source-text counterexample to `(2) → (3)` belongs to the
-- original covering-family presentation, not to this repaired presieve owner.
/-- Lemma 7.17.2 (4), repaired owner form: with the current presieve-level definitions, the
finite-refinement condition implies the finite-subcover condition. The source counterexample to the
reverse implication of the covering-family formulation is therefore not represented by
`HasFiniteRefinementProperty K V ∧ ¬ HasFiniteSubcoverProperty K V`. -/
theorem hasFiniteRefinementProperty_implies_hasFiniteSubcoverProperty
    {J : GrothendieckTopology C} {U : C} (hU : HasFiniteRefinementProperty J U) :
    HasFiniteSubcoverProperty J U := by
  refine
    { finite_subcover := fun R hR ↦ by
        obtain ⟨𝒱, h𝒱fin, h𝒱, hle⟩ := hU.finite_refinement R hR
        obtain ⟨φ⟩ := exists_hom_to_uncurry_family_of_sieve_refinement R 𝒱 hle
        let S : Set R.uncurry := Set.range φ.α
        let 𝒲 : SemiRepresentableFamily.Over.{max u v} U :=
          ofArrows (fun i : S ↦ i.1.1.1) (fun i ↦ i.1.1.2)
        have hS : S.Finite := by
          let _ : Finite 𝒱.index := h𝒱fin
          letI : Fintype 𝒱.index := Fintype.ofFinite 𝒱.index
          simpa [S] using Set.finite_range φ.α
        have hle_cover : 𝒱.toSieve ≤ 𝒲.toSieve := by
          simpa [S, 𝒲] using toSieve_le_range_family_of_hom R φ
        have h𝒲 : 𝒲.toSieve ∈ J U := by
          exact J.superset_covering hle_cover h𝒱
        -- The finite image of the comparison map is the required finite covering subset of `R`.
        refine ⟨S, hS, ?_⟩
        simpa [S, 𝒲, toSieve, toPresieve, ofArrows] using h𝒲 }

end CategoryTheory.GrothendieckTopology
