module

public import Mathlib.CategoryTheory.Sites.Canonical
import Mathlib.Tactic.Recall

@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory

universe v u uI

namespace CategoryTheory

section

variable {C : Type u} [Category.{v} C]
variable {I : Type uI} (F : I → Cᵒᵖ ⥤ Type v)

/- Domain-style sampling for Lemma 7.47.11:
- primary domain: Grothendieck topologies generated by a family of sheaf conditions;
- sampled owner abstractions:
  `Sheaf.finestTopology`,
  `Sheaf.sheaf_for_finestTopology`,
  `Sheaf.le_finestTopology`,
  `Sheaf.canonicalTopology`;
- source/core/bridge triage:
  `core/canonical`: `Sheaf.finestTopology`;
  `bridge/view`: the indexed family `F : I → Cᵒᵖ ⥤ Type v`, viewed as the set `Set.range F`.

Primitive data are the family of presheaves, or equivalently its range as a set. The indexed
phrasing `∀ i, Presieve.IsSheaf J (F i)` is derived API from the owner `Sheaf.finestTopology`.
-/

/-
Lemma 7.47.11: the Grothendieck topology on `C` generated by the family `F` is the canonical
mathlib construction `Sheaf.finestTopology (Set.range F)`. It is the finest topology on `C` for
which every `F i` is a sheaf.
-/
recall Sheaf.finestTopology

/-- For a Grothendieck topology `J`, being a subtopology of
`Sheaf.finestTopology (Set.range F)` is equivalent to asking that every `F i` be a `J`-sheaf. -/
theorem le_finestTopology_family_iff_isSheaf (J : GrothendieckTopology C) :
    J ≤ Sheaf.finestTopology (Set.range F) ↔ ∀ i, Presieve.IsSheaf J (F i) := by
  constructor
  · intro hJ i
    exact Presieve.isSheaf_of_le (F i) hJ
      (Sheaf.sheaf_for_finestTopology (Set.range F) (Set.mem_range_self i))
  · intro hF
    exact Sheaf.le_finestTopology (Set.range F) J <| by
      rintro _ ⟨i, rfl⟩
      exact hF i

end

end CategoryTheory
