module

public import ReasLib.Geometry.Euclidean.Plane.OrientedAngleToReal
import all ReasLib.Geometry.Euclidean.Plane.OrientedAngleToReal
import ReasLib.LinearAlgebra.Matrix.OrthogonalTransport

/-!
# Oriented angles in a positively oriented planar frame

This file packages the cancellation of a common unit frame from two planar vectors.
It is useful for angle observables expressed in a moving eigenframe: the frame itself
disappears before any scalar Taylor expansion is performed.
-/

public section

noncomputable section

open scoped EuclideanSpace Matrix

namespace EuclideanPlane

/-- A real `2 × 2` special orthogonal matrix is the positively oriented frame
generated by its first column. -/
theorem eq_frame_firstColumn_of_mem_specialOrthogonalGroup
    (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M ∈ Matrix.specialOrthogonalGroup (Fin 2) ℝ) :
    M = frame (WithLp.toLp 2 (fun i ↦ M i 0)) := by
  obtain ⟨hdiag, hoffDiagonal, _⟩ :=
    Matrix.mem_specialOrthogonalGroup_fin_two_iff.mp hM
  ext i j
  fin_cases i
  · fin_cases j
    · rfl
    · simpa [frame, perp_apply] using hoffDiagonal
  · fin_cases j
    · rfl
    · simpa [frame, perp_apply] using hdiag.symm

/-- The first column of a real `2 × 2` special orthogonal matrix has Euclidean
norm one. -/
theorem norm_firstColumn_eq_one_of_mem_specialOrthogonalGroup
    (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M ∈ Matrix.specialOrthogonalGroup (Fin 2) ℝ) :
    ‖WithLp.toLp 2 (fun i ↦ M i 0)‖ = 1 := by
  have hcolumn :
      M *ᵥ (![(1 : ℝ), 0] : Fin 2 → ℝ) = fun i ↦ M i 0 := by
    ext i
    fin_cases i <;>
      simp [Matrix.mulVec, dotProduct, Fin.sum_univ_two]
  have hnorm := Matrix.norm_toLp_mulVec_eq_of_mem_specialOrthogonalGroup
    M hM (![(1 : ℝ), 0] : Fin 2 → ℝ)
  rw [hcolumn] at hnorm
  simpa [EuclideanSpace.norm_eq, Fin.sum_univ_two] using hnorm

/-- Applying the same positively oriented unit frame to two coordinate vectors preserves
their oriented angle. -/
theorem oangle_frame_mulVec (e : EuclideanSpace ℝ (Fin 2)) (he : ‖e‖ = 1)
    (a b c d : ℝ) :
    orientation.oangle
        (WithLp.toLp 2 (frame e *ᵥ ![a, b]))
        (WithLp.toLp 2 (frame e *ᵥ ![c, d])) =
      orientation.oangle
        (!₂[a, b] : EuclideanSpace ℝ (Fin 2))
        (!₂[c, d] : EuclideanSpace ℝ (Fin 2)) := by
  let θ := orientation.oangle
    (!₂[(1 : ℝ), 0] : EuclideanSpace ℝ (Fin 2)) e
  have hframe : frame e = rotationMatrix θ :=
    frame_eq_rotationMatrix_oangle e he
  have hu : WithLp.toLp 2 (frame e *ᵥ ![a, b]) =
      rotation θ (!₂[a, b] : EuclideanSpace ℝ (Fin 2)) := by
    rw [hframe]
    ext i
    have hcoords : (EuclideanSpace.equiv (Fin 2) ℝ)
        (!₂[a, b] : EuclideanSpace ℝ (Fin 2)) = ![a, b] := by
      ext j
      fin_cases j <;> rfl
    have h := congrArg (fun v : Fin 2 → ℝ ↦ v i)
      (rotationMatrix_mulVec θ (!₂[a, b] : EuclideanSpace ℝ (Fin 2)))
    rw [hcoords] at h
    simpa [θ] using h
  have hv : WithLp.toLp 2 (frame e *ᵥ ![c, d]) =
      rotation θ (!₂[c, d] : EuclideanSpace ℝ (Fin 2)) := by
    rw [hframe]
    ext i
    have hcoords : (EuclideanSpace.equiv (Fin 2) ℝ)
        (!₂[c, d] : EuclideanSpace ℝ (Fin 2)) = ![c, d] := by
      ext j
      fin_cases j <;> rfl
    have h := congrArg (fun v : Fin 2 → ℝ ↦ v i)
      (rotationMatrix_mulVec θ (!₂[c, d] : EuclideanSpace ℝ (Fin 2)))
    rw [hcoords] at h
    simpa [θ] using h
  rw [hu, hv]
  exact orientation.oangle_rotation _ _ θ

/-- Simultaneously applying a real `2 × 2` special orthogonal matrix preserves
the oriented angle between two coordinate vectors. -/
theorem oangle_specialOrthogonal_mulVec
    (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M ∈ Matrix.specialOrthogonalGroup (Fin 2) ℝ)
    (a b c d : ℝ) :
    orientation.oangle
        (WithLp.toLp 2 (M *ᵥ ![a, b]))
        (WithLp.toLp 2 (M *ᵥ ![c, d])) =
      orientation.oangle
        (!₂[a, b] : EuclideanSpace ℝ (Fin 2))
        (!₂[c, d] : EuclideanSpace ℝ (Fin 2)) := by
  rw [eq_frame_firstColumn_of_mem_specialOrthogonalGroup M hM]
  exact oangle_frame_mulVec _
    (norm_firstColumn_eq_one_of_mem_specialOrthogonalGroup M hM) a b c d

/-- In a positively oriented unit frame, the principal real oriented angle is the
difference of the arctangents of the two coordinate slopes. -/
theorem oangle_frame_mulVec_toReal_eq_arctan_sub_of_pos
    (e : EuclideanSpace ℝ (Fin 2)) (he : ‖e‖ = 1)
    (a b c d : ℝ) (ha : 0 < a) (hc : 0 < c) :
    (orientation.oangle
        (WithLp.toLp 2 (frame e *ᵥ ![a, b]))
        (WithLp.toLp 2 (frame e *ᵥ ![c, d]))).toReal =
      Real.arctan (d / c) - Real.arctan (b / a) := by
  rw [oangle_frame_mulVec e he a b c d]
  exact oangle_toReal_eq_arctan_sub_of_pos a b c d ha hc

end EuclideanPlane
