module

public import Mathlib.CategoryTheory.IsConnected
import Mathlib.Tactic.Recall
@[expose] public section

-- Declarations for this item will be appended below by the statement pipeline.

universe v u

namespace CategoryTheory

variable {J : Type u} [Category.{v} J]

/- Domain-style sampling for Definition 4.16.1:
- primary domain: connected categories and zigzag connectivity in `CategoryTheory`;
- sampled owner-level declarations:
  `IsConnected`,
  `Zigzag`,
  `isPreconnected_zigzag`,
  `zigzag_isConnected`;
- best owner abstraction: the canonical owner is the class `IsConnected J`;
- primitive data: the owner class `IsConnected J`;
- derived API: `isPreconnected_zigzag`, `zigzag_isConnected`, and the source-facing zigzag
  characterization below.

Source/core/bridge triage:
- `source-facing`: the textbook zigzag characterization of connectedness;
- `core/canonical`: `IsConnected`;
- `bridge/view`: the equivalence theorem below, which restates the source wording in terms of the
  canonical owner. -/

/- Canonical recall: a category is connected when the equivalence relation generated by the
existence of a morphism between two objects has exactly one equivalence class; this is the
canonical mathlib notion `CategoryTheory.IsConnected`. -/
recall IsConnected

/-- Definition 4.16.1: a category is connected exactly when it is nonempty and any two objects are
related by the zigzag relation generated by the existence of morphisms in either direction. -/
theorem isConnected_iff_nonempty_and_zigzag :
    IsConnected J ↔ Nonempty J ∧ ∀ j₁ j₂ : J, Zigzag j₁ j₂ := by
  constructor
  · intro hJ
    letI : IsConnected J := hJ
    exact ⟨inferInstance, isPreconnected_zigzag⟩
  · rintro ⟨hJ, hzigzag⟩
    letI : Nonempty J := hJ
    exact zigzag_isConnected hzigzag

end CategoryTheory
